### ISSUE TITLE
[BUG]: PCSX2 Mysteroius and Unknown Crash

### ISSUE THREAD

**Issue by StShAzzy** [PCSX2/pcsx2#11345]
### Describe the Bug

the crash seems to be system specific, which makes it something hard to pin point.

### Reproduction Steps

Run the executable and watch it crash, and not produce a crash dump in the process, yey

### PCSX2 Revision

1.7.5867 (Possibly 1.7.5866 too)

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Working fine here. What CPU? Maybe it is non-AVX specific.

**Comment by StShAzzy** [comment]
if i knew, my CPU runs this fine, perhaps running under a VM with a mysterious CPU could do the trick

i had 2 people that weren't able to run this, one is my friend and the other was a guy in the discord server complain of the exact problem

**Comment by stenzek** [comment]
Not sure why you can't just list your hardware, as the issue template requests.

**Comment by StShAzzy** [comment]
my hardware has no issues with the current build, i'm here doing this so it can get hopefully fixed later

**Comment by StShAzzy** [comment]
my friend, is running it on a VM in a VPS because their computer is just too weak to actually run PCSX2 at a playable rate, so it's not much use asking which CPU is it, as it's emulated

**Comment by StShAzzy** [comment]
one of the people affected reported they have AMD A10-9700 (it's AVX2 capable)

**Comment by stenzek** [comment]
That is not an AVX2-capable CPU.

Anyway, I reproduced it in a VM with AVX disabled, looking into it now. It's very strange.

**Comment by StShAzzy** [comment]
> That is not an AVX2-capable CPU.

my bad...

**Comment by StShAzzy** [comment]
that is strange yes, my CPU isn't AVX2 capable, yet i'm able to run PCSX2 just fine

**Comment by stenzek** [comment]
Looking at it further, the crash I'm seeing is a result of the PCRE2 JIT in Qt, which seems to think that AVX2 is present, despite the xsavedisable option. So probably unrelated. Back to not knowing what the issue is :P

**Comment by stenzek** [comment]
I think this might be invalid. According to Majestic, reinstalling the VC Redist fixed his crash.

I'm still going to patch Qt to disable PCRE2 jitting, because it makes it impossible for me to debug the SSE4 build, as I don't have a CPU that old, and have to rely on xsavedisable.

**Comment by StShAzzy** [comment]
if PCRE2 JIT is the problem, then it would be a bug in Qt?

**Comment by stenzek** [comment]
That's the crash that **I am seeing**, in a Win11 VM with AVX disabled at the bootloader level. I suspect it's different to what these other users are getting.

**Comment by stenzek** [comment]
#11346 drops the compiler back to clang-17, so there shouldn't be any difference compared to v5865.
#11347 disables the PCRE2 JIT, but I suspect that's only needed for my janky xsavedisable VM setup.

**Comment by koscrob** [comment]
Because the issue is happening on an older AMD CPU, I venture to guess that it's something I encountered with Xbyak. The CPU detection code was broken in Xbyak::util::Cpu for legacy AMD CPUs. I fixed it upstream a few months ago so updating to Xbyak 7.06 should fix it.

**Comment by stenzek** [comment]
Good catch, thanks. We probably should just swap over to cpuinfo for multi-ISA selection anyway.

**Comment by smashed-penguin** [comment]
the instant crash on launch still happens to me too since the aforementioned mentioned version (Intel i5-8400)

**Comment by refractionpcsx2** [comment]
did you upgrade your VC redistributable?
https://aka.ms/vs/17/release/vc_redist.x64.exe

**Comment by smashed-penguin** [comment]
thx. I don't usually update VC since Windows Update typically grabs it not long after a release goes public/stable.
