### ISSUE TITLE
[Folder Memory Card] GTA3 / San Andreas / Vice City saves are being ignored.

### ISSUE THREAD

**Issue by Ryudo300** [PCSX2/pcsx2#1136]
Report originally came from the Forums (http://forums.pcsx2.net/Thread-Memory-Card-Problem-GTA-3-and-Vice-City?pid=503684#pid503684).

For him it only happened with GTA3 and Vice City, while San Andreas worked fine. But when I tested San Andreas, it started a new game for me, despite the folder being right there. As you can see here:
![bandicam 2016-01-20 22-59-12-991](https://cloud.githubusercontent.com/assets/10039778/12464555/d2d80192-bfc9-11e5-8b15-76593c05476a.png)
And then this is what I get in-game if I try to manually load it. (Since it starts a new game automatically, instead of loading my Save)
![pcsx2 2016-01-20 23-02-36-442](https://cloud.githubusercontent.com/assets/10039778/12464565/e1f958ec-bfc9-11e5-9ad0-6e65e769d22d.png)

When using an actual Memory Card it works fine:
![pcsx2 2016-01-20 23-03-28-607](https://cloud.githubusercontent.com/assets/10039778/12464602/08c1b280-bfca-11e5-82dc-da3e17b0e38b.png)

@AdmiralCurtiss Any clues? It's a bit weird that it works on San Andreas for him, but it isn't working here. So I'm not really sure what's going on. Could it have something to do with the filenames? Maybe some weird characters in the titles could cause it to be ignored, which would explain why it's not being read every time?

**Comment by AdmiralCurtiss** [comment]
Can you upload a file memory card that works so I can compare? I don't have any of the GTA games though so this will be difficult to debug.

It shouldn't be filenames though, [I'm handling those](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/gui/MemoryCardFolder.cpp#L1526), unless maybe the game uses extra spaces that Windows doesn't like or something of the sort?

**Comment by AdmiralCurtiss** [comment]
Ah, I think I see the problem. Some of these files end in multiple dots (ie, `1: Keep your Friends Clo...`) which get quietly truncated by Windows. If that's all it is the fix should be fairly simple, just need to update that function I linked above to consider that.

**Comment by AdmiralCurtiss** [comment]
Though that only would prevent some of them from loading, not all of them. Still, it's a thing that needs to be fixed anyway, but it might not actually be the root cause of this.

**Comment by Ryudo300** [comment]
Are you still in need of the Memory Card file? 

And yeah, that's why I thought it was related to filenaming somehow. Since it was working for him on San Andreas, but on my side it wasn't.

**Comment by AdmiralCurtiss** [comment]
May or may not be fixed by #1156, feel free to test.

**Comment by refractionpcsx2** [comment]
I may have merged the PR, apologies if you wanted it left as a PR, but now you can just grab the latest development build from the pcsx2 website :)

**Comment by refractionpcsx2** [comment]
Assuming this is now resolved, please post if it isn't

**Comment by LordArchantos** [comment]
Issue still exists in v1.5.0-dev-2673-g15733ed8c. When using a folder memory card with GTA3, the game only sees an empty memory card when attempting to load, even when trying to load right after saving in-game.

**Comment by shortcat359** [comment]
Still happens in Vice City, on saving on the first opportunity ("In the beginning...")
pcsx2-v1.5.0-dev-3023-g5f099b1be-windows-x86

**Comment by Solniz** [comment]
> Still happens in Vice City, on saving on the first opportunity ("In the beginning...")
> pcsx2-v1.5.0-dev-3023-g5f099b1be-windows-x86

Old thread but I found a somewhat simple workaround. Basically, you just need to upload the save to your memory card (through MyMC) with an .xps (x-port file format). For example, let's say you download a codebreaker save, all you have to do is use "ps2 save builder" to convert it to .xps - the option 'save as'. For some reason both the game and emulator only read the save file if it was installed as .xps onto the memory card.

**Comment by cracraafiam** [comment]
1. 
Duplicate of #

**Comment by F0bes** [comment]
This isn't a support page. Please go to our [Forum](https://forums.pcsx2.net/) or [Discord](https://discord.com/invite/TCz3t9k)

**Comment by RedDevilus** [comment]
From what i recall it has to either be a new save game with the new index or convert to file memcard and back to folder memcard.

**Comment by ERRA-Augment** [comment]
Was i asking for support? No, telling you your shit is broken and its not still working after like 10 years. Im not using an old save am trying to create a new one, pscx2 wont even make the folder for the game, if i could save my game at all instead of using save states i wouldnt even be commenting here,  ty to the other commenters, but that isnt the issue. I'm trying to play the game at all, not convert files or save my old game. You literally cant save this game. This is like what a 10 year old issue also. Ill find someone elses save online and try to convert it into my folder and see if that works.

**Comment by refractionpcsx2** [comment]
Well, it works fine for everybody else, so you're either using an old version, or your memcard folder is broken.

I'd suggest maybe updating to the latest dev build and making a new memcard folder.

And not being fucking rude.
