### ISSUE TITLE
[BUG]: Unable to select video or audio codec for capture on KDE AppImage

### ISSUE THREAD

**Issue by TheTechnician27** [PCSX2/pcsx2#12715]
### Describe the Bug

Using the v2.3.370 AppImage on KDE, I'm unable to select a codec for video or audio capture at `Settings` > `Graphics` > `Recording`. The Flatpak works just fine, and @Mrlinkwii's testing shows it working fine on Ubuntu which uses GNOME. Instead of a list, clicking the codec option simply shows a list where 'Default' is the only option. Unable to tell if the format option is affected since I cannot select a codec first. @kamfretoz has said this only works on Ubuntu.

### Reproduction Steps

Download AppImage v2.3.370, run it on KDE. Try to change the option.

### Expected Behavior

The list should be the same as on Flatpak.

### PCSX2 Revision

v2.3.370

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Manjaro

### Logs & Dumps

![Codec setting](https://github.com/user-attachments/assets/6af480e2-fa45-4e57-bf58-4907a2c9afc2)

**Comment by TheTechnician27** [comment]
Tested in v2.5.28, and it now works. Possibly fixed by #12897, but cannot say for sure without testing.

**Comment by AmandaRoseChaqueta** [comment]
It has been partially fixed. But a new issue has been made so it's more clear what other problems need to be solved now that you can actually make recordings with the appimage.
