### ISSUE TITLE
Gran Turismo series PCSX2 Crashes

### ISSUE THREAD

**Issue by MarcoEstevez** [PCSX2/pcsx2#1313]
PCSX2 Crashes when going in races, no issues while on menus.

PCSX2 1.5.0-20160426190932 - compiled on Apr 26 2016
    Operating System =  Microsoft Windows 10 Home (build 10586), 64-bit
    Physical RAM     =  7986 MB
    CPU name         =  Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz

OpenGL information. GPU: GeForce GT 755M/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 364.72

---

I did several tests, and I managed to reproduce only on IR greater than Native.

![image](https://cloud.githubusercontent.com/assets/3447089/14836241/f0a23c38-0c0e-11e6-9b35-1d59047d66ae.png)

If I start the game with Native res. then it works fine, while on game If I change IR to 2x game works during few seconds at full speed until it crashes after few seconds.

---

Im not sure if that is a general issue or its only me due a weak GPU, but I remember being able to play it a 3x on previous builds.

---

Im not sure if that related or not but PCSX2 Console get spammed with thousands of messages.

SummerTime=0
Timezone=60
SummerTime=0
Timezone=60
SummerTime=0
Timezone=60
SummerTime=0
Timezone=60

**Comment by willkuer** [comment]
Can you please post the full emulog after the crash? (can be found in logs/emulog.txt in the directory of pcsx2.exe)

**Comment by FlatOutPS2** [comment]
Related to this: http://forums.pcsx2.net/Thread-Gran-Turismo-4-crash-in-OpenGL-Mode?page=2
And #1314: There was a regression in git builds 650/651, that made it more likely to crash than usual.

The log messages are because you probably haven't been to the bios(boot with no disc selected) to set the time(zone).

**Comment by gregory38** [comment]
Yes, it is expected. And it will remain like that until I (or someone that beat me) properly fix the handling of the bad effect.

**Comment by MarcoEstevez** [comment]
Great, Ill try to set up bios as you said, I just tried different ones yesterday, so most probably is that.

I will also re-test with @gregory38 fix as soon as I get home.

**Comment by MarcoEstevez** [comment]
Same with latest build:

LOG: https://drive.google.com/file/d/0ByJrCj2X0ZpAQXhjTHNDczBXb3c/view?usp=sharing

![image](https://cloud.githubusercontent.com/assets/3447089/14859062/cd43cede-0ca2-11e6-8662-c24d6c964089.png)

**Comment by willkuer** [comment]
Can you please try without gzip?

**Comment by MarcoEstevez** [comment]
Sure. same thing

https://drive.google.com/file/d/0ByJrCj2X0ZpAcHFrUml4YmlFT0k/view?usp=sharing

**Comment by gregory38** [comment]
The crash is normal. There are too much memory allocation in GSdx. Until it is properly fixed, you need to reduce the upscaling or use a custom resolution.

**Comment by MarcoEstevez** [comment]
However no crashes on Native or Custom, that surprised me cause I've set custom to HD (1920x1080) what I believe its greater resolution than 2x.

**Comment by MarcoEstevez** [comment]
3 secs faster than me  :-)

I just heard than integer scales were better than Custom ones.

**Comment by ssakash** [comment]
Custom uses RT buffer size equivalent to the scaled value (lower buffer size) whereas native scaling resolution use a bigger buffer size which increases the memory consumption.

**Comment by MarcoEstevez** [comment]
Thanks, for your time and explanations. I don't think this is an issue or regression, anymore. I did use Custom Res before until @willkuer told me one day Native scaling is much accurate than custom, and then my confusion.

So both fashions, Custom and Native has benefits and counterparts  :-D.

**Comment by gregory38** [comment]
Native scaling is better, however it highlight bugs in texture management. You still have it in custom resolution (monitor you vram and you will see a huge allocation).

**Comment by prafullpcsx2** [comment]
Crash still happens if you set the brightness to 0 ingame?

**Comment by willkuer** [comment]
It needs to be like that. Native scaling is naturally an automorphism. Custom resolution needs rounding. Additionally scaling is always less 'accurate' or just not the same as native resolution. The effect you see is - if i understood correctly - rather related to a wrong or lets say inacurate implementation.

**Comment by gregory38** [comment]
The bug is the renderer allocating hundreds of framebuffer instead of 1. Integer upscaling requires 5-20 MB by framebuffer. Due to the useless allocated fb, it becomes 500-2000MB of extra memory. When I will fix the bug, memory will be small even at 8x

**Comment by gregory38** [comment]
If you want to play the game, use the stable release. (Until I fix the git version)

**Comment by MarcoEstevez** [comment]
Well... to me the game looks great even at Native resolution, custom one does not seem to have any graphical problems acording to my eyes. I just opened this issue cause I though it was a new introduced bug. 

Out of curiosity, what makes stable ones works?, does stable use less memory?

**Comment by gregory38** [comment]
Stable is stable by definition

Stable has some hack to avoid the issue but it break some rendering. Git is work in progress with the intended goal to fix most issue correctly.

**Comment by MarcoEstevez** [comment]
Thanks @gregory38, I'm looking forward your upcoming memory improvement fix.

**Comment by gregory38** [comment]
I'm looking into it. Some stat number from Metal Gears Solid 3 (but I suspect the same effect is used for GT4). Done with a scaling of 4x

Before (2994MB):
```
T:Perf	ID:41251	S:Info	=> MEM: RO Tex 12MB. RW Tex 48MB. Target 2680MB. Depth 160MB
T:Perf	ID:41251	S:Info	=> MEM: Surface Pool 94MB
```
After (total 460MB):
```
T:Perf	ID:40495	S:Info	=> MEM: RO Tex 14MB. RW Tex 48MB. Target 160MB. Depth 160MB
T:Perf	ID:40495	S:Info	=> MEM: Surface Pool 78MB
```

So far the draw call is only skip but I hope to emulate it properly.

**Comment by gregory38** [comment]
Actually I pushed my change to master. So could you test the impact on GT4? Thanks you.

**Comment by FlatOutPS2** [comment]
I tried it on Killzone(another game with RAM spike issues) , it uses 1.5GB less now. :)

I'll try it with GT4 too.

**Comment by gregory38** [comment]
Great. Note I open a meta issue for those games (#1318)

**Comment by FlatOutPS2** [comment]
No change on GT4. It's fine on native and 2x, with both pre-RAM fix and current master with fix. But on 3x native it rises by at least 2GB and crashes, with both versions.

**Comment by gregory38** [comment]
Too bad. Either it isn't the same effect or I don't catch it properly. It could be useful if you manage to generate me a gs dump at the ram spike.

**Comment by gregory38** [comment]
I have a ram spike on prince of persia. I will debug this one first.

**Comment by MarcoEstevez** [comment]
No changes on GT3 either. stops working at same point: IR 2X.

**Comment by MarcoEstevez** [comment]
here you can find gs dump, if that helps

https://drive.google.com/file/d/0ByJrCj2X0ZpAc3Rzd0NHcGFvTUE/view?usp=sharing

**Comment by gregory38** [comment]
Thanks I can reproduce the issue.

**Comment by tabnk** [comment]
Look forward to a fix soon :)

**Comment by gregory38** [comment]
It seems brightness/contrast options don't work as expected.
I would love to have additional dump with brightness/contrast value set to big value. In a way that you can easily see the effect. So it is easier for me to compare SW/HW rendering.

**Comment by DonelBueno** [comment]
The differences between SW and HW in GT4 are the following:

1) Spikes in VRAM Usage
2) Broken Brightness Config (Always Renders at Bbrightness 0)
3) Missing Specular Lighting
4) Missing Black & White Effect in Failed Licenses Result

**Comment by gregory38** [comment]
Thanks for the summary. But so far, I would like a gs dump for issue 2 so I can debug it properly on my side.
Do you have the VRAM skipes in 3 or 4 scene ?

**Comment by tabnk** [comment]
Here is the GS dump for issues 2 with brightness/contrast value set to big value.
https://www.sendspace.com/file/4khzvy
![gsdx_20160503221910](https://cloud.githubusercontent.com/assets/10874582/14986230/834c2e54-117d-11e6-86e0-3de320665598.jpg)

**Comment by gregory38** [comment]
Ok. Yeah, the effect is badly detected. Everything is broken ;)

**Comment by DonelBueno** [comment]
@gregory38: Effect 3 happens during all the race, so no, I don't have VRAM spikes during it.

I've just tested effect 4 for VRAM spikes. The problem is, it was tested at native resolution, since anything above it crashes the emulator. At native resolution, it seems to cause VRAM spikes, but I may be wrong.

**Comment by gregory38** [comment]
Ok. Let's start with the brightness effect first. It is already complex enough.

**Comment by MrCK1** [comment]
Technically the specularlighting isn't missing on cars, but alot of the vertices are being shaded improperly/sometimes specular will flicker. I'll post a comparison later

**Comment by gregory38** [comment]
Honestly the brightness effect is completely wrong. If the game uses a similar trick for another effect, it will be broken too. Memory spikes are a typical symptom of a bad emulated effect. Give me a couple of days (weeks) to solve the first effect (well I hope I can find a solution).

**Comment by MrCK1** [comment]
I wonder if the VRAM effects are related to sprites. I did a test in the tunnel on SS Route 6 (where sprites can be seen through walls and flicker) My VRAM usage was going all over the place. Maybe the issue is sprite-related?

Tunnel GS Dump: http://www.filedropper.com/gsdx20160504223545

**Comment by gregory38** [comment]
95% of the post-processing effects are done with sprite. So yes it is sprite related ;) But the real issue is offset in the RT (instead of vertex offset). GSdx will allocate wrongly a 5MB buffer (*upscale^2) for each offset (between 100-300).

**Comment by MrCK1** [comment]
As of revision 265ea82 (721) License fail screens now show properly; but we have another problem...

The last build I ran was 705, so I'll check recent commits for regressions
GS Dump: http://www.filedropper.com/gsdx20160506165406
![gsdx_20160506165406](https://cloud.githubusercontent.com/assets/16314399/15085922/5a445b64-13ab-11e6-8de4-0c267125f37c.png)
![gsdx_20160506165719](https://cloud.githubusercontent.com/assets/16314399/15085965/a1c87362-13ab-11e6-9393-a77c097c9a51.png)

**Comment by gregory38** [comment]
Msi afterburner (or others tools)? (Someone post the same kinds of screenshot in the forum)

**Comment by MrCK1** [comment]
oops, my fault. I will say that the black box glitch in the 2nd screenshot has been going on for 2 or 3 months; but reproducing it consistently is the problem

**Comment by gregory38** [comment]
Please name your dump properly. I have hundred of dump named gsdx_xxxxx.

And what is the issue of the dump. I have the license fail screen. It seems to be correct.

**Comment by MrCK1** [comment]
The dump was for the license screen, (since the bug was new)  but I haven't been able to duplicate the issue. Just ignore it at this point

**Comment by FlatOutPS2** [comment]
> As of revision 265ea82 (721) License fail screens now show properly

What has improved?

**Comment by MrCK1** [comment]
The screen used to have checkered boxes all over, similar to previously broken effects. I guess it's been fixed for longer than I thought

**Comment by FlatOutPS2** [comment]
> The screen used to have checkered boxes all over, similar to previously broken effects. I guess it's been fixed for longer than I thought

I hoped you meant it was shown in black and white like it should. :p

**Comment by tabnk** [comment]
GT4 headlight see-through could be relate effect issue

![gsdx_20160503223112](https://cloud.githubusercontent.com/assets/10874582/15095539/30dc36cc-14fd-11e6-809f-909c9d94403d.png)

GS dump here https://www.sendspace.com/file/kwbva7

**Comment by FlatOutPS2** [comment]
You can see headlights through car windows? :That's sooo unrealistic. :D

**Comment by DonelBueno** [comment]
@FlatOutPS2 Yes, it is, sadly =(

**Comment by gregory38** [comment]
Could someone explain me the `see headlights through car windows` issue ?

**Comment by tabnk** [comment]
Actually GT4 headlight not limit to car windows. It's pass through all.

**Comment by DPersonalized** [comment]
Does setting Skipdraw to 28 remove the light from the headlights?

**Comment by FlatOutPS2** [comment]
> Does setting Skipdraw to 28 remove the light from the headlights?

It doesn't show in software mode though, unlike Burnout's sun.

**Comment by gregory38** [comment]
One ought to stop using skipdraw with openGL. Nowadays, it just breaks everythings.

Here my dump replay from the SW:
![gt4_sw](https://cloud.githubusercontent.com/assets/1569559/15098695/4264e29a-1543-11e6-81ba-a88d93365fc0.png)

Could you confirm me that rendering is wrong. If yes, it is likely a depth reading issue.

**Comment by tabnk** [comment]
Yellow car right side headlight obviously wrong.

**Comment by FlatOutPS2** [comment]
It's depth issue in hardware mode, headlights(and sun) shine through objects.

**Comment by gregory38** [comment]
@tabnk but you don't have the issue when you play the game with the SW renderer, do you?

 gs dump can't replay well depth transfer between EE and GS. So it is my guess of the issue. Unfortunately I don't see any reading of the depth. However I do see some depth write. Strange. Anyway the issue is minor and hard to debug so I won't look into it.

By the way, what is the vram status on the future git (just pushed the latest update)? Note: you need CRC on partial.

**Comment by FlatOutPS2** [comment]
The headlights might be a minor issue, but the sun can obscure the rearview mirror or even the next corner at some tracks.

**Comment by tabnk** [comment]
GT4 headlight is correct in software mode.
GT4 hardware mode: 
Brightness fixed 
VRAM spike doesn't crash pcsx2 but still high usage around 1900MB at 3xnative.

**Comment by tabnk** [comment]
Finally a more obvious headlight issue in GT4. Headlight see through wall now.

![gsdx_20160509112303](https://cloud.githubusercontent.com/assets/10874582/15103010/eda01266-15d8-11e6-832f-84b1526be082.png)

GS dump here https://www.sendspace.com/file/c8d08o

**Comment by MrCK1** [comment]
That's actually part of a longstanding bug, it's been there forever AFAIK

**Comment by DonelBueno** [comment]
No clue on how to solve the VRAM spikes? They happen just because of the crossfade effect not being properly emulated?

**Comment by gregory38** [comment]
Yes. Some effects triggers the allocation of 50-150 framebuffer. Each framebuffer is around 3-5MB * upscale^2.
If the emulation effect is corrected, it will require only a single framebuffer. You could imagine the impact on the mem (and the perf boost too). 
Anyway I think I will provide an option to choose either a small or a big framebuffer. It could help to reduce the size of the spike until a better solution is found.

**Comment by MrCK1** [comment]
Is there anything else major they needs to be resolved here? The game is OK for now AFAIK.

**Comment by FlatOutPS2** [comment]
It has definitely improved. D3D11 still has a massive RAM spike at 8x native with large framebuffer enabled, but it doesn't crash and OGL still crashes at 8x, but manages to survive 6x with large framebuffer disabled.
That's a definite improvement over the crashes at just 3x or 4x or worse on both renderers.

**Comment by gregory38** [comment]
@FlatOutPS2 The crash is because openGL misses memory. However I don't know who is the bad guy RAM or VRAM? Could you monitor both of them to find the culprit ?

**Comment by FlatOutPS2** [comment]
Looks like it's the VRAM. The massive RAM usage I saw with D3D11 isn't near as high in OGL at the moment of the crash, but the VRAM is on/near the max.

**Comment by gregory38** [comment]
I pushed some commits to be more user-friendly on master but nothing is tested so far. 

Could you tell me if the available memory of your GPU is correctly reported. If yes, try to load the beast, hopefully it will print out-of-memory message instead of a crash.

**Comment by FlatOutPS2** [comment]
It reports close to 2 times more VRAM than I have available.

**Comment by gregory38** [comment]
I.e? Default is around 3870 MB (4096-256).

**Comment by FlatOutPS2** [comment]
It reports 3840.

**Comment by gregory38** [comment]
Ok doesn't work so. It is the default value. Feel free to play with the opengl code in last commit (GSDeviceOGL.cpp)

**Comment by FlatOutPS2** [comment]
`GL_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX` reports the wrong value, but `L_TEXTURE_FREE_MEMORY_ATI` seems to report the correct VRAM size.

**Comment by gregory38** [comment]
`_NVX` is for nvidia GPU normaly.

**Comment by gregory38** [comment]
Maybe you could test the others enum
https://www.opengl.org/registry/specs/NVX/gpu_memory_info.txt
```
        GL_GPU_MEMORY_INFO_DEDICATED_VIDMEM_NVX          0x9047
        GL_GPU_MEMORY_INFO_TOTAL_AVAILABLE_MEMORY_NVX    0x9048
        GL_GPU_MEMORY_INFO_CURRENT_AVAILABLE_VIDMEM_NVX  0x9049
```

**Comment by FlatOutPS2** [comment]
Yes, it seems it was just using the default when forcing _NVX.
`else if (GLLoader::found_GL_ATI_meminfo) ` does not trigger though, but like I posted it does show the correct VRAM when I removed the if functions.

 `No extenstion supported to get available memory. Use default value` was printed on the log, but it was hidden on the previous line. `OpenGL renderer is slow on AMD GPU due to inefficient driver. Sorry.` lacks the `\n` to move it to the next line.

**Comment by gregory38** [comment]
So what is the value returned with AMD. I want to know if it is the full vram or only the remaining one.

**Comment by FlatOutPS2** [comment]
It is the full vram.

**Comment by gregory38** [comment]
Ok.  Remain to see what happen when a lots of textures are allocated.

**Comment by FlatOutPS2** [comment]
It modified the latest master so that it prints the VRAM deficit, it only crashes once memory usage is twice the available VRAM. Maybe close GS Window with a emergency warning before this happens?

**Comment by gregory38** [comment]
Hum, it isn't twice, it is the 4GB limit of a process. In this case maybe we can keep the ~3800 default limit.

**Comment by gregory38** [comment]
Need someone with 1GB card to test

**Comment by DonelBueno** [comment]
![](https://cloud.githubusercontent.com/assets/16314399/15085965/a1c87362-13ab-11e6-9393-a77c097c9a51.png)

This still happens to me in HW mode. Even in OGL and with accurate options enabled.

**Comment by FlatOutPS2** [comment]
> This still happens to me in HW mode. Even in OGL and with accurate options enabled.

Are you using the NTSC version as well? I've never seen it in the PAL version. Can it happen during any event?

**Comment by MrCK1** [comment]
I can actually shed some light on this. From what I remember, the issue popped up in February while we were adjusting RT sizing, depth, or memory management but I don't remember what exactly. Despite this fact, It's not a regression. 

I tried to pin it down before, but I never found it related to a specific build. The only thing I was ever certain on was that it only happens on specific maps. I own the NTSC copy btw. 

I'll check later, but I might've mentioned this in another one of my issues a while back.

**Comment by DonelBueno** [comment]
Yes, mine is NTSC. It also happens in GT3 (which is also NTSC).

**Comment by Enverex** [comment]
I'm getting the earlier discussed memory issue in Gran Turismo 4 here as well. It's fine until the camera changes to look at your car at the start of the race, after a few seconds the framerate drops to <5fps.

Full console log from PCSX2 is here - https://www.hastebin.com/qahuhitajo.py

Lines of note are:
```
PCSX2 1.5.0-20170703192203 - compiled on Jul  8 2017
Savestate version: 0x9a0d0000

Host Machine Init:
	Operating System =  Linux 4.11.9-1-ARCH x86_64
	Physical RAM     =  7690 MB
	CPU name         =  Intel(R) Core(TM) i7-5775C CPU @ 3.30GHz
	Vendor/Model     =  GenuineIntel (stepping 01)
	CPU speed        =  3.296 ghz (8 logical threads)
	x86PType         =  Standard OEM
	x86Flags         =  bfebfbff 7ffafbbf
	x86EFlags        =  2c100000

x86 Features Detected:
	SSE2.. SSE3.. SSSE3.. SSE4.1.. SSE4.2.. AVX.. AVX2.. FMA
```
```
Current Renderer: OpenGL (Hardware renderer)
Available VRAM/RAM:3840MB for textures
GSdx Lookup CRC:0
```
Note that it seems to detect the card as 3840MB, despite the fact it's a 6GB card (and I have nothing else open). The card is an Nvidia GTX 1060 (using the official drivers).
```
Unknown device 'dev9x'
Available VRAM is very low (-48811521), a crash is expected ! Disable Larger framebuffer or reduce upscaling!
GSDX OUT OF MEMORY
```

**Comment by MrCK1** [comment]
3840 is always the reported memory available. Did you see the previous comments?

**Comment by Enverex** [comment]
I'd somehow missed that. Still, I assume the overall issue persists as I'm seeing the "GSDX OUT OF MEMORY" error when using only 4x and no large framebuffer.

**Comment by gregory38** [comment]
4x is too much for this game. Otherwise, the only solution is to use custom resolution (but I removed it from the linux GUI, so you need to edit the ini file manually).

**Comment by mirh** [comment]
Come to think - might [latest](https://www.reddit.com/r/emulation/comments/75posm/fyi_latest_nvidia_drivers_38792_fixes_ram_usage/) nvidia driver have improved this?
...
Is this reproducible outside of nvidia?

**Comment by lightningterror** [comment]
It wasn't a driver issue but texture cache and channel effect which caused high vram spikes and eventually a crash.
Then there's also clamping causing a crash #2240

**Comment by d4d385** [comment]
Hello everybody,
when I am playing GT4, the view of the car changes randomly on its own, I should control the camera view with the select of my PS1 pad, but the system changes it for me every minutes. Does that happens to you guys as well?  
Thank you

**Comment by MrCK1** [comment]
@d4d385 This isn't the place for general support. Please redirect your question over to the [PCSX2 forums]([url](https://forums.pcsx2.net/index.php)). Thanks!

**Comment by FlatOutPS2** [comment]
See: https://forums.pcsx2.net/Forum-General-Discussion-and-Support-Windows

**Comment by refractionpcsx2** [comment]
Is this crash still happening?

**Comment by MarcoEstevez** [comment]
These were mi specs back when I opened this issue.

CPU name = Intel(R) Core(TM) i7-4700MQ CPU @ 2.40GHz
OpenGL information. GPU: GeForce GT 755M/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 364.72

Since I upgraded my hardware:
CPU name         =  Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz
NVIDIA GeForce RTX 2060

I haven't got that issue anymore. but I feel besides hardware, lot have improved on the emulation side, shader cache, x64 builds, vulkan, etc I think is safe to close this, or at least I can't reproduce myself
