### ISSUE TITLE
Meta: GSdx HW half-bottom screen issue

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1339]
Let's list all games impacted. This way it would be easier to check any potential implementation.

- [ ] mercenaries
- [ ] destruction derby
- [ ] MGS3 codec (some versions)
- [ ] get away

**Comment by gregory38** [comment]
@refractionpcsx2 @ssakash @FlatOutPS2 @prafullpcsx2
I let's you complete the list :+1:

**Comment by FlatOutPS2** [comment]
The Getaway doesn't have a half-screen bug as far as I know, it did have a fog wall, but it's been fixed.
Black Monday does have a depth issue with sun rayes, not sure if it's a half-bottom screen issue.

Games with HW half-bottom screen issue:
Need For Speed Hot Pursuit 2
Killzone
Total Immersion Racing(fog in wet races)
TimeSplitters (Future Perfect)
WRC II Extrme (fog in distance)

**Comment by gregory38** [comment]
I need to check my get away dump (or maybe I mix it with another game)

**Comment by prafullpcsx2** [comment]
Oops. Sorry I directly added few games to the first list. i hope gregory wasn't editing the post at the same time.

**Comment by refractionpcsx2** [comment]
I added one :P Cant remember many off hand

**Comment by pepiczech77** [comment]
NFS Underground could be probably added too.

**Comment by refractionpcsx2** [comment]
Does that have the half screen issue? I've never seen it on that game

**Comment by FlatOutPS2** [comment]
I believe most, if not all, PS2 NFS games have the issue. NFS Underground 2 and Most Wanted definitely.

**Comment by refractionpcsx2** [comment]
Alrighty, added all those to the list.

**Comment by pepiczech77** [comment]
I think so. Bottom half of the screen is blurred or something and it misses fog. 
Probably even NFS Carbon has it, but it is not the only issue there, because the game looks too green in HW mode. I will check those games on real PS2 soon.

**Comment by refractionpcsx2** [comment]
Yeh carbon had a new engine I believe, so it might be different, need to test it, I have it but haven't touched it in a while

**Comment by pepiczech77** [comment]
I tested it, bottom half of the screen is rendered differently than the upper half.

**Comment by refractionpcsx2** [comment]
OK I'll add that one as well then

**Comment by refractionpcsx2** [comment]
I've also had a scan through the forums to try and find some other games with these issues and added them to the list.

**Comment by MarcoEstevez** [comment]
Test drive unlimited has that problem also but only under hw custom resolution hw scaled native is not affected

**Comment by FlatOutPS2** [comment]
More bottom half screen issues:
Judge Dredd: Dredd VS Death
Star Wars: The Force Unleashed

**Comment by gregory38** [comment]
Sigh... The list might be shorter if we list the game that don't have the issue.

**Comment by FlatOutPS2** [comment]
And what about right(vertical) half screen issues?

**Comment by gregory38** [comment]
Open a new issue :p do you have lots of them ?

**Comment by FlatOutPS2** [comment]
No, just two I know of, and a possible third and fourth.

**Comment by gregory38** [comment]
Ok. Open a new issue with the list of game. Could still be useful one day.

**Comment by pepiczech77** [comment]
Seems like TOCA Race Driver 3 could be added too.

**Comment by refractionpcsx2** [comment]
Added

**Comment by FlatOutPS2** [comment]
FIFA 2003 doesn't have the issue, FIFA 2006 does. So it probably only affects FIFA from 2004-2006 and later.

**Comment by refractionpcsx2** [comment]
Updated that one, thanks :)

**Comment by FlatOutPS2** [comment]
I meant the issue started in 2004-2006, later games are affect too. At least up to FIFA 14.

**Comment by refractionpcsx2** [comment]
Sorry, fixed :P

okay went through a bunch of my DVD's here's other games i found with the issue plus some other misc bugs which are outside the scope of this PR


Half Screen issues:
Brothers in Arms - Road to Hill 30 - All videos, 2D and 3D
DragonBall Z - Buidokai Tenkaichi 3 - Transitions suffer from half screen issue, rest of game ok.

Other GS Bugs:
Battle Engine Aquila - Flickering Videos with preload frame
Burnout 3 Takedown & Burnout Dominator - Thick bars of light and black sky
DT Racer - Shadows in wrong place in hw and sw

**Comment by FlatOutPS2** [comment]
The Burnout issues are known, though the thick bars onscreen might have regressed in OpenGL. I think they were fixed for OpenGL in an earlier version.
You didn't even mention the sun shining through walls. :p

**Comment by refractionpcsx2** [comment]
I didn't play it that much :P I was literally just loading them until they were ingame to see if the issue was there, I went through about 100 games, I wasn't thoroughly testing them xD

**Comment by gregory38** [comment]
Burnout depends on the preload option. But the game is globally broken anyway. Generally speaking the texture cache doesn't support texture/framebuffer offset.

On the SW renderer, it is easy you just allocate all the memory and you handle manually the dynamic width. On the HW it is awful. First there is upscaling and then you can't reconfigure the width on the fly. So the trick is to detect that address X is included in buffer Y and not the start of a new buffer Z. Intially I wanted to use the size of the draw, if the game draw into a 640x480 rectangle, you can guess the size of the buffer. I was naive, you have some 64x2500 draw sometimes....

**Comment by refractionpcsx2** [comment]
Sounds horrible :(

**Comment by gregory38** [comment]
The GS memory is awful. Everything is allowed. The only limitation is that Color/Depth buffer must be aligned on a page boundary and the remaining (texture/clut) must be aligned on a block boundary. Otherwise the rule is "there is no rule" ;)

**Comment by refractionpcsx2** [comment]
Well I suppose that makes sense, considering the limitations of the GS, the developers needed free reign to come up with clever tricks :P

**Comment by FlatOutPS2** [comment]
The FIFA games affected are from 2006 onwards. 2004 doesn't have it and highely likely 2005 doesn't either, as the next engine upgrade was 2006 and that engine was used on all subsequent PS2 FIFA games(and thus all have the same issue).

**Comment by refractionpcsx2** [comment]
Ok thanks, updated again.

**Comment by FlatOutPS2** [comment]
Just stumbled on another game with this issue: Ford Racing 2

This game actually has several graphical issue in hardware mode.
One I hadn't seen before was the shadows in hardware mode aren't black, but instead reflect the sky. :S

**Comment by refractionpcsx2** [comment]
> One I hadn't seen before was the car shadows in hardware mode aren't black, but instead reflect the sky. :D

How weird! :P 

Added to the list :)

**Comment by Kurdischerjapaner1** [comment]
gregory38 can you please fix  dance summit 2001. a few seconds can i play it after that its stop and the music continue  i try it with direct x9 and 11

**Comment by refractionpcsx2** [comment]
> gregory38 can you please fix dance summit 2001. a few seconds can i play it after that its stop and the music continue i try it with direct x9 and 11

This isn't a fix request thread and that sounds completely unrelated. If you have an issue, make a new issue with that information. But I would suggest first opening a support thread on the forum and seeing if anybody can help you.

**Comment by Kurdischerjapaner1** [comment]
i have this issue _spu_rev_offsetaddr 1f9021
### addr = 1034255  size = 28640

**Comment by refractionpcsx2** [comment]
Did you not listen to what I just said?

**Comment by Kurdischerjapaner1** [comment]
i ask everybody no one can help me

**Comment by refractionpcsx2** [comment]
you obviously haven't asked everybody because I haven't seen a thread on the forum about this. which is a majority of the PCSX2 communiy.

**Comment by Kurdischerjapaner1** [comment]
do you test dance summit 2001(SLPM 62029) by your self ?

**Comment by refractionpcsx2** [comment]
Stop asking in this Issue, jeez, post on the forums at http://forums.pcsx2.net
I'll be deleting all your posts from here in the next 10-20 minutes.

**Comment by prafullpcsx2** [comment]
x-men origins - wolverine added to the list.

**Comment by MrCK1** [comment]
Add Band Hero to the list - I'm making the compatibility report right now ;)

**Comment by refractionpcsx2** [comment]
added :)

**Comment by MrCK1** [comment]
Here's my [report for Band Hero](http://forums.pcsx2.net/Thread-Band-Hero-SLUS-21898-U?pid=520652#pid520652)

Seems like a can of worms :P

**Comment by 0neshotJonny** [comment]
Call of duty World at War : Final Front 

Same issue

**Comment by refractionpcsx2** [comment]
Added, thanks :)

**Comment by FlatOutPS2** [comment]
Added Matrix: Path Of Neo, post on the forum showed the game having this issue.

**Comment by refractionpcsx2** [comment]
added Rogue Trooper to the list http://forums.pcsx2.net/Thread-Probelm-in-Game-ROGUE-TROOPER?pid=523600#pid523600

**Comment by FlatOutPS2** [comment]
Added 007: Everything Or Nothing.

**Comment by AmbientMalice** [comment]
Out of curiosity, what is the root cause of half screen issues in PS2 emulation? They seem very common.

**Comment by gregory38** [comment]
There are 2 bugs but globally main issue is that GPU texture/framebuffer has a constant origin. Pixel 0,0 is always a top left corner (or bottom left corner depends on the API).

This assertion isn't true on the GS. The pixel 0,0 could be located anywhere, and here it is located in the middle of the framebuffer. The extra difficulty is framebuffer doesn't have any size, only a max size of 2048x2048. So you can't detect easily a half-screen issue.

**Comment by AmbientMalice** [comment]
@gregory38 Thanks.

**Comment by MrCK1** [comment]
I almost forgot about this - you can add Jonny Moseley Mad Trix

http://forums.pcsx2.net/Thread-Jonny-Moseley-Mad-Trix-SLUS-20229-U--28361

**Comment by gregory38** [comment]
So I implemented something for one of the half-screen bug. Now it is time for you to work :+1: 

If it works well, it would replace some CRC hack and we will enable it by default. I would need that you test those game with the following config
* Both OpenGL and Dx (I'm not sure Dx will support well without depth support)
* CRC fully disabled
* hw hack enabled + this hidden conf option `UserHacks_ColorDepthClearOverlap = 1`

You can compare with CRC set to minimal which is correct.

Here a list of games that are for sure impacted by the change
* [ ] OI_GodOfWar2
* [ ] OI_SimpsonsGame
* [ ] OI_SpidermanWoS
* [ ] OI_TyTasmanianTiger
* [ ] OI_DigimonRumbleArena2
* [ ] OI_BlackHawkDown
* [ ] OI_XmenOriginsWolverine
* [ ] OI_CallofDutyFinalFronts
Extra (seem to contains several CRC hacks so might be harder to see)
* [ ] OI_SpyroNewBeginning
* [ ] OI_SpyroEternalNight
* [ ] OI_StarWarsForceUnleashed

**Comment by FlatOutPS2** [comment]
Ty The Tasmanian Tiger works great with the hack, didn't notice any change with old CRC hack.

**Comment by refractionpcsx2** [comment]
Simpsons game also works great with the hack on DX and OGL :) .  Annoying thing on there though (very unrelated but thought I'd mention it) when upscaling, the half pixel offset stops the cell shading being outside the characters but only horizontally, the vertical is still off, not sure why.

**Comment by gregory38** [comment]
Ok. It is a good start. Maybe the game uses a different HPO on the Y axis (already have enough on my plate :p )

**Comment by refractionpcsx2** [comment]
That's fine, I was just planting the seed for possible future things to look in to, it isn't important :P

**Comment by FlatOutPS2** [comment]
@refractionpcsx2 Can you share a GS Dump of The Simpsons Game?

**Comment by refractionpcsx2** [comment]
Sure, here you go: http://www.filedropper.com/simpsons-offset

I think i had the half pixel offset on in this, hence the screenshot.

**Comment by FlatOutPS2** [comment]
In hardware mode I can only see the contents of the dump for two short flashes when I resize or open the window. Otherwise it stays completely black. :S

**Comment by refractionpcsx2** [comment]
:/  might need to do a longer dump then...

**Comment by refractionpcsx2** [comment]
@FlatOutPS2 Here's a longer dump for you: http://www.filedropper.com/simpsons-offsetlong

**Comment by FlatOutPS2** [comment]
Thanks, that dump works great. But I don't really see the issue. The cel-shading looks fine vertically with the HPO hack.

**Comment by refractionpcsx2** [comment]
Try native x3, homer has two lots of hair on  the side  of his head

**Comment by FlatOutPS2** [comment]
Yes, he seems to have one brown and one black. But it looks the same on native/SW mode, only the lines are thinner at higher than native resolution.

**Comment by AmbientMalice** [comment]
Delta Force: Black Hawk Down seems fixed by hack. Shadows flicker, but that's probably another problem.

![gsdx_20160920154905](https://cloud.githubusercontent.com/assets/10704701/18659127/e851def2-7f4b-11e6-8f8b-dcf00e9e4a05.png)

**Comment by gregory38** [comment]
@AmbientMalice does the shadow flicker if you enable the CRC ?

**Comment by AmbientMalice** [comment]
You mean CRC Hack Level? Makes no difference. Here are the shadows for reference.

![gsdx_20160920174531](https://cloud.githubusercontent.com/assets/10704701/18661651/36f413dc-7f5a-11e6-8d62-649d86f2321c.png)

**Comment by gregory38** [comment]
```
You mean CRC Hack Level? Makes no difference.
```
Perfect. First goal is to replace various CRC with a generic code that will always be enabled.

For the shadow, I suspect a color shuffling effect wrongly detected due to a sub frame/depth buffer. Low priority.

**Comment by FlatOutPS2** [comment]
It could be CRC hack for an issue that only affects certain missions though.

**Comment by gregory38** [comment]
I pushed the code for a generic function in #1579 Hopefully we could reduce a bit the huge list above :)

**Comment by gregory38** [comment]
I merged my commit to handle some half-screen bugs. The guy that generates me this huge list can test all of them :p 

Someone said Mercenaries was better. I would like a confirmation. And someone to test the 2 too.

**Comment by prafullpcsx2** [comment]
I can confirm that both mercenaries games are indeed fixed.

**Comment by FlatOutPS2** [comment]
Did the mercenaries games have the half-clear(bottom half of the screen not getting cleared properly) issue?

**Comment by gregory38** [comment]
They got an half screen issue. Previous clear function didn't help but now the code is more generic so it likely helps.

**Comment by prafullpcsx2** [comment]
xman origins wolverine is not fixed, so something else is going on there.

**Comment by suikoden123** [comment]
Can some please make a ps vita emulator.gregory ?

**Comment by suikoden123** [comment]
Can some please make a ps vita emulator.gregory ?

**Comment by suikoden123** [comment]
Can some please make a ps vita emulator.gregory ?

**Comment by prafullpcsx2** [comment]
Gun fighter 2 also fixed. :+1:

**Comment by FlatOutPS2** [comment]
Ford Racing 2, Killzone, NFS Underground 2 and WRC half-screen issues are all still there.

**Comment by refractionpcsx2** [comment]
Destruction Derby still has the half screen issue too

**Comment by refractionpcsx2** [comment]
Destruction Derby still has the half screen issue too

**Comment by FlatOutPS2** [comment]
Where does The Getaway have the issue?

**Comment by refractionpcsx2** [comment]
as soon as you go in to "new game" you get the lighting cut off half way through the screen

**Comment by FlatOutPS2** [comment]
You mean The Getaway Black Monday?

**Comment by refractionpcsx2** [comment]
Yeah, sorry, didn't realise there was more than one :P

**Comment by FlatOutPS2** [comment]
A few more still broken ones:
007: Everything Or Nothing (MI6 training)
Crash Twinsanity
FIFA games (2006 onwards)
Need For Speed Hot Pursuit 2
Tekken5 (heat effect burning temple)
Total Immersion Racing(fog in wet races)

**Comment by pepiczech77** [comment]
Some other games still affected:
Killzone
NFS Carbon (if it is half screen issue, seems a bit different)
NFS Underground
NFS Underground 2 (also shadows seem incorrect in HW mode)
TOCA Race Driver 3 (in distance when it is rain) but broken menus in HW mode are probably fixed

**Comment by FlatOutPS2** [comment]
> NFS Carbon (if it is half screen issue, seems a bit different)

Looks like a normal half-screen issue to me.

I updated the first post a little to show the games that are confirmed to still have the issue, so we don't keep checking the same games.

**Comment by gregory38** [comment]
@prafullpcsx2 could you retest X-men origins - wolverine

**Comment by prafullpcsx2** [comment]
Although God of War 2 is fixed now Xmen is still messed up. It seems to have separate half screen issues in menu as well as ingame (may be same). Here is gsdump of both. http://www.filedropper.com/xmenorigins

**Comment by prafullpcsx2** [comment]
Although God of War 2 is fixed now Xmen is still messed up. It seems to have separate half screen issues in menu as well as ingame (may be same). Here is gsdump of both. http://www.filedropper.com/xmenorigins

**Comment by pepiczech77** [comment]
Here are screenshots. I am not sure if it is related at all, but I can somehow see some horizontal plane there. (see screenshot, I highlited it on one of them)
Also the game is green in HW mode. I think it's a known issue.
Also I have no idea why the screenshots  are stretched. 
![gsdx_20160930212916](https://cloud.githubusercontent.com/assets/17233252/19005060/01024ce2-8759-11e6-937f-fea024db608f.png)
![gsdx_20160930212916 - kopie](https://cloud.githubusercontent.com/assets/17233252/19005061/0112321a-8759-11e6-8233-c189f05f1498.png)
SW mode
![gsdx_20160930213803](https://cloud.githubusercontent.com/assets/17233252/19005098/1f355344-8759-11e6-8622-fe65e7af6549.png)

**Comment by gregory38** [comment]
@prafullpcsx2 thanks you. Fix pushed.

**Comment by prafullpcsx2** [comment]
@gregory38 Good job. It works fine now :+1:

**Comment by FlatOutPS2** [comment]
MGS3 codec still has the issue.

**Comment by AmbientMalice** [comment]
@FlatOutPS2 PAL version, I assume?

**Comment by FlatOutPS2** [comment]
Yes, it only affects PAL versions as far as we know.

**Comment by FlatOutPS2** [comment]
I happened to find a demo of Gunfighter II, and tried it with the latest git and it still showed the half-screen issue. @prafullpcsx2 Can you check if it's still fixed?

**Comment by prafullpcsx2** [comment]
@FlatOutPS2 : Sorry I didn't notice your comment. I rechecked Gunfighter II today and yes it's fixed.

**Comment by refractionpcsx2** [comment]
Added Superman Returns as well, can be seen in #934 even though there's obviously other issues going on there as well

**Comment by prafullpcsx2** [comment]
Call of duty World at War : Final Front is also fixed.

**Comment by FlatOutPS2** [comment]
Judge Dredd has also been fixed.

World War Zero has been fixed partially, the initial half-screen issue was hiding another that is not fixed. :p

**Comment by MrCK1** [comment]
Can anybody confirm if #318 (Price of Persia: Warrior Within) needs to be added here? According to the issue, the bottom half of the screen has greenish tint on OGL HW

**Comment by FlatOutPS2** [comment]
As that issue is a few months old, I asked if it's still active in the other thread.

**Comment by FlatOutPS2** [comment]
Added Hardware: Online Arena. Seems to have a half-clear issue, but is not resolved.

**Comment by FlatOutPS2** [comment]
Added Splinter Cell. It has the issue when using the optical cable.

**Comment by FlatOutPS2** [comment]
I tried the Mercenaries demo and noticed it still has a half-screen issue. It only appears in the sky, so you won't notice it behind terrain or buildings. In earlier PCSX2 builds the demo also had the half-clear issue, which has been resolved.

GS Dump: (rename .pdf to .7z)
[Mercenaries half-screen.pdf](https://github.com/PCSX2/pcsx2/files/578789/Mercenaries.half-screen.pdf)

**Comment by CaffinatedRain** [comment]
Can confirm. It causes a new striped effect on the bottom half of the ground and sky. 

GS Dump, Rename .pdf to .7z.
[Mercs half-screen bug.pdf](https://github.com/PCSX2/pcsx2/files/673244/Mercs.half-screen.bug.pdf)

**Comment by MonJamp** [comment]
On the latest commit, Thrillville is still affected by this issue.

**Comment by MrCK1** [comment]
Issue in Band Hero still exists, no surprise there :P

**Comment by refractionpcsx2** [comment]
I don't think this issue has been addressed in a while so it is likely nothing will have changed. 

I'm sure gregory or whoever will post here if any progress is made

**Comment by FlatOutPS2** [comment]
> Can confirm Mercs full game is still not 100%. It causes a new striped effect on the bottom half of the ground and sky.

> On the latest commit, Thrillville is still affected by this issue.

> Issue in Band Hero still exists, no surprise there :P

Thanks, I moved them all up to confirmed to still have the issue.

**Comment by MrCK1** [comment]
Can someone please add "The Suffering: Ties That Bind" to the list? Thanks.

![gsdx_20170109214633](https://cloud.githubusercontent.com/assets/16314399/21796471/f8feb9d6-d6d6-11e6-90ca-f2691bb83bca.png)

**Comment by lightningterror** [comment]
Can someone explain what the issue was with DragonBall Z - Buidokai Tenkaichi 3 ?
I can run some tests , is it the black transition between starting and ending fights ?

**Comment by refractionpcsx2** [comment]
I don't think that's relevant to this issue.

**Comment by MrCK1** [comment]
Somebody can add Scarface The World is Yours - might also be related to #2022

http://forums.pcsx2.net/Thread-GSDX-Hardware-mode-Bug-Report-Scarface-The-World-Is-Yours-PAL?pid=566807#pid566807

**Comment by crismaster** [comment]
I have the same problem with Metal Gear Solid 2: Subsistence (PAL)

![image](https://user-images.githubusercontent.com/2672846/28807828-bb7c4ef2-7645-11e7-8584-413037b3e2a6.png)

My video settings:

![image](https://user-images.githubusercontent.com/2672846/28807850-e0b42ef6-7645-11e7-8879-f07208a5589c.png)

**Comment by gregory38** [comment]
@ssakash could you test MGS2 on your side ? Is the NTSC version ok ?

**Comment by AmbientMalice** [comment]
This is likely same issues as MGS3: Subsistence PAL.

**Comment by ssakash** [comment]
> @ssakash could you test MGS2 on your side ? Is the NTSC version ok ?

I just checked my dump and the NTSC version seems fine.

**Comment by crismaster** [comment]
Maybe that issue exist just in the PAL version 🤔

**Comment by ssakash** [comment]
> Maybe that issue exist just in the PAL version

Could you provide a [GS Dump](http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump) of your issue?

**Comment by crismaster** [comment]
This moment I can't send you a GS Dump (I'm working now hahaha). In this night I will provide you the info.

**Comment by crismaster** [comment]
Hi, it's my current video settings.

![image](https://user-images.githubusercontent.com/2672846/28857222-b0b1c652-7715-11e7-9dd6-2adde85ceb7c.png)

**GS Dump without thermal goggles:**

- https://transfer.sh/FIYUH/gsdx_20170802000812.gs.xz
- https://transfer.sh/1077LS/gsdx_20170802000812.png

**GS Dump with thermal goggles (BUG):**

- https://transfer.sh/1sljP/gsdx_20170802000832.gs.xz
- https://transfer.sh/hBLPO/gsdx_20170802000832.png

**Comment by crismaster** [comment]
Some new about this ? .. or nothing yet? 👍

**Comment by JOHN30011887** [comment]
i often come back here checking for Crash Twinsanity, these bugs are prob very hard to fix but im happy to wait, i sometimes think this might be same issue for crash the wrath of cortex as the bottom half of the water on the water levels doesnt fill the whole of the screen in some parts

**Comment by MrCK1** [comment]
I'll take another look at Call of Duty 3 later, but I don't really think it has the half-screen issue. The half-screen corruption only occurs in the HW renders in the first memory card screen; but is easily resolved by switching to the SW renderer and back. The rest of the game is fine (ignoring the remaining graphical mess of course) :P

**Comment by MrCK1** [comment]
Added Dropship United Peace Force to the list: https://forums.pcsx2.net/Thread-Core-Bug-Report-Dropship-United-Peace-Force-NTSC?pid=578436#pid578436

(for those of you who saw the report earlier, skipdraw was accidentally enabled. The game looks much better in HW now ;) )

**Comment by FlatOutPS2** [comment]
Added Silent Hill : Shattered Memories

**Comment by MrCK1** [comment]
Added Jak X (unconfirmed)

**Comment by MrCK1** [comment]
Added ShellShock - Nam '67

**Comment by raelgc** [comment]
I tested Fifa 2014 and 2005.

Fifa 2014 has the issue. 

Fifa 2005 works fine (i.e, this issue doesn't affect it).

Fifa 2006 uses a new engine, probably it affects it and forward (2006-2014).

**Comment by atomic83GitHub** [comment]
You can add "Just Cause".
![capture](https://user-images.githubusercontent.com/26351275/39430088-1d54d48c-4c8d-11e8-8785-1fc9362fca1f.PNG)

**Comment by JOHN30011887** [comment]
the water and fog has this issue in crash bandicoot the wrath of cortex so should be on this list :)
https://github.com/PCSX2/pcsx2/issues/2380

**Comment by legend800** [comment]
Sadly not fixed yet. This is the last big issue on my list so I hope it can get fixed someday. 

![2018-12-10 18_42_18-window](https://user-images.githubusercontent.com/20983844/49775060-b28d1e00-fcab-11e8-89bd-fbbef94d65ad.png)

**Comment by MrCK1** [comment]
Added Tony Hawk's American Wasteland

**Comment by Xcedf** [comment]
Crash TwinSanity fixed here with with new half-bottom fix PR

**Comment by nikita36078** [comment]
Brothers in Arms: Road to Hill 30 is fixed too.

**Comment by raelgc** [comment]
Tested Fifa 14 and issue is fixed too.

**Comment by RinMaru** [comment]
The Godfather still has this issue a diff varient of half bottom i was told

**Comment by MonJamp** [comment]
Looks like Thrillville no longer has this issue on version 20190503010305. I'll try and see which commit fixed it when I have time. Software and hardware rendering look identical now.

**Comment by lightningterror** [comment]
Posting this here so we don't forget for Superman: Shadow of Apokolips.


```
621: Valid Rect Height 448, m_r Height 591
621: Height Delta 143
```


In this case we won't be able to hit the code path because the delta is too big.
`bool half_bottom = abs(height_delta) <= 64 && !m_disable_ts_half_bottom;`

**Comment by gregory38** [comment]
Maybe we can hint 448/512 based on ntsc/pal selector ?

**Comment by Kriptto** [comment]
I know this is a historically buggy game, but I find the same issue in Scarface, using version 1.5.0-dev-3239

![print](https://user-images.githubusercontent.com/11839198/62651510-89eb2000-b92f-11e9-886a-608eda487e1c.png)

**Comment by lightningterror** [comment]
Can you upload a gsdump?

**Comment by Kriptto** [comment]
Is this usable?
![gsdx_20190807163041](https://user-images.githubusercontent.com/11839198/62652055-cf5c1d00-b930-11e9-9bbe-d66a5c51a714.png)

**Comment by Kriptto** [comment]
Sorry, the dump file is not atttaching, where can I send it?

**Comment by lightningterror** [comment]
Zip it and upload it here.

**Comment by Kriptto** [comment]
Got it! This is from a single frame, let me know if you need some time recorded.
[snaps.zip](https://github.com/PCSX2/pcsx2/files/3478603/snaps.zip)

**Comment by lightningterror** [comment]
I don't see any half screen issue on my end after the fix.
![gsdx_20190807214449](https://user-images.githubusercontent.com/18107717/62652915-aea9bc80-b95c-11e9-99f0-61313bb57c3b.png)

**Comment by Kriptto** [comment]
Made some tests on this. The fix works when the GS resets but, after I enter either the pause menu, interaction menu or the Rage Mode, it comes back. Again, reseting the GS, like opening the GS Settings, makes it go away until the effect comes through

**Comment by lightningterror** [comment]
Ah that explains it then, maybe issue is similar to Demon Stone. Either a blockdump or a long gs dump being able to capture the entire process would be better then.

**Comment by Kriptto** [comment]
[Scarface (2019-07-07 16-57-02).zip](https://github.com/PCSX2/pcsx2/files/3478669/Scarface.2019-07-07.16-57-02.zip)
Sure, here is blockdump, not a long one, but it has from fresh load with no bug, hitting pause and bug coming to life.

**Comment by atomic76** [comment]
WRC : Rally Evolved same fog issue on v1.5.0-dev-3310-g24be7785d

GSDX11 DX HW MODE
![HW](https://user-images.githubusercontent.com/56898639/68170459-3aaa9f00-ffb3-11e9-8e39-db4e35c782c2.JPG)

GSDX11 DX SW MODE
![SW](https://user-images.githubusercontent.com/56898639/68170490-531ab980-ffb3-11e9-962e-65e9501ff14f.JPG)

**Comment by lightningterror** [comment]
@atomic76 may also be a blending issue, did you test opengl with different blending levels?

**Comment by atomic76** [comment]
@lightningterror I tested opengl mode with every blending level(basic/medium/high/full/ultra).
but same here.

![OGLHW](https://user-images.githubusercontent.com/56898639/68171461-32546300-ffb7-11e9-9929-2e3a575950b6.JPG)

**Comment by lightningterror** [comment]
@atomic76  can you upload a gsdump?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by atomic76** [comment]
@lightningterror here is the gsdump. thanks.

[gsdx_20191105104227.zip](https://github.com/PCSX2/pcsx2/files/3806855/gsdx_20191105104227.zip)

**Comment by brahimakh** [comment]
> 
> 
> Is this usable?
> ![gsdx_20190807163041](https://user-images.githubusercontent.com/11839198/62652055-cf5c1d00-b930-11e9-9bbe-d66a5c51a714.png)

I have the same issues with pcsx2 1.5.0 dev 3296. Have you find or create the fix for this ? thank you in advance and sorry if I bother you

**Comment by lightningterror** [comment]
I forgot to mention but most of the Half Screen issues can be resolved with adjusting the **Half-screen Fix option** in gsdx hw advanced options & hacks. Latest dev build only.

**Comment by brahimakh** [comment]
where can I find the last dev build ? thank you for your help

**Comment by Start-Cart** [comment]
Ran into a screen bug rendering the game unplayable upon booting up stage. The PS2 game is Hasbro Family Game Night (USA)
PCSX2c 1.6.0 Stable. Windows 10. OpenGL.
Half-screen Fix option set to Forced-Enabled or auto did not resolve the issue.

![gsdx_20210118235505](https://user-images.githubusercontent.com/77656993/104990979-babbf980-59eb-11eb-97e4-f505761ec1da.png)

**Comment by tadanokojin** [comment]
Not a half-bottom screen issue as is being tracked here but a super sampling issue in the cache.
being tracked here: https://github.com/PCSX2/pcsx2/issues/2289

**Comment by coornio** [comment]
All testing done on 1.7.2112

007: From Russia With Love -- Game works/looks flawless, but explosions have some effect that causes an odd, transparent screen corruption as seen in picture (can't be fixed). No other issue noticed.

![image](https://user-images.githubusercontent.com/11655762/148680526-399aad21-ea6e-477f-8b91-33ddce309788.png)

Dropship: United Peace Force -- Still broken as always, top half of screen is fine but the bottom only works in software rendering, not affected by any hacks.

Need For Speed: Underground -- Perfect, no issues.

Need For Speed: Underground 2 -- Perfect, though color blending is whack when driving around (can't be fixed, only by reducing blending accuracy below High).

Need For Speed: Most Wanted -- Perfect, no issues.

Need For Speed: Carbon -- Perfect, though it has vertical lines on screen (needs Merge Sprite) and the pause menu has inaccurate blur blending (can't be fixed).

WRC 3: Has rendering issues on FMVs and main menu. It appears as if the interlacing is done in thick lines, and half of them are stuck in some previous frame. See picture. The game has incorrect interlace mode on automatic, works best in either Weave or Blend modes, Bob introduces the same shaking as automatic. Text is rendered offset, getting cut off. Needs Round Sprite (Half or Full) to display properly. No issues in actual gameplay, seems to work flawlessly when tested in a couple of quick races.

![image](https://user-images.githubusercontent.com/11655762/148683043-5e45545f-e893-4d4b-aa85-594d869618a7.png)

Splinter Cell: Chaos Theory -- Perfect, no issues whatsoever that I could discern, except the fact that the game freezes shortly after initiating combat..

**Comment by nf6429** [comment]
Tested on 1.7-2216.
Star Wars: The Force Unleashed - doesn't seem to have any any half screen issues, the menu's don't cut off like before either. This was with half screen fix disabled and enabled.

TOCA 3 - confirmed to still have issue.
![toca3](https://user-images.githubusercontent.com/37595436/148776830-899e285a-93ff-40e5-b3dd-d9494d47462e.png)

**Comment by nf6429** [comment]
Sorry bout that, Should've specified that I already had CRC to none. Ill edit the posts.

**Comment by coornio** [comment]
Amended my test results as well, caught a few mistakes in WRC 3, oops. 

@refractionpcsx2 - are all the games in this list actually using some CRC hack to amend half-screen issues? From the log I'm not seeing anything particular about them. I'm guessing there's no specific about region, otherwise they'd be listed right?

**Comment by refractionpcsx2** [comment]
@coornio I couldn't tell you, sorry, possibly some of them at least, maybe not all thought

**Comment by coornio** [comment]
Added Ford Racing 2 in my initial message.

**Comment by coornio** [comment]
The original Splinter Cell (SLUS 20652) appears to have a half-screen issue on the bottom half when using the night vision goggles, only apparent when one force-disables the Half-Screen Fix hack. It's not on the list here, maybe we should add it.

Also, nothing fixes it aside from that particular hack no matter what I try so there's that.

**Comment by seta-san** [comment]
i can find no problems in max payne 2. i even tried it in 1.4 and there seems to be no half screen problems.

**Comment by seta-san** [comment]
same with need for speed underground. no half screen issue

**Comment by refractionpcsx2** [comment]
Spiderwick Chronicles pause screen has a half bottom problem

![image](https://user-images.githubusercontent.com/6278726/195654687-1ea73ba8-4449-4109-bb7c-bf412bafc350.png)

**Comment by Biscuits25** [comment]
Dropship united peace force still has this issue. Not sure if its still possible to disable CRC, or at least I can't find it in graphical settings. Only on hardware though, software renderer works fine. Really wish there was a fix since you can't do higher resolution with software.

**Comment by TheTechnician27** [comment]
@gregory38 I've found that Thrillville's splitscreen works as intended. I've tested both the FPS minigames as well as the racing ones. I think this one can safely be checked off. Do you suppose it's also worth testing Off the Rails? I have both.
[Thrillville_SLUS-21413_20240106055505.zip](https://github.com/PCSX2/pcsx2/files/13849505/Thrillville_SLUS-21413_20240106055505.zip)

**Comment by refractionpcsx2** [comment]
Gregory isn't really around anymore, but I will check it off. Thanks for letting us know

**Comment by jk7gr** [comment]
it seems all Hasbro games have a similar issue where only part of the screen is rendered properly and the rest is not.
Example1: Family Game Night
![Hasbro Family Game Night_SLUS-21805_20240826201007](https://github.com/user-attachments/assets/93dc97f2-14e0-49ac-be96-f9c8e2fde083)
The areas highlighted are mostly visible but in general the left side is rendered properly and the right side not.
Example2: Monopoly
![Monopoly_SLUS-21753_20240826201738](https://github.com/user-attachments/assets/83ae088d-5162-4cd9-968b-d1226cda2956)
The left top corner seems to be rendered properly while not the rest of the screen (zooming in will make it more obvious) 
![Monopoly_SLUS-21753_20240826201738_zoomed](https://github.com/user-attachments/assets/90241b29-de50-42db-bf14-05e61a9bfe65)
Example 3: Trivial Pursuit
![Trivial Pursuit_SLES-55467_20240826202512](https://github.com/user-attachments/assets/59c7bb92-5a05-43df-8333-3edd3816548f)
Exactly as in Monopoly.
I am proficient with PCSX2 and I have spend a couple of days reading and testing all possible settings both on the stable but also on the nightly build (v2.1.109) in Windows and Linux with all different rendering options. The issue exists only when using hardware rendering (software rendering works fine). The samples are taken with Internal Resolution set to 3x Native where is most obvious.

**Comment by refractionpcsx2** [comment]
The Hasbro games download each quadrant back to the core in order to move it (or some weird move, for some weird reason) which means 3/4 of the screen will only render at native resolution, the top left corner is the only part which will render correctly

**Comment by jk7gr** [comment]
> The Hasbro games download each quadrant back to the core in order to move it (or some weird move, for some reason) which means 3/4 of the screen will only render at native resolution, the top left corner is the only part which will render correctly

I guess this means it is a known issue then. I also guess the only workaround is to use software rendering?

**Comment by Triticum0** [comment]
Still an issue on mlb show 2011

**Comment by refractionpcsx2** [comment]
MLB Show 2011 has issues with upscaling, but half screen is not one of them.

<img width="1466" height="1281" alt="Image" src="https://github.com/user-attachments/assets/e4914b5f-9da5-4355-ac2a-6c6c9a512f4a" />

**Comment by Triticum0** [comment]
@refractionpcsx2 during the first loading screen 

<img width="958" height="718" alt="Image" src="https://github.com/user-attachments/assets/731ceaa2-a66b-475d-9b4a-77360f7e5aed" />

[MLB 11 - The Show_SCKA-20142_20260131024730.gs.zip](https://github.com/user-attachments/files/24976773/MLB.11.-.The.Show_SCKA-20142_20260131024730.gs.zip)

**Comment by refractionpcsx2** [comment]
oh right, yeah, fair cop.
