### ISSUE TITLE
Meta: GSdx HW memory wrapping

### ISSUE THREAD

**Issue by gregory38** [PCSX2/pcsx2#1648]
GS memory is 4MB. Address above 4MB are wrapped back to the start. Some games relies on this behavior. Severals fixes was done to wrap block or page address for the SW renderer. But HW renderer is still broken. I'm not sure it is even doable with an HW renderer but let's keep a trace of impacted game for future reference.

Here a list of game that use this feature.
* [ ] Beyond good and evil
* [ ] Silent hill 3 (FMV)
* [ ] Thrillville (cutscene)

**Comment by refractionpcsx2** [comment]
Any ideas of symptoms that will appear to show it happening?

**Comment by gregory38** [comment]
Well depends on how much it overlaps. It could be massive flickering or miss the end of the framebuffer. Check with 1.4 SW renderer :) If it is broken and good now, it is a good hint.

**Comment by refractionpcsx2** [comment]
Not sure I have any games that do that :/ I may be of little use here.. lol it's not a common issue I don't think.

**Comment by gregory38** [comment]
Yes I think it is quite limited. SW compatibility is rather big (even on 1.4). Note, if game use such crazy features there are potentially extra texture cache issue too.

**Comment by refractionpcsx2** [comment]
There were quite a few games doing it with VIF writing to the VU's, Guitar Hero 3 (i think) being an example, where it wrapped around VU memory during the unpacks.  There were other games doing it too but I can't remember what.

**Comment by FlatOutPS2** [comment]
Wouldn't any game with this issue also have the issue in SW like SH3 had?

**Comment by gregory38** [comment]
Yes sw used to have the issue. And potentially still have some. I fixed beyond good&evil with my last commit.

On my dump (lamguage selector) hw is fine but I'm not sure that full game will be fine. On the wiki it said that game got issue (very old report), it could be related.

**Comment by AmbientMalice** [comment]
Could this be related? https://github.com/PCSX2/pcsx2/issues/1107 Game is meant to have a blurred menu background when in inventory, but it shows vertical lines instead. Same in SW and HW.

**Comment by gregory38** [comment]
I don't think that SW and HW will behave the same. However did you test latest git with openGL. It could be the feedback write.

**Comment by FlatOutPS2** [comment]
> On my dump (lamguage selector) hw is fine but I'm not sure that full game will be fine. On the wiki it said that game got issue (very old report), it could be related.

Yeah, HW is fine. Software flickered everywhere in the game before you fixed it. It's fine now. The game looks pretty good in HW (needed to unscale point line hack to see press start screen when upscaling, shadows are missing(after switching to software and back shows a static shadow did appear) and there looks to be a texture cache issue in the sky). I do remember seeing broken graphics like the wiki report described when I tried the demo version a good while ago. So I'll need to check up on that.

**Comment by gregory38** [comment]
I don't think there is any crc hack for BGE. GS dithering is implemented on the SW side not HW.

**Comment by FlatOutPS2** [comment]
I'll look up the demo issue in the full game to see what the issue exactly is. But I didn't notice any issue that seemed memory wrapping related, In SW memory wrapping flickering affected the whole game. But in HW it's fine except for unrelated issues.

**Comment by MonJamp** [comment]
For Thrillville the cutscene getting cut off may be a separate issue. The memory wrapping on the SW renderer fixes the pause menu cutting off part of the screen but the cutscenes are still the same as on the HW renderer.

**Comment by piorrro33** [comment]
Bump? Anything new on this topic?

**Comment by FlatOutPS2** [comment]
Yes, we're busy wrapping things up.

**Comment by refractionpcsx2** [comment]
Pun intended?

**Comment by FlatOutPS2** [comment]
I don't remember, my memory is acting up.

**Comment by MonJamp** [comment]
> 
> 
> For Thrillville the cutscene getting cut off may be a separate issue. The memory wrapping on the SW renderer fixes the pause menu cutting off part of the screen but the cutscenes are still the same as on the HW renderer.

I never corrected myself... Both issues are fixed by memory wrapping in Thrillville.

Also isn't memory wrapping implemented in the hardware renderers now? Should this issue be closed?

**Comment by TheTechnician27** [comment]
Say, refraction, is this still an issue? At least for Thrillville, this seems like something that's fixed. The HW mode cutscenes in Thrillville were pretty jank (basically unwatchable) in the 1.5.X days, but as best I can tell, they work flawlessly now (I think the GameDB defaults to bob interlacing to fix the "earthquake" flickering?)

Couldn't say, though, for the first two games.

**Comment by refractionpcsx2** [comment]
I think Silent Hill 3 is still an issue, though I'm not 100% sure, we *might* have fixed it.

**Comment by TheTechnician27** [comment]
Fair enough. At the very least, I can present (hopefully compelling) evidence that Thrillville's cutscenes are no longer an issue.
[Thrillville_SLUS-21413_20240106102259.zip](https://github.com/PCSX2/pcsx2/files/13850345/Thrillville_SLUS-21413_20240106102259.zip)

![Thrillville_SLUS-21413_20240106102259](https://github.com/PCSX2/pcsx2/assets/12673964/44cb7159-8a33-4ce8-962b-f94d533a8b40)

**Comment by refractionpcsx2** [comment]
Beyond Good and Evil may also still be a problem.  I guess I could look into this at some point...

**Comment by TheTechnician27** [comment]
It's worth noting that #1562, also by Gregory, designates Silent Hill 3 as having this issue fixed. Beyond Good & Evil isn't listed there, so maybe I could poll around on Discord to see if anyone has a copy (that, or the next time I'm across town, I could pick up a copy at the used games store if the price is right).

**Comment by refractionpcsx2** [comment]
There was 2 parts to the memory wrapping, the hardware issue is related but different
