### ISSUE TITLE
Test Drive: Missing GUI elements in HW renderers

### ISSUE THREAD

**Issue by MrCK1** [PCSX2/pcsx2#1739]
***PCSX2 version:***
PCSX2 1.5.0-dev-1756

***PCSX2 options:***
Defaults

***Plugins used:***
OGL HW (affects all HW renderers)

***Description of the issue:***
The GUI text in-game is invisible when using any hardware renderer. The only workaround is to switch to SW renderer.

***How to reproduce the issue:***
Boot the game, enter a race and pause the game.
OR
Select "Single Race," "Linear" and notice the culling issues on the top and bottom of the car selection screen

***Last known version to work:***
Never

***PC specifications:***
i5-6600k@4.7Ghz, NVIDIA GTX 1070 8GB, Windows 10 64-bit

**Pause menu in HW:**
![gsdx_20170102203533](https://cloud.githubusercontent.com/assets/16314399/21628369/e088b9b8-d1ec-11e6-8e2b-17b4def196d8.png)

GSDump: 
[testdrive_menu.zip](https://github.com/PCSX2/pcsx2/files/5938136/testdrive_menu.zip) (rename to .xz)

**Comment by FlatOutPS2** [comment]
I believe this was fixed at some point. Not sure if it required a setting change or a certain build.

**Comment by MrCK1** [comment]
I thought it got fixed too, but setting changes didn't fix this issue.

I added another issue that I found above where borders used to hide the 3D culling aren't displayed properly in the HW renderer.

**Comment by MrCK1** [comment]
The missing borders are gone thanks to #1747. Missing GUI still remains in HW renderer as well as texture glitch in minimap where dots become lines.

**Comment by MrCK1** [comment]
Quick update on this - preload data frame hack allows the missing text to appear in HW renderer, but it's all corrupted junk.

**Comment by DisorderIy** [comment]
Hardware:
![gsdx_20170316165540](https://cloud.githubusercontent.com/assets/8225831/24008476/acf0f2f4-0a69-11e7-939f-e9d6c68e8ed7.png)
Software:
![gsdx_20170316165542](https://cloud.githubusercontent.com/assets/8225831/24008473/ab151028-0a69-11e7-8c5b-7af1bea4cc05.png)

This might be related to how in SB: ROTFD, the "camera locked" icon in the bottom right doesn't appear in the HW renderers.

**Comment by FlatOutPS2** [comment]
Not all missing things in Hardware mode are related(technically possible, but you can't tell just by looking). :P If you want it to be looked into you'll be better off making a new issue for it.

**Comment by prafullpcsx2** [comment]
https://github.com/pcsx2/pcsx2/issues/971

These issues are almost same.

**Comment by MrCK1** [comment]
I would agree that the issues seem very similar. IIRC, the menu had briefly worked in HW mode when a long string of work was being done on RT stuff. 

Another separate issue, but I could've sworn that the distant blue lines seen above native resolution were a regression as well, but I'm not sure. Off the top of my head (can't access my PC right now) the game is also doing some color and channel shuffling; so additional work on that in the future may resolve the remaining issues with the minimap, ect.

**Comment by MrCK1** [comment]
Just pasting this here before I forget. Down below is the log where the menu is drawn as well as the junk input texture from the same frame/drawcall.

```
10581	API's debug messages	Info	Defined	65197	Channel shuffle effect detected SKIP
10581	API's debug messages	Info	Defined	65197	TC: Lookup Target(Color) 2048x2048, miss (0x3000, C_16)
10581	API's debug messages	Medium	Defined	57005	Preloading the RT DATA
10581	API's debug messages	Medium	Defined	57005	ERROR: Update RenderTarget 0x3000 bw:8 (0,0 => 512,512)
```
![junktexture](https://cloud.githubusercontent.com/assets/16314399/25859839/b7bc1132-34ad-11e7-9d47-904c5e295b45.png)

**Comment by MrCK1** [comment]
I meant to post this a while ago, but it seems that the alpha channel (Drawcall 979 in the dump) of the input texture used for the GUI (with Preload Data Frame) is total junk. The problem is that the texture is located at FBP 0x0, which might be a problem? 

For better or worse, the newer debug log makes no mention of channel shuffle or anything so it must've been a misdetected effect.

Raw dump w/ log: https://drive.google.com/open?id=1kvozyumtq-lfhxNklDIHL2I8vykSHDkA

**Comment by refractionpcsx2** [comment]
Didn't really look in to this hard, but interestingly using Preload Frame gives it... something..

![image](https://user-images.githubusercontent.com/6278726/167474731-8452736e-1d43-4f54-8dbb-edbfdf2573a3.png)

**Comment by stenzek** [comment]
Seems to be the usual dosage of cheeky "stashing texture data in the upper 8 bits of the framebuffer".

#8826 fixes the GS dump at least.
