### ISSUE TITLE
Lilypad Regression: Controllers do not work on some games

### ISSUE THREAD

**Issue by lightningterror** [PCSX2/pcsx2#1904]
Last working version: pcsx2-v1.5.0-dev-1934-ga3efc77
Regression version: pcsx2-v1.5.0-dev-1939-gf3a89f5

Some games don't read controller inputs , pcsx2 reads the inputs fine fine but pressing the buttons in game does nothing.

Affected games: The Getaway Black Monday , Tekken 5
There could be more but these are the only ones that showed these results for me.
Some others showed some weird results as well but those sometimes work and sometimes not.

All default settings used without speedhacks , cheats ...etc
i3 4160, amd r7-360, 16gbram, windows 7 64 bit

**Comment by turtleli** [comment]
pgert reported on #1831 that the Network Access Disc didn't respond either.

Two guesses (try separately at first, then combined if neither work):
 * Try changing https://github.com/PCSX2/pcsx2/blob/master/plugins/LilyPad/LilyPad.cpp#L1367 to:
```
if (pad->mode == MODE_DIGITAL || pad->mode == MODE_PS1_MOUSE || pad->mode == MODE_NEGCON) {
```
* Try changing https://github.com/PCSX2/pcsx2/blob/master/plugins/LilyPad/LilyPad.cpp#L1333 to:
```
 if (pad->mode != MODE_ANALOG) {
```

**Comment by FlatOutPS2** [comment]
Disable "Use analog mode if possible".

**Comment by lightningterror** [comment]
@turtleli no result , still doesn't work.
@FlatOutPS2 that doesn't work either.

**Comment by FlatOutPS2** [comment]
> that doesn't work either.

Restart the game.

**Comment by lightningterror** [comment]
> Restart the game.
Ops I forgot to do that xD
It works now.

**Comment by FlatOutPS2** [comment]
The function is not enabled by default(and it is a regression, though the option only worked with PS1 emulators before). Native PS2 behaviour doesn't always enable analog controls if it's supported or even recommended.

**Comment by pgert** [comment]
The Projects Zero (Fatal Frame) games are also more or less unresponsive to DS2 input since the last commit-batch. Why not just revert?

**Comment by turtleli** [comment]
So do the issues only exist when "Use Analog mode is possible" is enabled, or are there other regressions?

**Comment by lightningterror** [comment]
For the games I have disabling ""Use Analog mode is possible" fixes the issues.
Probably more than half of my games library are affected.

There are no other regressions.

**Comment by pgert** [comment]
"Use Analog mode is possible" is disabled with my settings,
 but greyed out (I don't actually know how to enable it if wanted).

**Comment by turtleli** [comment]
Guess I'll need to use trial and error to figure out which specific change isn't working. I can't just revert it because we'll learn nothing from it.

Try https://ci.appveyor.com/api/buildjobs/j8w0238ciaxbv5q9/artifacts/pcsx2-v1.5.0-dev-2124-gb336dd597-580-vs2015-Win32-AppVeyor.7z , which consists of the following change:
```
diff --git a/plugins/LilyPad/LilyPad.cpp b/plugins/LilyPad/LilyPad.cpp
index 1d997c7a3..cdf58b11e 100644
--- a/plugins/LilyPad/LilyPad.cpp
+++ b/plugins/LilyPad/LilyPad.cpp
@@ -1330,7 +1330,7 @@ u8 CALLBACK PADpoll(u8 value)
                         query.response[8] = Cap((sum->sticks[1].vert + 255) / 2);  // Left stick: up & down
 
                         query.numBytes = 9;
-                        if (pad->mode != MODE_ANALOG && !pad->config) {
+                        if (pad->mode != MODE_ANALOG) {
                             // Good idea?  No clue.
                             //query.response[3] &= pad->mask[0];
                             //query.response[4] &= pad->mask[1];
```

**Comment by pgert** [comment]
No difference with the Project Zero games or with Network Access Disc, using gb336dd597.

**Comment by turtleli** [comment]
Try https://ci.appveyor.com/api/buildjobs/56s4et0wppaouk04/artifacts/pcsx2-v1.5.0-dev-2125-g44409980d-581-vs2015-Win32-AppVeyor.7z, which has the following additional change:
```
diff --git a/plugins/LilyPad/LilyPad.cpp b/plugins/LilyPad/LilyPad.cpp
index cdf58b11e..306784d1d 100644
--- a/plugins/LilyPad/LilyPad.cpp
+++ b/plugins/LilyPad/LilyPad.cpp
@@ -1364,7 +1364,7 @@ u8 CALLBACK PADpoll(u8 value)
             // QUERY_DS2_ANALOG_MODE
             case 0x41:
                 // Right?  Wrong?  No clue.
-                if (pad->mode == MODE_PS1_MOUSE || pad->mode == MODE_NEGCON) {
+                if (pad->mode == MODE_DIGITAL || pad->mode == MODE_PS1_MOUSE || pad->mode == MODE_NEGCON) {
                     queryMaskMode[1] = queryMaskMode[2] = queryMaskMode[3] = 0;
                     queryMaskMode[6] = 0x00;
                 } else {
```

**Comment by pgert** [comment]
Test results for g44409980d:
No difference with PZ1, PZ3, or Network Access Disc.
With PZ2, no controller is detected.

**Comment by turtleli** [comment]
Try https://ci.appveyor.com/api/buildjobs/s7u48qnwlfyhhxsk/artifacts/pcsx2-v1.5.0-dev-2124-gd61058cd5-582-vs2015-Win32-AppVeyor.7z
Only change compared to master is:
```
diff --git a/plugins/LilyPad/LilyPad.cpp b/plugins/LilyPad/LilyPad.cpp
index 1d997c7a3..a724b0ed7 100644
--- a/plugins/LilyPad/LilyPad.cpp
+++ b/plugins/LilyPad/LilyPad.cpp
@@ -1242,7 +1242,7 @@ u8 CALLBACK PADpoll(u8 value)
             // CONFIG_MODE
             case 0x43:
                 if (pad->config && padtype != neGconPad) {
-                    if (pad->mode == MODE_DIGITAL && padtype == Dualshock2Pad && config.padConfigs[query.port][query.slot].autoAnalog) {
+                    if (pad->mode == MODE_DIGITAL && padtype == Dualshock2Pad && config.padConfigs[query.port][query.slot].autoAnalog && !ps2e) {
                         pad->mode = MODE_ANALOG;
                     }
                     // In config mode.  Might not actually be leaving it.
@@ -1465,7 +1465,7 @@ u8 CALLBACK PADpoll(u8 value)
                         pad->modeLock = 3;
                     } else {
                         pad->modeLock = 0;
-                        if (pad->mode == MODE_DIGITAL && padtype == Dualshock2Pad && config.padConfigs[query.port][query.slot].autoAnalog) {
+                        if (pad->mode == MODE_DIGITAL && padtype == Dualshock2Pad && config.padConfigs[query.port][query.slot].autoAnalog && !ps2e) {
                             pad->mode = MODE_ANALOG;
                         }
                     }
```

**Comment by pgert** [comment]
Test results for gd61058cd5:
Network Access Disc & the Project Zero games works normally.

**Comment by turtleli** [comment]
Are you sure you don't have "Use Analog mode if possible" enabled (it's a per pad setting)? That build simply disables that feature when LilyPad is opened by PCSX2.

Anyway, I might just disable the feature.

**Comment by pgert** [comment]
Oups.
I thought that the "Use analog mode if possible" setting was general,
 but it turned out that each PAD has its own setting.
By disabling the feature, the Network Access Disc & the Project Zero games works normally,
 even with regular builds. Sorry.

Still, it shouldn't be like that.
Suggestion: Invert the value from the setting,
 or rename it to "Don't use analog mode if possible".

**Comment by turtleli** [comment]
> Suggestion: Invert the value from the setting,

It's off by default. Inverting the value won't be great for most users, who'll suddenly find some of their games not working anymore.

So the only options are to leave it alone or disable the feature when LilyPad is run by PCSX2.

**Comment by FlatOutPS2** [comment]
I already fixed this in local branch last year shortly after this issue was created. I'm still waiting for a response to issue #1965 (if someone can make a blockdump of Kung Fu Panda, please share), before I can release it though.

**Comment by lightningterror** [comment]
I thought the Kung Fu Panda issue was fixed ? Well anyway I can take a look at it tomorrow.

**Comment by FlatOutPS2** [comment]
> I thought the Kung Fu Panda issue was fixed ? Well anyway I can take a look at it tomorrow.

It wasn't fixed properly. It regressed the analog/pressure sensitivity behaviour in some other games.

**Comment by FlatOutPS2** [comment]
@atomic83GitHub @lightningterror Can either of you upload a blockdump of KungFu Panda(see #1965)?

I need it before I can push the fix for this issue.

**Comment by lightningterror** [comment]
https://drive.google.com/open?id=1mHKxumYWiLbBqcmlZN8LfznCu73MewvK

**Comment by atomic83GitHub** [comment]
Here is the blockdump you request:
https://drive.google.com/file/d/1xrX-AyeAyQpZ-dn7SzF11B1SKb-_kVHR/view?usp=sharing

**Comment by refractionpcsx2** [comment]
@FlatOutPS2 can you push this fix? You've had blockdumps for 2 months :P
