### ISSUE TITLE
Onepad: Gamepad controls both players

### ISSUE THREAD

**Issue by orbea** [PCSX2/pcsx2#2039]
***PCSX2 version:***
`pcsx2-2017.07.27_66a87ce4d_master-x86_64-1_git`

***Plugins used:***
`OnePAD 20170729201046 2.0.0`

***Description of the issue:***
When using the `OnePAD 2.0.0` plugin with multiplayer games (i.e. `Guilty Gear X2`) with only one gamepad connected it will try to use the same gamepad for both players. For example if I press start in the arcade character selection it will choose characters for both players 1 and 2, during the match if I press left on the d-pad both characters will then move left. Interestingly enough it does not affect the left analog stick (Right is unused in the game).

Additionally in the `OnePAD 2.0.0` plugin settings when I try to select `Gamepad 1` and then `Gamepad Configuration` it will print `No gamepad detected.`

This is my first time trying `OnePAD 2.0.0` instead of the legacy `OnePAD 1.3.0` plugin which does not have this issue and I configured it with antimicro as explained in issue https://github.com/PCSX2/pcsx2/issues/2010. Potentially this is something I did wrong with my configuration?

`$HOME/.config/PCSX2/inis/OnePAD2.ini`
```
first_time_wizard = 0
log = 0
options = 0
mouse_sensibility = 500
ff_intensity = 32767
uid[0] = 0
uid[1] = 0
PAD 0:KEYSYM 0x3b = 1
PAD 0:KEYSYM 0x61 = 0
PAD 0:KEYSYM 0x64 = 14
PAD 0:KEYSYM 0x65 = 12
PAD 0:KEYSYM 0x66 = 13
PAD 0:KEYSYM 0x69 = 4
PAD 0:KEYSYM 0x6a = 7
PAD 0:KEYSYM 0x6b = 6
PAD 0:KEYSYM 0x6c = 5
PAD 0:KEYSYM 0x6e = 11
PAD 0:KEYSYM 0x70 = 3
PAD 0:KEYSYM 0x73 = 15
PAD 0:KEYSYM 0x76 = 8
PAD 0:KEYSYM 0x77 = 2
SDL2 = 030000000d0f00006700000001010000,HORIPAD ONE,Joystick,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,guide:b8,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,
```

***How to reproduce the issue:***
1. Configure and select the `OnePAD 2.0.0` plugin.
2. Start a multiplayer game like `Guilty Gear X2`
3. Press start in the arcade character selection to select characters for both players 1 & 2.
4. Press various buttons during the match to control both characters at once.

***Last known version to work:***
When using the legacy `OnePAD 1.3.0` plugin.

***PC specifications:***
OS: `Slackware64-current`
gamepad: `Horipad One`

**Comment by gregory38** [comment]
I can confirm you that I didn't think about multi-player game with a single gamepad. I should add some code to allow a no-gamepad available configuration.

Otherwise could you show me the complete of the bad detection. Is the controller working (if only this one is plugged)

**Comment by orbea** [comment]
Sorry, I don't really follow your question? The controller seems to work with the new OnePAD 2.0.0 plugin, granted I only tested it a little bit so far.

**Comment by gregory38** [comment]
I mean this part: `No gamepad detected.` My understanding was that even with ini config, gamepad was still wrongly detected.

**Comment by orbea** [comment]
I'm not very familiar with the ini config. That message appeared when using the GUI.

**Comment by gregory38** [comment]
ok. I think it is because you try to configure the 2nd player but with only a single pad.

**Comment by orbea** [comment]
Yes, I assume that was the case. I checked because I had a similar issue like this in the past with RetroArch, but that time it was because I somehow configured two players to the same gamepad. This time it does not appear I did that. :)

**Comment by gregory38** [comment]
I pushed a branch. Could you test it ?
https://github.com/PCSX2/pcsx2/tree/greg/onepad-2039

**Comment by orbea** [comment]
I tested your branch and I can confirm that it solves the initial problem.

However I then tested the game with two gamepads plugged in and I was only able to use one in game, the 2nd gamepad remained unresponsive, but my alternate gamepad is a standard ps3 gamepad which I suspect has issues in the linux kernel (`4.12.5`) and I'm not sure if my test provided useful data... For example if I try to use it with RetroArch is disables all input until its unplugged and it only works with certain usb slots.

**Comment by orbea** [comment]
I tested the previous build which had this issue and its still present even when both gamepads are connected where I'm still unable to use the 2nd gamepad.

**Comment by gregory38** [comment]
Hum did you try to set the 2nd gamepad in the gamepad configuration sub panel?

**Comment by orbea** [comment]
Yes, that was the problem. I failed to actually set the 2nd gamepad in the gamepad configuration, my bad.

Now I can use both gamepads, but this shows a new issue... 

The analog sticks do not work for the 2nd gamepad and it does not matter what controller. If I set the horipad as player 1 and the ps3 gamepad as player 2, the ps3 gamepad has non-functional analog sticks while the horipad works. The same is true if I set the ps3 gamepad as player 1 and the horipad as player 2, the horipad will have non-functional analog sticks while the ps3 gamepad works...

**Comment by gregory38** [comment]
Hum, I will change the code so 2nd player use the 2nd gamepad by default.

So if you plug only a single controller, analog sticks are working. Is it correct ?

**Comment by orbea** [comment]
Yes, the analog sticks work with a single controller. They also work with player 1 regardless of which controller that is. They just don't work for player 2.

**Comment by XenonPK** [comment]
Using two PS3 controllers connected via bluetooth under linux causes the first controller to control both players at the same time, that said, when I toggle rumble, both controllers respond as expected.

**Comment by orbea** [comment]
That sounds expected. gregory38's branch which has not been merged yet fixes the first issue and you probably set a 2nd gamepad working around it when you toggled rumble.

**Comment by gregory38** [comment]
I updated my branch to handle a nice default for 2nd player. Now remain the issue of analog sticks.

**Comment by gregory38** [comment]
@orbea could you retest analog stick on my brach. It seems to work on my side (tested left stick on bomberman kart). Delete ini files and try to setup both gamepad controller.

**Comment by orbea** [comment]
I tested the changes in your branch, it defaults the 2nd player to the 2nd gamepad correctly now. However as discussed in irc the analog stick issue is still present.

**Comment by orbea** [comment]
The analog issue was my own pebkac, I overlooked that the analog sticks can be enabled or disabled in the game options. They work now when they are enabled.

Seems like this issue is solved and should be closed when the changed are pushed to master?

**Comment by escalade** [comment]
@gregory38 

> Hum, I will change the code so 2nd player use the 2nd gamepad by default

```
I have two DS4v1 controllers, and while one works the other one doesn't work. Here's the output of sdl2-jstest:

Joystick Name:     'Wireless Controller'
Joystick GUID:     050000004c050000c405000000810000
Joystick Number:    0
Number of Axes:     6
Number of Buttons: 13
Number of Hats:     1
Number of Balls:    0
GameController:
  Name:    'PS4 Controller'
  Mapping: '050000004c050000c405000000810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,'

Joystick Name:     'Wireless Controller Motion Sensors'
Joystick GUID:     050000004c050000c405000000810000
Joystick Number:    1
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameController:
  Name:    'PS4 Controller'
  Mapping: '050000004c050000c405000000810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,'

Joystick Name:     'Wireless Controller'
Joystick GUID:     050000004c050000c405000000810000
Joystick Number:    2
Number of Axes:     6
Number of Buttons: 13
Number of Hats:     1
Number of Balls:    0
GameController:
  Name:    'PS4 Controller'
  Mapping: '050000004c050000c405000000810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,'

Joystick Name:     'Wireless Controller Motion Sensors'
Joystick GUID:     050000004c050000c405000000810000
Joystick Number:    3
Number of Axes:     6
Number of Buttons:  0
Number of Hats:     0
Number of Balls:    0
GameController:
  Name:    'PS4 Controller'
  Mapping: '050000004c050000c405000000810000,PS4 Controller,a:b0,b:b1,back:b8,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b11,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b12,righttrigger:a5,rightx:a3,righty:a4,start:b9,x:b3,y:b2,'
```

I suppose it's because the "Wireless Controller Motion Sensors" gets their own joystick, so /dev/js1 is a motion controller and not the second joystick like PCSX2 expects. I tried specifying through the GUI with "game controller config" but it doesn't seem to have any effect.
