### ISSUE TITLE
Switch from DX to OpenGL cause a screen freeze in Windows 10 fall creators update

### ISSUE THREAD

**Issue by atomic83GitHub** [PCSX2/pcsx2#2117]
***PCSX2 version:***
Last 1.5 dev

***PCSX2 options:***
All default, speedhack makes no differences

***Plugins used:***
GSDX , all default

***Description of the issue:***
Switch from the DX render to the OpenGL render once the emulator is running cause a screen freeze issue.

***How to reproduce the issue:***
Load PCSX2, run the BIOS or a game and switch from DX to OpenGL under GSDX.

***Last known version to work:***
Windows 10 creators update

***PC specifications:***
AMD fx8350  Gainward GTX 780Ti  Windows 10 64 Bit

**Comment by MrCK1** [comment]
Not sure what you're doing, because I've never had this issue.

**Comment by lightningterror** [comment]
It could be a W10 update. @atomic83GitHub can you go through the updates and remove the latest Cumulative Update ?

**Comment by atomic83GitHub** [comment]
Yes, the issue was introduced for me in the Fall creators update.

**Comment by lightningterror** [comment]
Guess it's just the creators update.

**Comment by atomic83GitHub** [comment]
No, the creators update was fine, the Fall creators update (the folowing major Windows 10 update) introduce it for me.

**Comment by MrCK1** [comment]
I'm sure that's what he meant. MS's naming schemes are confusing for everybody. ;)

**Comment by vsub** [comment]
Hmm,in my case is the other way arround.
Switching from OGL to DX makes the screen to freeze.
PCSX2 is not actually freezing,just nothing is rendered like with None for renderer

https://forums.pcsx2.net/Thread-Switching-to-Dx-from-OGL-stop-rendering-anything

OGL=>DX=>Freeze
DX=>OGL=>Ok
DX=>OGL=>DX=>Freeze

**Comment by MrCK1** [comment]
Wow this is weird, here's my results:

OGL->DX->Fine, (side note: Geforce Experience Overlay also pops up recognizing the window properly)

DX->OGL->Renderer window freezes

**Comment by MrCK1** [comment]
Nobbs said he'll do a test later. 

Intel could be affected too (I won't bother testing that), but so far it seems like signs are pointing to the MS as the main culprit. I don't understand how this continues to get through into their stable branches - must be since they fired they're entire QA team for Windows Insiders 🙄

**Comment by mirh** [comment]
Does changing aspect ratio (fit to Window/Screen, 4:3, 16:9) change anything?

**Comment by MrCK1** [comment]
I'll have to check later. IIRC, the entire program has to be restarted - shutting down the VM won't clear the frozen GS window.

**Comment by vsub** [comment]
No change,it keeps freezing and once it freeze,no matter what I try(I tried few other things),dx will not work until I restart pcsx2

Startiing another instance of pcsx2 while the other one has the problem(dx selected after ogl)will work fine(untill I do one of the switching types)

Even changing the plugin(with some older version)does nothing
And also,even tho nothing is moving,the GS usage is till the same as when it works(tested with ZOE2 at native because I know this game is a monster)

**Comment by mirh** [comment]
K. 
Can we pinpoint whether even amd or intel are affected, or if instead it's only an nvidia issue?

**Comment by vsub** [comment]
I am on Win10 6700HQ,GTX1060/IGPU HD 530
And when I really make pcsx2 to only use my intel card from the nvidia control panel,then it works fine but changing adapters from gsdx does nothing(I have an indicator and a taskbar icon that tells me if the nvidia card is used or not and the console keeps saying that I'm using the same card

Also,when I remove the fps  limit during the dx freeze,there is barely any nvidia gpu usage but I'm getting over 1000fps

It's probably nvidia related...again

**Comment by atomic83GitHub** [comment]
***Dear Windows 10 users***
The issue has been resolved in a Windows update (KB4048955), you can now download it.
"Addressed issue that causes a black screen to appear when you switch between windowed and full-screen modes when playing some Microsoft DirectX games."
After testing, it solve the folowing issue.
I will stay the topic's status open: waiting for feedbacks :).

**Comment by MrCK1** [comment]
I'll test later

**Comment by vsub** [comment]
No change here too after updating windows(I really hate that thing....it took so long to install it on a ssd and then after the restart,it was still not done for 30 minutes more...good luck wanting to check something on your pc when you are in a hurry)

**Comment by MrCK1** [comment]
@mirh Can you retest as well? I'm having no issues on Nvidia as of present. For the record, I haven't updated my drivers recently or anything.

**Comment by mirh** [comment]
? 
I, for one, am on W7 (+amd) and never had the issue.

**Comment by MrCK1** [comment]
Sorry, it's easy to mix you guys up ;)

**Comment by vsub** [comment]
No change....it's still freezing the same way
Windows is waiting for me to restart the laptop to install the latest update which is KB4054517
I have the 388.31 nvidia drivers installed(the latest is 388.59)
And I also tried the latest pcsx2 beta

**Comment by MrCK1** [comment]
I'm running Insider Builds, but I believe they pushed the fix to everybody.

**Comment by lightningterror** [comment]
Is this still an issue ?

**Comment by MrCK1** [comment]
Not for me, but I'm on RS4 now and am using Nvidia Gameready Drivers.

**Comment by mirh** [comment]
Actual driver version instead of some marketing game wouldn't be despised.

**Comment by MrCK1** [comment]
Sorry, I'm not at my PC. It's the latest driver anyways - 391.01

**Comment by lightningterror** [comment]
I don't think the driver was at fault since it happened on both amd and nvidia. It could be just a recent MS update that fixed the issue.

**Comment by turtleli** [comment]
Still an issue.

**Comment by mirh** [comment]
Supposedly amd was fixed by the windows update mentioned above, and intel never had this to begin with. 
So I'd think this to be nvidia-related.

**Comment by vsub** [comment]
Still no change but there is something weird going on
Laptop with Intel 530 HD and nVidia 1060

Right click on the exe and choose to use the Intel card:

1.Choosing "Default Hardware Device" from GSdx,it will use the intel card in OGL\DX mode as expected
2.Choosing "Reference Device" will allow me to choose between DX9 and OGL but DX9 will work in a weird way and OGL will work fine
3.Choosing the Intel card will work in any mode without problems
4.Choosing the nVidia card,pcsx2 will use it only in DX11 mode
5.Choosing the "Microsoft Basic Render Driver" will use the Intel card in any mode but it will be around 170fps slower(DX11 only)

Right click on the exe and choose to use the nVidia card:

1.Choosing "Default Hardware Device" from GSdx,it will use the nVidia card in all modes but switching from DX=>OGL=>DX will result in the problem
2.Choosing "Reference Device" will allow me to choose between DX9 and OGL but DX9 will work in a weird way and OGL will work fine
3.Choosing the Intel card will make the Intel card to used only in DX11 mode but switching between OGL and DX11 will result the the same freezing problem
4.Choosing the nVidia card,pcsx2 will use the nvidia card in any mode
5.Choosing the "Microsoft Basic Render Driver" will use the nVidia card in DX9 and OGL but in DX11,it will use the Intel card but it will be around 170fps slower(DX11 only)

**Comment by turtleli** [comment]
I'm no longer affected by this issue. GTX970, 397.31.

Side note: The Adapter combobox in GSdx doesn't affect OpenGL. It might only affect DX11 (not 100% sure).

**Comment by gregory38** [comment]
OpenGL doesn't allow to select the GPU (or at least not in a standard way). We did some hack for optimus and co.

**Comment by mirh** [comment]
Afaik [this line](https://github.com/PCSX2/pcsx2/blob/master/pcsx2/windows/Optimus.cpp#L23) is the only thing affecting optimus. 
(though if device selection is D3D only, I guess like it should be hidden/removed in opengl then)

Anyway, back in topic.. Would it be possible to find out whether it was something in windows, the driver or whatever?

**Comment by turtleli** [comment]
@vsub Does this issue still affect you?

**Comment by vsub** [comment]
Yes,no change and I even have a newer drivers version installed 397.64(not the latest 398.82) but probably not the latest windows updates

**Comment by MrCK1** [comment]
I swear I haven't noticed this still... I'll have to check when I get home in a few days.

**Comment by vsub** [comment]
Just now after I(windows without asking)update my video drivers to 399.01(from 397.64)the problem seems to be fixed,it dosn't freeze anymore no matter from what to what I switch

**Comment by mirh** [comment]
Thanks the almighty god. 
It may still be a problem on the legacy 390 branch though.

**Comment by lightningterror** [comment]
I'll close this since the issue has been resolved by windows/driver updates.

> It may still be a problem on the legacy 390 branch though.

Maybe but then again there are older legacy drivers so that's also an option.

**Comment by mirh** [comment]
Well, *yes*, but understanding what are these versions in the first place would be already more "telling".
