### ISSUE TITLE
.hack//INFECTION: Minor Font-Rendering and Texture Glitch

### ISSUE THREAD

**Issue by Petrichoral** [PCSX2/pcsx2#2136]
***PCSX2 version:***
v1.5.0-dev-2218-g3b122a1ba
Known to happen on PSCX2 v1.4.0 and previous versions.

***PCSX2 options:***
No explicit options required to run. Preset used is Safest,

***Plugins used:***
Default plugins were used. Used GSdx AVX2 plugin. GSdx used the OpenGL renderer. Problem occurs when using native resolution with no HW hacks. GS dump provided [here].(https://www.mediafire.com/file/5k148747nomc7ly/dothack_text_bug.gs.xz)

Images:
![dothack_text_bug](https://user-images.githubusercontent.com/18050205/32925116-dc0f7292-cb05-11e7-8d12-6b4cb98d1811.png)
![image](https://user-images.githubusercontent.com/18050205/32925135-fb3da51c-cb05-11e7-9b93-d1afe26eb4e9.png)

***Description of the issue:***
Menu text and menu textures are misaligned and not scaled correctly. A bug that triggers OSD so hard the game is unplayable due to the frequency of sighting the bug.

***How to reproduce the issue:***
Skip the demo cut-scene.
Start a new game.
Skip the beginning cut-scene.
Skip the dialog.
Enter a user name and character name.
Proceed.
Skip the dialog.
Select "The World"
Select "Login"
Wait for the loading screen.
Skip the dialog until Orca tells you to press Triangle.
Observe the error!

***Last known version to work:***
Unknown if there was a version to fix this. Searching images finds that this bug has persisted across many versions.

***PC specifications:***
Processor: Intel i7 7700k @ 4.20 GHZ, 4 Cores, 8 Logical Processors
GPU: NVIDA GEFORCE GTX 960 
RAM: 16GB

**Comment by MrCK1** [comment]
Images aren't exactly accurate when it comes to finding bugs. Could you try 1.2.1 and 1.0.0 on your system to see if the bug is present?

**Comment by Petrichoral** [comment]
@MrCK1 Sure. I dropped a GS dump in the OP as well.
For clarification, it's the title bar of the menu.

**Comment by Petrichoral** [comment]
@MrCK1 Problem persists in 1.2.1.
![image](https://user-images.githubusercontent.com/18050205/32925815-8ad4277a-cb09-11e7-9892-13957792ee07.png)

**Comment by MrCK1** [comment]
Make sure your texture filtering is set to Bilinear (PS2)

It looked OK to me, I'm not sure I understand what the bug is? Can you explain for me what you're concerned about?

**Comment by Petrichoral** [comment]
![dothack_text_bug](https://user-images.githubusercontent.com/18050205/32926074-c9c2ff82-cb0a-11e7-990c-506097bbef80.png)
This is why I said minor, but fixing the font rendering might be exactly what the doctor ordered for this game.

**Comment by MrCK1** [comment]
So the font looks fine for you now correct? It's just that menu alignment issue?

**Comment by Petrichoral** [comment]
No. Forgive me if I am being specific, but the original graphic is continuous and the font width is scaled. I have a screen grab of actual PS2 behavior.

![capture](https://user-images.githubusercontent.com/18050205/32927100-5fa5559a-cb10-11e7-976f-191438cff4b8.PNG)

**Comment by bositman** [comment]
Can you try setting OpenGL hardware renderer and Blending Unit Accuracy to Full? This looks very much like the text issue Rogue Galaxy has and is fixed with that setting

**Comment by Petrichoral** [comment]
@bositman With blending unit accuracy full it does not fix the graphical glitch. (It's actually my go-to setting for my computer).

**Comment by FlatOutPS2** [comment]
Issue persits with all GSdx renderers including the software renderer(going back at least as far as PCSX2 v0.9.1), ZeroGS and Play.

**Comment by Mrlinkwii** [comment]
is this still an issue on latest master ?

**Comment by SamJulson** [comment]
Hi! Long time no reply.
I will pull the latest master and test tomorrow.

**Comment by SamJulson** [comment]
Hi, I didn't pull the latest master, but as of nightly version 1.7.3337 this still happens across all GSdx renderers.
(DX11, DX12, GL, Vulkan, Software)

**Comment by Mrlinkwii** [comment]
[issue_2136.zip](https://github.com/PCSX2/pcsx2/files/10048053/issue_2136.zip)
copy of GS dump in-case  mediafile link dies

**Comment by MrCK1** [comment]
Still exists as of v2.1.17

**Comment by Tellilum** [comment]
As of 2.7.133 (nightly) this is still an issue
