### ISSUE TITLE
Crash Tag Team Racing Freezing after climbing the ladder first level or by loading new area.

### ISSUE THREAD

**Issue by Kristijan1001** [PCSX2/pcsx2#2366]
PCSX2 version:

v1.5.0-dev-2338-g0e39caaad

Plugins used:
OpenGL Hardware, Issue wasn't present before (it was only short freezes), now it is.

Description of the issue:
Issue happens in the first level after you climb the ladder it hard freezes and have to end process it is also happening after u enter the new area on the left after the tutorial it freezes immediately when the cut-scene happens, this issue was not happening before in version PCSX2 v1.5.0-dev-2120-g07c69eb it was just short freezing:

How to reproduce the issue:
First Level after ladder. Or after tutorial loading the new area on the left.

![](https://i.imgur.com/aKKWAR0.jpg)

![](https://i.imgur.com/YzXGAOQ.jpg)

Console Log:

> Loading GS
> 	Loading PAD
> 	Loading SPU2
> MTVU speedhack is enabled, saved states may not be stable
> (UpdateVSyncRate) Mode Changed to NTSC.
> (UpdateVSyncRate) FPS Limit Changed : 59.94 fps
> (GameDB) Enabled Gamefix: ScarfaceIbitHack
> Overall 0 Widescreen hacks loaded
> (Wide Screen Cheats DB) Patches Loaded: 0
> Frame buffer size set to  640x1280 (2560x5120)
> [23:23:10.273] Auto-ejecting memcard [port:0, slot:0]
> 
---Crash.

Last known version to work:
PCSX2 v1.5.0-dev-2120-g07c69eb was working with short freezes.

PC specifications:
CPU: Intel i5 3330 2.4GHz
GPU: Nvidia GeForce 1050Ti
OS: Windows 10 64 Bit

**EDIT:**
Disabling

> (GameDB) Enabled Gamefix: ScarfaceIbitHack

**fixed it.** I don't know why the fix freezes the game maybe someone can go further into the issue ?

**EDIT: Without the FIX the game Hangs, and freezes for 10 seconds while in the lobby, The fix that was made to fix this probably , created an other issue where you hard freeze.**

Even after loading the area , closing game and enabling the fix, the game hard freezes after 2 seconds.

**Comment by Kristijan1001** [comment]
Disabling 

> (GameDB) Enabled Gamefix: ScarfaceIbitHack

 fixed it. I don't know why the fix freezes the game maybe someone can go further into the issue ? 

Because it was working perfectly fine before.

**Comment by lightningterror** [comment]
Hum so which is worse ? With or without the fix ?
The GameDB change was added in #2326

**Comment by Kristijan1001** [comment]
Obviously without the fix the game is playable but has short freezes. But with the fix it hard freezes where you have to reset whole PCSX2. Is it possible to revert it back where it just worked without freezes (i am going to test this again and see if there are 0 shor freezes in PCSX2 v1.5.0-dev-2120-g07c69eb) ?

**Comment by lightningterror** [comment]
Just to be sure test these two versions:
https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-2296-g333e0cc82&platform=windows-x86

https://buildbot.orphis.net/pcsx2/index.php?m=dl&rev=v1.5.0-dev-2298-gb3a1345bb&platform=windows-x86

**Comment by Kristijan1001** [comment]
@lightningterror i will test them right now i just tested PCSX2 v1.5.0-dev-2120-g07c69eb and it has the short freezes, will report back on those 2 in 5-10min.

**Comment by Kristijan1001** [comment]
@lightningterror 
pcsx2-v1.5.0-dev-2296-g333e0cc82-windows-x86 **Has Short Freezes**
pcsx2-v1.5.0-dev-2298-gb3a1345bb-windows-x86 **Has Hard Freezes in the Same Spots**

**Comment by lightningterror** [comment]
Main Menu >Debug > Create Blockdump
You start the game and load the level that you experience freezes at(but without gamefixes on), save the game with a savestate (f1).
The blockdump from the game should be in pcsx2installdir with a .dump filename.
The savestate you should find the correct one if you have multiple from different games (look for the matching serial)
pcsx2installdir> sstates>

Upload the two  filenames (on google drive for example)

**Comment by Kristijan1001** [comment]
@lightningterror Here you go two crash dumps and a save state, BTW the game doesn't crash as soon as you loadstate , you have to load it first then game is running fine, but as soon as you move it crashes.

[Crash Tag Team Racing.zip](https://github.com/PCSX2/pcsx2/files/1885369/Crash.Tag.Team.Racing.zip)

**Comment by Ryudo300** [comment]
The file you uploaded seems to be corrupted. Can you upload the savestate again (or possibly create a new one entirely?)

**Comment by Ryudo300** [comment]
Ok did some testing as well now.

Gamefix enabled - Tutorial level
The game as well as the entire emulator completely locked up on me after setting foot in the tutorial after about 30 seconds of playing. This happened in both OGL and Direct3D11 (Hardware).

Gamefix disabled - Tutorial level
I was able to completely clear the tutorial, as well as reach the area in the screenshot of the OP, and had no hard freezes during the entire period.

Gamefix enabled - Park area of the screenshot:
Game (and emulator again) froze up after a few moments of playing in the area. (Also froze in Direct3D11 Hardware)

**Comment by Kristijan1001** [comment]
@Ryudo300 sorry i just saw this, but looks like you found it out. Yes i had the same exact freezes, tutorial after ladder it freezes. And in the park when u load the new area. Was this fixed or postponed , since the topic got closed ? just wondering ?

**Comment by MrCK1** [comment]
Yes it was fixed in the "master" PCSX2 branch ;)

Just go to buildbot.orphis.net/pcsx2 and download the latest build from there.

**Comment by Kristijan1001** [comment]
@MrCK1 from the looks of it ,if i am not mistaken the freezes are not fixed ? but only the game fix was disabled so the game doesn't hard freezes, instead short freezes but makes it playable ?

**Comment by MrCK1** [comment]
Yeah, that's just the microprogram program cache filling up, so it has to be emptied. Still beats having the entire emulator freeze ;)
