### ISSUE TITLE
Xenosaga I (U) OpenGL/DX11 HW  black surfaces in cutscenes

### ISSUE THREAD

**Issue by lordmedo** [PCSX2/pcsx2#2737]
pcsx2-v1.5.0-dev-2714
win10 x64 
gtx950 driver 417.01
Speedhacks preset is set to "safe"; 
MTVU off
no graphic hacks enabled 

Many of the cutscenes have black surfaces scattered randomly on the environment or on characters. Gameplay isn't affected. 
Examples: 
-Shion goes near the emulator and soldier pulls her back (behind him)
-prison cell when momo was in (on the walls)
-shion talks with her brother (center of the room for a split second)

This is exclusive to the hardware mode ogl/dx11, as software mode doesn't have it.
![screenshot_1](https://user-images.githubusercontent.com/13256611/49676308-82f6cf80-fa79-11e8-8e84-445576636c58.png)

[saves (mcard+sstate)](https://www.dropbox.com/s/vrs0vgr0aseln7a/xenosaga%20saves.rar?dl=0)
(if you use memory card, go down, use elevator then use the other elevator to your left to go up and start the cutscene)

**Comment by AlessandroVetere** [comment]
Can you try a build from #2731 to see if it solves the issues?

**Comment by lightningterror** [comment]
A gs dump will be helpful as well.
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by lordmedo** [comment]
here is the gs dump [snaps.zip](https://github.com/PCSX2/pcsx2/files/2660464/snaps.zip)
as for the build from #2731, I'm not sure how to find it - it's not referenced on automated Pcsx2 builds page yet?
additionally, tested on pcsx2-0.9.8-r4600, the glitch is there, too.

**Comment by AlessandroVetere** [comment]
The dump plays black on my side, so I cannot debug further.

As for the build, please try [this link].(https://ci.appveyor.com/api/buildjobs/agkrdsvt7gtn51c7/artifacts/pcsx2-v1.5.0-dev-2743-g6beabb330-5074-vs2017-Win32-AppVeyor.7z)

**Comment by lordmedo** [comment]
build 2743:
-glitch (black stripes on sleeves when he is sitting) is now gone
-glitch (very faint stripes on sleeves, sleeves are darker then the rest of the uniform when he is standing) is unaffected 
-random black surfaces are still there

setting half pixel offset  to "normal (vertex)" (in build 2714 and 2743) fixed some black surfaces (sleeves were unaffected)

**Comment by AlessandroVetere** [comment]
Now #2731 has been merged, so could you please update the issue pointing out what remains broken? Thanks

**Comment by lordmedo** [comment]
screenshots taken with build 2748
half pixel offset set to  "normal (vertex)"
Left OGL SW 
Right OGL HW

![xeno_sleeves](https://user-images.githubusercontent.com/13256611/49843757-87482300-fdc0-11e8-878c-dcde55adc255.jpg) his sleeves 

![xeno_black_box](https://user-images.githubusercontent.com/13256611/49843777-98912f80-fdc0-11e8-81c6-607ad8c845c4.jpg) small black surface on the floor (in cutscene it's following her movement)

![xeno_black_box2](https://user-images.githubusercontent.com/13256611/49843843-d4c49000-fdc0-11e8-86c3-6943e79b8d97.jpg)
black wall on the right

![xeno_black_box3](https://user-images.githubusercontent.com/13256611/49843847-da21da80-fdc0-11e8-8f03-be2a2986a63e.jpg)
black wall behind her

**Comment by AlessandroVetere** [comment]
Can you try to test older versions to see it this issue happened there too?

**Comment by lightningterror** [comment]
Can you see if this plugin works ? Test both opengl and d3d11.

[GSdx32-AVX2.zip](https://github.com/PCSX2/pcsx2/files/2717626/GSdx32-AVX2.zip)

**Comment by lordmedo** [comment]
It gives me an error as I'm using i7-3770k cpu, so all avx2 plugins fail to load.

**Comment by lightningterror** [comment]
Ah yea, avx2 isn't supported on that cpu, anyway can you retest latest build ? You can enable the Gsdx hw hack "Disable Safe Features" to see if it helps.

**Comment by lordmedo** [comment]
build 2888
DirectX
all hacks off > 20% black surfaces.
Disable safe features on > no effect.
half pixel offset on > 0% black surfaces.
Disable safe features on + half pixel offset  on >50% black surfaces.

OpenGL
all hacks off > 100% black surfaces.
half pixel offset on >50% black surfaces.
Disable safe features on > 0% black surfaces.
Disable safe features on + half pixel offset on > 50% black surfaces.
Disable safe features on + half pixel offset texture > 0% (and shadow fixed).
Half pixel offset is needed for the main character's shadow to be displayed without the infamous lines.

Sleeves remain unaffected by any of those settings.

**Comment by lightningterror** [comment]
Sleeves should be fixed on latest dev build now.

**Comment by lordmedo** [comment]
tested with v1.5.0-dev-3391-g79db01d7e
sleeve problem is still present, both on dx11 and ogl

**Comment by lightningterror** [comment]
Odd, I can't reproduce it on latest build.
![gsdx_20200305045358](https://user-images.githubusercontent.com/18107717/75946445-72601f80-5e9d-11ea-9ef2-87af1402e0c1.png)

**Comment by lordmedo** [comment]
v1.5.0-dev-2714 (first screenshot from the top)
stripes can be seen very profoundly but they can be remedied with turning on 8bit textures, and it was fixed in the next build... so, yeah that cannot be reproduced anymore but,

v1.5.0-dev-3391-g79db01d7e (like in second screenshot from the top)
any combination of hacks still renders his sleeves randomly blackish and they have stripes from the first screenshot but way less profound 
as he takes the dish tray and turns 90 degrees by doing so, his sleeves all go blackish and stripes are moving, making them easier to spot

**Comment by JordanTheToaster** [comment]
Currently this issue is fixed in OpenGL as of Nightly 1.7.0 2301. Vulkan and DX11 have a black triangle artifact.

OpenGL
![image](https://user-images.githubusercontent.com/80843560/152252951-36064744-c14b-48ee-8c5c-e482cc7bef20.png)

Vulkan
![image](https://user-images.githubusercontent.com/80843560/152252967-27877d7c-49e3-4c5b-afae-8aef73f2ffe6.png)

**Comment by lordmedo** [comment]
pcsx2-v1.7.2318-windows-64bit-SSE4

The sleeves scene, where he is given food:
dx11/vulkan have additional black geometry. In previous versions, (like pcsx2-v1.5.0-dev-3391), that black geometry was manageable by setting half pixel offset to vertex, now that setting just moves the black geometry to a new place on the screen.

dx11/vulkan/opengl : that particular bit when he sits down from the first picture in this thread, where the sleeves are most prominent is fixed. But in the same cut scene, his sleeves still go dark a bit with less prominent stripes. (see first screenshot from 12th December 2018 for reference)

**Comment by refractionpcsx2** [comment]
This should be fixed in all renderers now.

**Comment by lordmedo** [comment]
PCSX2 Nightly - v1.7.4235 
my gpu changed from gtx960 to rtx 3070, drivers 531.29 
windows 10 pro 22h2
the infamous sleeves are still black in all hardware modes, geometry looks fine.
I've went back and re-checked  Nightly 1.7.0.2301 & v1.7.2318-windows-64bit-SSE4 and they are still present (for this card?)
[https://www.youtube.com/watch?v=Cc9I6NnFSX8](url)
on the side note, OGL render has increased in demand from 1.7.2318 by 200%, i cannot maintain 60 fps as it reaches almost 90% utilization in this cutsceneAll options on default, 6x upscale. No manual hacks.

**Comment by JordanTheToaster** [comment]
> PCSX2 Nightly - v1.7.4235

Looks fine here.

![image](https://user-images.githubusercontent.com/80843560/225794173-977e78b6-a47f-4189-9eae-23370372ed85.png)

**Comment by RedDevilus** [comment]
Try automatic renderer it should default to Vulkan for your GPU.

**Comment by lightningterror** [comment]
It will reappear with upscaling, either disable safe features hw hack or hpo.

**Comment by lordmedo** [comment]
nothing in hacks ever worked for the sleeves and now I see where is the confusion about this matter, the sleeves changed color to black stripes more than 4 times in that cutscene, and I've supplied a GS snap of only the most prominent one that was indeed fixed, thinking that they are linked, as the others that are still there are like a less pronounced version of that case. So with that in mind, here are the gs dumps of the four remaining cases
[xeno1 sleeves.zip](https://github.com/PCSX2/pcsx2/files/10997421/xeno1.sleeves.zip)
