### ISSUE TITLE
Manhunt (NTSC-U) [SLUS-20827] - Crane freeze only on right side of the crane

### ISSUE THREAD

**Issue by soultoyo** [PCSX2/pcsx2#3031]
***PCSX2 version:***
``(For example, stable build v1.4.0 (or) development builds v1.5.xxx)``
v1.5.0-dev-3203-g56b861250

***PCSX2 options:***
Safest preset.

***Plugins used:***
![image](https://user-images.githubusercontent.com/20318021/61449362-ab6a7480-a94c-11e9-931a-77be7910eb35.png)

gsdx dump - https://drive.google.com/open?id=1wf4suqqfktZckkAj3UWsl7T9N59HXiqs

***Description of the issue:***
https://youtu.be/x0tcr4aLWss

If you get into the crane on the right side, it will freeze and you have to either wait to get killed or restart the emulator. If you get into the crane on the left side or the front you'll be fine. I have included a video to demonstrate this issue.

***How to reproduce the issue:***
Please look at the video to reproduce the issue, the mission is "Fueled by Hate".

***Last known version to work:***
I'm not too sure the last version as I've been using this version to get around the lighting bug.

***PC specifications:***
CPU: Intel Core i7 4790K,
GPU: AMD Radeon RX 590
OS: Windows 10 64-bit
``(For example: CPU: Intel Core 2 Duo E4600 GPU: Gigabyte GTX 750Ti OS: Windows 10 64 Bit)``

**Comment by kozarovv** [comment]
Is timing issue, but more game bug than pcsx2 issue. Reducing wait time for m instruction exec seems to fix it. But there is a catch. I described that below, proper patch should be totally fine to use. 

**Proper patch, highly recommended to use that one.**

```
patch=1,EE,001D70F8,word,0803FFE0 // j       sub_FFF80           (jump to our hook s0 = wait time)
patch=1,EE,000FFF80,word,26737333 // addiu   $s3, 0x7333         (s3 seems to be always unused/zeroed earlier when we jump here, in worst case hook just will do nothing. That why add, not li, we can restore it later without issues.)
patch=1,EE,000FFF84,word,16700002 // bne     $s3, $s0, loc_FFF90 (if value in s0 is not 0x7333 return to original runtime)
patch=1,EE,000FFF88,word,26738CCD // addiu   $s3, -0x7333        (restore s3 to previous value, just in case.)
patch=1,EE,000FFF8C,word,2610D1CD // addiu   $s0, -0x2E33        (set s0 to 0x4500)
patch=1,EE,000FFF90,word,08075C43 // j       loc_1D710C          (jump back to original runtime)
patch=1,EE,000FFF94,word,00000000 // nop                         (just in case)

```
**There is alternative way of patching, but that can break something, as value is set in very complicated way i assumed that something else can be stored there.** 
`patch=1,EE,00548F24,word,00004500 // store 0x4500 to 0x548F24  (alternative patch, can break other stuff)`

For devs that eventually want to look into that. Value 0x7333 is set from 0x269380.
 
```
li      $v1, 0x48000
jr      $ra
sw      $v1, dw_549198 // bss
```

then at 0x1D5198 is left shifted by one, then multiplied by 0xCCCCCCCD, and _hi_ is moved to v0.
Finally right shifted by 4, and stored at 0x548F24.

```
lw      $v1, -0x4ad8(gp)=>DAT_00549198             // 0x48000
lui     v0, 0xcccc
ori     v0, v0,0xcccd                              // v0 = 0xcccccccd
sll     $v1, 1                                     // 0x90000
multu   $zero, $v0, $v1                            // 0x7333333350000
nop
nop
mfhi    $v0                                        // 0x73333
srl     $v0, 4                                     // 0x7333 finally...
sw      v0,-0x4d4c(gp)=>DAT_00548f24
```

**Comment by prafullpcsx2** [comment]
Didn't setting ee timing to - 2 or - 3 fixed this bug?

**Comment by atomic83GitHub** [comment]
It does. But lowering the cyclerate also cause hanging in cutsceens.

**Comment by ZT-1** [comment]
> Is timing issue, but more game bug than pcsx2 issue. Reducing wait time for m instruction exec seems to fix it. But there is a catch. I described that below, proper patch should be totally fine to use.
> 
> **Proper patch, highly recommended to use that one.**
> 
> ```
> patch=1,EE,001D70F8,word,0803FFE0 // j       sub_FFF80           (jump to our hook s0 = wait time)
> patch=1,EE,000FFF80,word,26737333 // addiu   $s3, 0x7333         (s3 seems to be always unused/zeroed earlier when we jump here, in worst case hook just will do nothing. That why add, not li, we can restore it later without issues.)
> patch=1,EE,000FFF84,word,16700002 // bne     $s3, $s0, loc_FFF90 (if value in s0 is not 0x7333 return to original runtime)
> patch=1,EE,000FFF88,word,26738CCD // addiu   $s3, -0x7333        (restore s3 to previous value, just in case.)
> patch=1,EE,000FFF8C,word,2610D1CD // addiu   $s0, -0x2E33        (set s0 to 0x4500)
> patch=1,EE,000FFF90,word,08075C43 // j       loc_1D710C          (jump back to original runtime)
> patch=1,EE,000FFF94,word,00000000 // nop                         (just in case)

Working for me with this patch.
![gsdx_20190724140238](https://user-images.githubusercontent.com/11493450/61817474-a316ab80-ae1c-11e9-94a3-6894d6ecbb19.png)
And since v1.5.0-dev-3211, the camera static effect sound plays correctly, thanks to the noise generator fix. The lighting issues still requires auto flush/half-pixel offset hacks.

**Comment by kidhudi** [comment]
is there someplace to download the patched emulator?

**Comment by ZT-1** [comment]
I found that every dev build after v1.7.0-dev-680-g083380297 freezes at the first cutscene of the first level. v1.7.0-dev-683-g4a90499ec was the first to introduce this. It was last working in 680. Something introduced in between 680 and 683 caused this.

**Comment by refractionpcsx2** [comment]
> I found that every dev build after v1.7.0-dev-680-g083380297 freezes at the first cutscene of the first level. v1.7.0-dev-683-g4a90499ec was the first to introduce this. It was last working in 680. Something introduced in between 680 and 683 caused this.

Does enabling the Fast CDVD speed hack resolve it?

**Comment by ZT-1** [comment]
Yes it does. Seems it requires that now.

**Comment by refractionpcsx2** [comment]
Possibly, it's a bit of an ongoing battle. I'll add it to our list #4117

**Comment by ZT-1** [comment]
> Now that the game is fine CDVD wise, I highly sugest testing the game with instantVU1 disabled, that seemed to fix that bug on my end without the game needed the patch.

This is correct with instantvu1 disabled. But for some reason the second crane later in the level locks up the game when you enter it, leave, then enter it again.

**Comment by 5d-0** [comment]
> > Now that the game is fine CDVD wise, I highly sugest testing the game with instantVU1 disabled, that seemed to fix that bug on my end without the game needed the patch.
> 
> This is correct with instantvu1 disabled. But for some reason the second crane later in the level locks up the game when you enter it, leave, then enter it again. This also happens with the patch.

Yeah, can confirm.

**Comment by gilderoylockhart01** [comment]
That's very interesting indeed, can you send me a blockdump + savestate of the area where the softlock happens with the latest dev build please?

**Comment by ZT-1** [comment]
> That's very interesting indeed, can you send me a blockdump + savestate of the area where the softlock happens with the latest dev build please?

https://mega.nz/file/ewwk1LqI#Vahu4OO-C7iNhGNbOw7W8ia_FC5puCVvTZ8lDwntBKw

**Comment by MrCK1** [comment]
Is this still an issue?

**Comment by 5d-0** [comment]
> Is this still an issue on latest master?

Yes.

**Comment by sinisterseed** [comment]
Apologies if this isn't the proper way of reporting the issue, but to avoid duplicate reports I thought I should just reply here instead.

This still seems to be an issue as of version 1.7.3069 (x64, AVX2). I started playing the game for the first time today and while everything else thus far appears to be working correctly (except for the lights, I've noticed there is a separate report for those), things took a turn for the worse once I reached the first crane in Fuelled by Hate and refuelled it.

Jumping into the crane from any side seems to just cause the controls to lock up (I'm using an Xbox One controller, if relevant). I tried spamming all its buttons but nothing works, the scene proceeds and enemies spawn and kill me as I'm completely defenseless. I'm using manual save states in PCSX2 and reloading the save (which is right before jumping in) restores my ability to play as normal, but as soon as I jump back into the crane, I can't do anything anymore.

I've tried some of the settings recommended in this issue, such as disabling instantVU1, enabling Fast CDVD, restarting the emulator and trying again after applying the settings, but nothing really seems to be working (unless whatever caused the issue translated into my save state and it's now doomed?)

I'm happy to provide more information about my configuration if necessary.

**Comment by hammerfist** [comment]
Can confirm that this is still an issue as of 1.7.4254. The patch/cheat still fixes the issue though, thankfully.

**Comment by judesaurio** [comment]
v1.7.5251

i toggle on the patch but now it doesn't do anything if I press triangle

**Comment by DarthDarklorD** [comment]
I made this work by copy pasting the "recommended" patch code to the bottom of the SLUS-20827_38DEA143.pnach file in the zipped "patches" folder in the "resources" folder in the main PCSX2 directory and then copying the modified
 SLUS-20827_38DEA143.pnach  to the "patches" folder in the main. This will make it override the incumbent "zipped" patch and keep it from getting wiped when updating

I prefixed the patch in the SLUS-20827_38DEA143.pnach file with " [Crane Fix] " so as to have it be separate/ selectable in the Game properties / patches section along with 60 fps and 16:9 patches. I also put in some other visual patches and prefixed them the same way. those visual tweaks can be found here. 
https://forums.pcsx2.net/Thread-Post-your-PCSX2-cheats-patches-here?page=410

You have to right click the game in the list and go to properties and the patches are activatable there. I'm on the 2.3.2612 Nightly build of PCSX2. It is currently April 2025.
If for whatever reason you can't open the .pnach file in your text editor just change the extension from .pnach to .txt and then back to .pnach after you make the changes.

sorry/ not sorry to state what may be obvious, but it took my layman ass an hour to figure this out and I'm trying to help the other non software engineer manhunt enthusiasts out there. Good luck, GAME ON!

**Comment by Mrlinkwii** [comment]
has anyone checked this with #12001 ?

**Comment by 5d-0** [comment]
> has anyone checked this with [#12001](https://github.com/PCSX2/pcsx2/pull/12001) ?

Did a test and no, this PR does not fix the issue unfortunately.

**Comment by Ironyash46** [comment]
okay it's a small bug , i fixed it by just letting one of the hunter's survive , dont kill all of them , just let one survive before filling in the fuel for your crane and then volaa , the console works

**Comment by Zarukyun** [comment]
This is still not working as per latest release, dated 0-8-2026. The bug stills happen when using the cranes.
