### ISSUE TITLE
Ridge Racer V intro graphics glitches [SLUS-20002]

### ISSUE THREAD

**Issue by levonnn** [PCSX2/pcsx2#3278]
pcsx2-v1.5.0-dev-3391-gbf9519433-7012-vs2019-Win32

***PCSX2 options:***
Any options.

***Plugins used:***
Default plugins.

- **Note**:
Native resolution. All renders. Software mode. In HW mode the intro isn't displayed at all.

***Description of the issue:***
Screens:
PCSX2
[https://imgur.com/6BiyMpI](url)
PS2 capture
[https://imgur.com/8EC9lOT](url)
PCSX2
[https://imgur.com/kZmEa7b](url)
PS2 capture
[https://imgur.com/diii21C](url)
PCSX2
[https://imgur.com/kCtn0wV](url)
PS2 capture
[https://imgur.com/Q6JcqOo](url)

Youtube video of PS2:
[https://www.youtube.com/watch?v=Mfs5aFGKXJ8](url)

***How to reproduce the issue:***
Launch the game in SW mode, watch intro.

***PC specifications:***
i7 2700, GTX 760, Windows 7 64 Bit

**Comment by tadanokojin** [comment]
Try:
Config -> Emulation Settings -> VUs
Set clamping mode to extra or extra + preserve sign

**Comment by levonnn** [comment]
It fixes the highlights, but not the wheel multiplying.

**Comment by levonnn** [comment]
Still, I'd like to thank you guys for impressive work. It looks and works almost flawlessly in software mode. Shadows are fixed. Only minor stuff is left.

**Comment by BroKill** [comment]
@levonnn,

here shadows are not fixed, white blink on and off.
I tried also the settings for clamping mode to extra or extra + preserve sign but white shadows under cars are always there.

Did I miss something guys?

Thanks

**Comment by prafullpcsx2** [comment]
You need to grab the build from this pr

https://github.com/PCSX2/pcsx2/pull/3263

**Comment by BroKill** [comment]
Thanks for the reply @prafullpcsx2 but I don't see no download link there...

**Comment by RedDevilus** [comment]
Checks then appveyor then artifacts or ci and choose from there

**Comment by BroKill** [comment]
In Checks I see nothing clickable, it's empty.

**Comment by RedDevilus** [comment]
Sorry it was check then appveyor then click below on one of the environments (green line under name) and then artifacts

**Comment by prafullpcsx2** [comment]
https://ci.appveyor.com/api/buildjobs/9q92r4enyqifuovp/artifacts/pcsx2-v1.5.0-dev-3390-g9711b54a8-135-vs2017-Win32-AppVeyor.7z

**Comment by BroKill** [comment]
Thank you guys, got it and it works really good, no white shadows anymore  :)

Thanks to all devs for their awesome work!!!

CHEERs

**Comment by BroKill** [comment]
I'm wondering if yo guys are able to fix HW Render option for this game because using Software Render option it looks a bit blurry.
HW Render option has a few bugs I see : corrupted textures on cars and bad intro.

Thanks in advance

CHEERs

**Comment by tadanokojin** [comment]
Intro is a hard problem, it's a shuffle effect but not the easy kind.
Textures on cars needs research from me still.

**Comment by asp0909** [comment]
I hope it is possible to fix this game in HW is the only game in the saga that can not be emulated well on PC

**Comment by BroKill** [comment]
@tadanokojin,

is there any news about HW Render with this game?

Thanks for your work and thanks ti all involved.

CHEERs

**Comment by Mich-alt** [comment]
Can someone tell me if the fix was put into 1.6.0, the thread has a 1.5 download which supposedly fixes the shadows under cars but in 1.6.0 the issue is still there. At least the cars look good in software mode and the game runs smooth overall.

**Comment by tadanokojin** [comment]
The shadows are fixed in 1.7.0 dev builds.
I'll look at the car textures today I guess.

**Comment by Mich-alt** [comment]
> The shadows are fixed in 1.7.0 dev builds.
> I'll look at the car textures today I guess.

amazing thank you

**Comment by tadanokojin** [comment]
Moving the car texture problem over to #3639 since original issue is about the intro.

**Comment by BroKill** [comment]
> The shadows are fixed in 1.7.0 dev builds.
 Which build? All 1.7.0 or a specific one?

Thanks a lot for your work.


CHEERs

**Comment by tadanokojin** [comment]
pick the most recent: https://buildbot.orphis.net/pcsx2/
let's keep this thread on topic and not support related from now on

**Comment by BroKill** [comment]
Ok, thanks again  :)

**Comment by Mich-alt** [comment]
> pick the most recent: https://buildbot.orphis.net/pcsx2/
> let's keep this thread on topic and not support related from now on

appreciate it thank you

**Comment by Mich-alt** [comment]
As always thank you for the work. Still use pcsx2 weekly.

**Comment by refractionpcsx2** [comment]
This has been resolved (at some point, probably RT in RT)

<img width="1414" height="1186" alt="Image" src="https://github.com/user-attachments/assets/64c73b27-0008-412c-ab65-06465bb67ef0" />
