### ISSUE TITLE
SmackDown Just Bring It and SmackDown vs Raw 2006 - various graphical issues

### ISSUE THREAD

**Issue by FMecha** [PCSX2/pcsx2#3636]
***PCSX2 version:***
v1.5.0-dev-3324-g9c65b73ae

***PCSX2 options:***
 Default (Safe speedhack)

***Plugins used:***
GSdx32-AVX2 1.1.0 (Direct3D 11, mostly default settings) 
(all other plugins are defaults)

***Description of the issue:***
In WWF SmackDown! Just Bring It, some lower on-screen HUD appears to be shifted way to the top - this also affects entrances that causes the entrance video to go full screen, where you can see the arena on the bottom, as well as entrance name panels. See [this video](https://www.youtube.com/watch?v=ducp_hFlgK0) for proper 4+ man match wrestler HUD position and [this video](https://www.youtube.com/watch?v=ea6jwVZzlW4) for how entrance videos and name panels should look.
![gsdx_20200828124040](https://user-images.githubusercontent.com/68824023/91527770-92463c80-e930-11ea-9aca-94cf70af1762.png)
![gsdx_20200828124049](https://user-images.githubusercontent.com/68824023/91527754-89556b00-e930-11ea-87f7-77f888800672.png)
![gsdx_20200828124131](https://user-images.githubusercontent.com/68824023/91527761-8e1a1f00-e930-11ea-8e04-936cb3697f17.png)

In WWE SmackDown! vs Raw 2006, entrance videos do not play at all in the arena. Additionally, in Hardware mode, Hollywood Hogan's entrance (which requires the screen to go grayscale) is broken with the screen going full black, with ringside guardrail occasionally visible. The shifting mentioned above with JBI also seems to affect SvR06's startup "now loading" (with WWE logo, during memory card data load). A proper example of how entrance videos appear on the stage (along with how Hollywood Hogan's entrance should look like) can be seen [here](https://www.youtube.com/watch?v=G6yc6bBAKQ4). It is also possible the entrance video issue may also affect later SvR games.

![gsdx_20200828124409](https://user-images.githubusercontent.com/68824023/91527861-c7528f00-e930-11ea-8bfb-ecd6e3deea83.png)
![gsdx_20200828124836](https://user-images.githubusercontent.com/68824023/91527837-b86bdc80-e930-11ea-8591-a0da115d66fa.png)
![gsdx_20200828124505](https://user-images.githubusercontent.com/68824023/91527841-b9047300-e930-11ea-837f-16c13b7361e3.png)
![gsdx_20200828124516](https://user-images.githubusercontent.com/68824023/91527843-bd309080-e930-11ea-8600-afc5c0206ffd.png)

Also attached is how Hollywood Hogan's entrance in software mode:
![gsdx_20200828124554](https://user-images.githubusercontent.com/68824023/91528446-f1588100-e931-11ea-8a94-d929b619cd76.png)

***How to reproduce the issue:***
JBI: Start any match, particularly any match that involves more than two wrestlers and with entrances enabled. To demonstrate the how this affects entrance videos, at least one of the chosen wrestlers should be either The Rock or Chris Jericho.

SvR06: Start any match with entrances enabled. A good example is Chris Jericho vs Hollywood Hogan - Jericho's entrance is supposed to display a full-screen video, but it results in blank screen instead, while Hogan's entrance is full black with occasional ringside guardrail. (Note that Hollywood Hogan's entrance issue only occurs on software.)

***PC specifications:***
Acer Aspire A315-55G (Intel Core i5-1021U / NVIDIA GeForce MX230 / 8 GB RAM / Windows 10 1903 [10.0.18362.1016] 64-bit)

**Comment by tadanokojin** [comment]
Cursory glance and I would guess it's a PCRTC issue.

Can you upload some gsdumps?
https://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump

**Comment by FMecha** [comment]
It's probably going to be an hard task/time uploading the GS dumps with my potato-ass connection, unfortunately, as the GS dumps I produced turned out to be that big.

Anyway, I can confirm the SvR06 entrance video issue too on SvR07 - related to game soft-locking when previewing entrance videos from Create An Entrance's Easy Creation mode?
![gsdx_20200828201351](https://user-images.githubusercontent.com/68824023/91566414-d86dc100-e96d-11ea-80cd-e7dbb589d9d8.png)

**Comment by tadanokojin** [comment]
> It's probably going to be an hard task/time uploading the GS dumps with my potato-ass connection, unfortunately, as the GS dumps I produced turned out to be that big (covering all entrance sequences when this happened, as well starts of the match in JBI).

They compress pretty well with 7zip if you haven't tried that. I don't really need a GSdump of every example of the bug. Let's start with one single frame dump at a time and if I need more I'll let you know.

**Comment by FMecha** [comment]
GS dumps: https://gofile.io/d/PSnDiz

This also includes a GS dump for WWE SmackDown! Here Comes The Pain, which also suffer from not only shifting in loading screens, but also flickering in some of them (mostly tip screens after entrances).
![gsdx_20200828233807](https://user-images.githubusercontent.com/68824023/91591884-e03a5f00-e987-11ea-846b-6ea6533fd47a.png)

**Comment by FMecha** [comment]
As it turns out, WWE SmackDown! Shut Your Mouth also has a screen shifting in the moves editor in the game's CAW mode.
![gsdx_20200905230110](https://user-images.githubusercontent.com/68824023/92308994-d938cf80-efcb-11ea-8a6c-cac2e2f1f27b.png)

[GS dump for this game](https://github.com/PCSX2/pcsx2/files/5178319/SYM.GS.Dump.zip)

**Comment by refractionpcsx2** [comment]
I noticed you're running a very old version of PCSX2, can you try the latest development build just to confirm this is still an issue before we spend time looking in to this please? Thanks!

Here's a link to get the latest development builds: https://buildbot.orphis.net/pcsx2/

**Comment by FMecha** [comment]
[1.7.0 GS dumps](https://github.com/PCSX2/pcsx2/files/5215337/WWE.Games.GS.Dumps.1.7.0.zip)

Addendum: JBI seems to have shifting also in opening movie:
![gsdx_20200914060423](https://user-images.githubusercontent.com/68824023/93031258-9756fb80-f653-11ea-9d6f-1c2352ebfcc7.png)

Hollywood Hogan's SvR06 ("Superstar 2" in SvR07) entrance is still glitched on hardware, but entrance movies now play in the arena.
![gsdx_20200914061145](https://user-images.githubusercontent.com/68824023/93031281-bc4b6e80-f653-11ea-86f9-405f30679531.png)
![gsdx_20200914060949](https://user-images.githubusercontent.com/68824023/93031263-a047cd00-f653-11ea-8bb9-84cfb07ebc29.png)

**Comment by tadanokojin** [comment]
Holywood Hogan thing is a pretty big headache.

Two big problems:
1. Broken shuffle heuristic which makes a lot of bad assumptions
2. TC

**Comment by FMecha** [comment]
Online Pro Wrestling (SLPM-65586), being a based heavily on Shut Your Mouth, also inherits SYM's bug in the moves editor menu. 
[Uploading OPW GS Dump.zip…]()
![gsdx_20200921180642](https://user-images.githubusercontent.com/68824023/93760086-9155b180-fc35-11ea-8570-19b389587bf1.png)

**Comment by refractionpcsx2** [comment]
Hopefully the mentioned FMV problems are all solved with #5173

The Titantrons now work in said PR

**Comment by Rex000** [comment]
The issue still persists even in the most latest build 1.7.2746

One more thing I want to add with regards SvR 2006's Hollywood Hogan entrance glitch is that it also happens whenever a wrestler does a slow motion finisher (If you tap L1 whilst performing your finisher, you should get the slow motion effect in black and white).

**Comment by Rex000** [comment]
The issue still persists even in the most latest build 1.7.2746

One more thing I want to add with regards to SvR 2006's Hollywood Hogan entrance glitch is that the same glitch also happens whenever a wrestler does a slow motion finisher (If you tap L1 whilst performing your finisher, you should get the slow motion effect in black and white).

**Comment by Rex000** [comment]
SvR 2006's Hollywood Hogan entrance glitch still happens even in the latest build 1.7.2746.

The same glitch also happens whenever a wrestler does a slow motion finisher (If you tap L1 whilst performing your finisher, you should get the slow motion effect in black and white).

**Comment by Mewsey85** [comment]
As of 1.7.3220 the glitches above are still a problem

**Comment by waspennator** [comment]
[WWE SmackDown! Here Comes the Pain Flickering loading screen.zip](https://github.com/PCSX2/pcsx2/files/10716739/WWE.SmackDown.Here.Comes.the.Pain.Flickering.loading.screen.zip)

[WWE SmackDown! Here Comes the Pain Flickering Pause Text DX12.zip](https://github.com/PCSX2/pcsx2/files/10716763/WWE.SmackDown.Here.Comes.the.Pain.Flickering.Pause.Text.DX12.zip)


The Tip Screens for WWE SmackDown! Here Comes the Pain don't seem to flicker on software mode when I tested on the latest nightly build, but on hardware mode with all renderers, the tips screen before the match actually starts (After the entrances are done), have this black flickering box that shows up on the top left of the screen now.

Also when pausing during a match using the DX12 backend, the highlighted text on the pause menu seems to flicker in and out periodically. None of the other renderers that i've noticed seem to have this problem.

![WWE SmackDown! Here Comes the Pain_SLUS-20787_20230212100644](https://user-images.githubusercontent.com/78768499/218326696-7029eea4-a65e-45aa-a02a-d1174bdfc8b4.png)
![WWE SmackDown! Here Comes the Pain_SLUS-20787_20230212103418](https://user-images.githubusercontent.com/78768499/218327272-d4558b89-e066-4d90-b8cd-2b723696f834.png)

**Comment by refractionpcsx2** [comment]
do you know what build these problems started on?

**Comment by waspennator** [comment]
For the flickering pause screen text, I went through the builds on the site and narrowed it down to 1.7.3720 being the last version that was working correctly with it, the next downloadable build I tried, 1.7.3721 was when the regression began.

For the tips screen bug: I bisected, and it seems like on most builds up to 1.7.4022, the entire tips screen would flicker on and off, but 1.7.4023 was when only the top left of the tips screen started flickering.

**Comment by refractionpcsx2** [comment]
ok thanks :)

**Comment by waspennator** [comment]
> ok thanks :)

Retested HCTP again, seems like as of nightly 4125, the entire tips screen before the match starts is now back to flickering entirely, as opposed to the top left only flickering on 4124

Also a new regression has popped up on the DX12 backend that seems to have started around build 4137, the names on the pre-match confirmation screen don't seem to show up if your using DX12 rendering.

DX12 Renderer:
![WWE SmackDown! Here Comes the Pain_SLUS-20787_20230226221308](https://user-images.githubusercontent.com/78768499/221480167-af80f5b7-ce23-4950-8088-d2d7b16500d0.png)

DX11 Renderer:
![WWE SmackDown! Here Comes the Pain_SLUS-20787_20230226221352](https://user-images.githubusercontent.com/78768499/221480256-9ae05734-dc0c-4d4f-9cd8-e773adfac84d.png)

[WWE SmackDown! Here Comes the Pain - Missing Pre Match confirmation screen text DX12.zip](https://github.com/PCSX2/pcsx2/files/10836315/WWE.SmackDown.Here.Comes.the.Pain.-.Missing.Pre.Match.confirmation.screen.text.DX12.zip)

**Comment by waspennator** [comment]
Tested it out again on my end, the DX12 back end no longer seems to be showing the regressions anymore on the pre match confirmation screen or during the pause menu.

The flickering that seems to happen during the loading screen before the match actually starts (When you turn off entrances) doesn't seem to be flickering anymore either too.

**Comment by SSMasaAri** [comment]
I've had this issue in SvR 07, is this a known issue, with the fog freaking out?

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/fed1fb69-2489-4b9c-86ba-7899ae6bca13" />

**Comment by Rex000** [comment]
> I've had this issue in SvR 07, is this a known issue, with the fog freaking out?
> 
> <img alt="Image" width="1920" height="1080" src="https://private-user-images.githubusercontent.com/161258572/509072793-fed1fb69-2489-4b9c-86ba-7899ae6bca13.jpg?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjIyMDM0MjMsIm5iZiI6MTc2MjIwMzEyMywicGF0aCI6Ii8xNjEyNTg1NzIvNTA5MDcyNzkzLWZlZDFmYjY5LTI0ODktNGI5Yy04NmJhLTc4OTlhZTZiY2ExMy5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUxMTAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MTEwM1QyMDUyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0xZjU1YjcwOWY5OTliNzkyYWRmNTVhY2QwY2JhZDRjMjU0ZTgyMWIxMjRkODZiNDc4MDM5ZjYwNjliMTBlYTM5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.vabFlpyv2Jy9bUNzkiOOaoJCwIKil6u214q04Pllybk">

Yep, don't know why it still remains unfixed after such a long time.
