### ISSUE TITLE
GUN broken graphics

### ISSUE THREAD

**Issue by psennermann** [PCSX2/pcsx2#43]
The game GUN (SLUS_211.39;1) has broken graphics (as you can see below there are stripes on screen + missing ground textures...using some Skipdraw values (for example 12) gets rid of the stripes but the missing textures are still there:

![gsdx_20140506224258](https://cloud.githubusercontent.com/assets/6342467/2895471/5286fb10-d560-11e3-9623-a8012f1bf3e7.JPG)

Skipdraw=12

![gsdx_20140506224508](https://cloud.githubusercontent.com/assets/6342467/2895475/6be94270-d560-11e3-98cb-aa072bdce2e6.JPG)

Also see here: https://www.youtube.com/watch?v=DazA-5t6ykA

**Comment by gregory38** [comment]
Could you test the build of this thread http://forums.pcsx2.net/Thread-GSdx-2-0 ?
Note: OpenGL only

The stripes will be fixed for sure.

**Comment by psennermann** [comment]
Yes, stripes are gone, but the missing textures are still there...

**Comment by gregory38** [comment]
Did you try to enable the depth option / accurate option?

**Comment by gregory38** [comment]
Could you test the SW renderer on latest git ? A couple of bug were fixed so maybe yours.

**Comment by psennermann** [comment]
Unfortunately some ground textures are still missing even on software renderer of 1.3.1-886

**Comment by rz5** [comment]
Bug is still present in 1.3.1-1302, would a GS dump help?

**Comment by ssakash** [comment]
> Bug is still present in 1.3.1-1302, would a GS dump help?

GS dump will always be helpful. :)

**Comment by rz5** [comment]
Here's a couple of screenshots with VU clamp mode on Nearest. This game crashes the emulator frequently.

![sw_mode_vu_clamp_nearest](https://cloud.githubusercontent.com/assets/8117159/10663714/718754e8-78b5-11e5-9c44-f6f06da536ec.png)
![ogl_hw_highblend_vu_clamp_nearest](https://cloud.githubusercontent.com/assets/8117159/10663715/7188ab9a-78b5-11e5-8ee3-90e709c2de8c.png)

**Comment by gregory38** [comment]
Any info on the crash? Does it happen on SW rendering (I know gl isn't robust yet to memory allocation)

**Comment by rz5** [comment]
It's not a crash per-say, pcsx2 just hangs and doesn't respond to shutdown or exit requests. Happens regardless of HW/SW rendering, the emulogs are the same.

To replicate it: put VU round mode to "positive". Start game, skip the intro videos until the first loading screen. Loading apparently freezes in the middle and at this point the emulator does not respond normally anymore.

Below is a snippet of the emulog:
```
PlayStation 2 ======== Hard reset boot
 ROMGEN=2004-0614, IOP info (CPUID=1f, CACH_CONFIG=0, 2MB, IOP mode)
 <20040614-100914,ROMconf,PS20200EC20040614.bin:11696>
# Total accessable memory size: 32 MB (B:2:8:0) (370:2:7c30)
# TLB spad=0 kernel=1:12 default=13:30 extended=31:38
# Initialize Start.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize User Memory ...
# Initialize Scratch Pad ...
# Initialize Done.

EE DECI2 Manager version 0.06 Feb  6 2003 08:38:48
  CPUID=2e20, BoardID=0, ROMGEN=2004-0614, 32M

(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_211.39;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC
ELF (cdrom0:\SLUS_211.39;1) Game CRC = 0x4B80628D, EntryPoint = 0x002EC6E8
(SYSTEM.CNF) Detected PS2 Disc = cdrom0:\SLUS_211.39;1
(SYSTEM.CNF) Software version = 1.00
(SYSTEM.CNF) Disc region type = NTSC

IOP Realtime Kernel Ver.0.9.1
    Copyright 1999 (C) Sony Computer Entertainment Inc. 
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadelf: fname cdrom0:¥SLUS_211.39;1 secname all
loadelf version 3.30
Input ELF format filename = cdrom0:¥SLUS_211.39;1
0 00110000 003dd4dc ..............................................................
Loaded, cdrom0:¥SLUS_211.39;1
start address 0x2ec6e8
gp address 00000000
# Restart Without Memory Clear.
# Initialize GS ...
# Initialize INTC ...
# Initialize TIMER ...
# Initialize DMAC ...
# Initialize VU1 ...
# Initialize VIF1 ...
# Initialize GIF ...
# Initialize VU0 ...
# Initialize VIF0 ...
# Initialize IPU ...
# Initialize FPU ...
# Initialize Scratch Pad ...
# Restart Without Memory Clear Done.
sce_fileio: unrecognized code ff
allocated mp_frontend_region at 0x5c5d60
Setup TOP_DOWN mp_network_heap at 0x610db0
Setup mp_frontend_heap at 0x610e80
allocated mp_script_region at 0x610f50
Setup mp_script_heap at 0x6227a0
Initialising CD ...
 sceCdGetDiskType   Disk Type= PlayStation2 DVD
Get Reboot Request From EE

PlayStation 2 ======== Update rebooting..

PlayStation 2 ======== Update reboot complete
cdvdman Init

IOP Realtime Kernel Ver. 2.2
    Copyright 1999-2002 (C) Sony Computer Entertainment Inc. 
Reboot service module.(99/11/10)
cdvd driver module version 0.1.1 (C)SCEI
Load File service.(99/11/05)
Multi Threaded Fileio module.(99/11/15) 
iop heap service (99/11/03)
loadmodule: fname cdrom0:¥IOP¥SIO2MAN.IRX args 0 arg 
loadmodule: id 25, ret 0
loadmodule: fname cdrom0:¥IOP¥SIO2D.IRX args 0 arg 
loadmodule: id 26, ret 0
loadmodule: fname cdrom0:¥IOP¥DBCMAN.IRX args 0 arg 
loadmodule: id 27, ret 0
loadmodule: fname cdrom0:¥IOP¥MC2_D.IRX args 0 arg 
loadmodule: id 28, ret 2
loadmodule: fname cdrom0:¥IOP¥DS2U_D.IRX args 0 arg 
loadmodule: id 29, ret 0
loadmodule: fname cdrom0:¥IOP¥CDVDSTM.IRX args 0 arg 
loadmodule: id 30, ret 2
loadmodule: fname cdrom0:¥IOP¥LIBSD.IRX args 0 arg 
loadmodule: id 31, ret 0
loadmodule: fname cdrom0:¥IOP¥SDRDRV.IRX args 0 arg 
SDR driver version 4.0.1 (C) SCEI
 Exit rsd_main 
loadmodule: id 32, ret 2
loadmodule: fname cdrom0:¥IOP¥FILEIO.IRX args 0 arg 
FileIO driver version 0.1
loadmodule: id 33, ret 0
Starting FileIO_Init
Done FileIO_Init
loadmodule: fname cdrom0:¥IOP¥EZPCM.IRX args 0 arg 
PCM driver version 666
 Exit PCM loader thread 
loadmodule: id 34, ret 0
--- scripts¥engine¥engine_params.qb.ps2 not found in PRE
--- images/loadscrn.img.ps2 not found in PRE
--- pak/qb.pak.ps2 not found in PRE
--- pak/qb.pab.ps2 not found in PRE
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
Send of sound SifCmd failed.  Retrying...
EzADPCM: create thread ID= 11146811
Assigned core 0 and voice 23 to address 5010
Assigned core 1 and voice 23 to address 9010
Assigned core 0 and voice 22 to address d010
Assigned core 1 and voice 22 to address 11010
Assigned core 0 and voice 21 to address 15010
Assigned core 1 and voice 21 to address 19010
Assigned core 0 and voice 20 to address 1d010
Assigned Memory Stream 0 to address 21010
Assigned Memory Stream 1 to address 25010
Assigned Memory Stream 2 to address 29010
Assigned Memory Stream 3 to address 2d010
Assigned Memory Stream 4 to address 31010
Assigned Memory Stream 5 to address 35010
Assigned Memory Stream 6 to address 39010
Assigned Memory Stream 7 to address 3d010
Got init result
--- images/copyright.img.ps2 not found in PRE
--- Sounds¥pak¥Global_sfx.pak.ps2 not found in PRE
--- Sounds¥pak¥Global_iop_sfx.pak.ps2 not found in PRE
Async FUNC_IDLE on handle 64d490, result 1, cancelled 0, last func 3
Async FUNC_IDLE on handle 64d320, result 1, cancelled 0, last func 2
--- anims¥standardkeyq.bin not found in PRE
--- anims¥standardkeyt.bin not found in PRE
--- zones/global/global.pak.ps2 not found in PRE
--- zones/global/global.pab.ps2 not found in PRE
--- skies/default_sky/default_sky.pak.ps2 not found in PRE
--- skies/morning_sky/morning_sky.pak.ps2 not found in PRE
--- skies/evening_sky/evening_sky.pak.ps2 not found in PRE
--- skies/night_sky/night_sky.pak.ps2 not found in PRE
--- skies/Steamboat_sky/Steamboat_sky.pak.ps2 not found in PRE
--- player/cowboy_start/cowboy_start.pak.ps2 not found in PRE
--- player/cowboy_survivor/cowboy_survivor.pak.ps2 not found in PRE
--- player/cowboy_NewClothes/cowboy_NewClothes.pak.ps2 not found in PRE
--- player/cowboy_deputy/cowboy_deputy.pak.ps2 not found in PRE
--- player/cowboy_resistance/cowboy_resistance.pak.ps2 not found in PRE
--- player/cowboy_indian/cowboy_indian.pak.ps2 not found in PRE
--- player/cowboy_final/cowboy_final.pak.ps2 not found in PRE
--- player/cowboy_male/cowboy_male.pak.ps2 not found in PRE
--- player/ped_banker_1/ped_banker_1.pak.ps2 not found in PRE
--- weapons/rifle/winchester/winchester.pak.ps2 not found in PRE
--- weapons/rifle/ferguson/ferguson.pak.ps2 not found in PRE
--- weapons/pistol/colt/colt.pak.ps2 not found in PRE
--- weapons/pistol/schofield/schofield.pak.ps2 not found in PRE
--- weapons/pistol/volcanic/volcanic.pak.ps2 not found in PRE
--- weapons/pistol/peacemaker/peacemaker.pak.ps2 not found in PRE
--- weapons/sharpshooter/sharpshooter/sharpshooter.pak.ps2 not found in PRE
--- weapons/sharpshooter/sharpshoot02/sharpshoot02.pak.ps2 not found in PRE
--- weapons/bow/bow/bow.pak.ps2 not found in PRE
--- weapons/bow/firebow/firebow.pak.ps2 not found in PRE
--- weapons/bow/dynamitebow/dynamitebow.pak.ps2 not found in PRE
--- skies/default_sky/default_sky.pak.ps2 not found in PRE
--- player/cowboy_male/cowboy_male.pak.ps2 not found in PRE
--- images/loadscrn_generic.img.ps2 not found in PRE
--- pause¥hud¥hud.pak.ps2 not found in PRE
--- Zones/Z_Badlands/Z_Badlands.pak.PS2 not found in PRE
--- Zones/Z_Bridge/Z_Bridge.pak.PS2 not found in PRE
--- Zones/Z_CanyonE/Z_CanyonE.pak.PS2 not found in PRE
--- Zones/Z_CanyonM/Z_CanyonM.pak.PS2 not found in PRE
--- Zones/Z_Apache/Z_Apache.pak.PS2 not found in PRE
--- Zones/Z_CanyonW/Z_CanyonW.pak.PS2 not found in PRE
--- Zones/Z_CanyonTrail/Z_CanyonTrail.pak.PS2 not found in PRE
--- Zones/Z_Cutscene/Z_Cutscene.pak.PS2 not found in PRE
--- Zones/Z_CutsceneDH/Z_CutsceneDH.pak.PS2 not found in PRE
--- Zones/Z_CutsceneST/Z_CutsceneST.pak.PS2 not found in PRE
--- Zones/Z_Dodge/Z_Dodge.pak.PS2 not found in PRE
--- Zones/Z_Alhambra/Z_Alhambra.pak.PS2 not found in PRE
--- Zones/Z_DodgeSkirts/Z_DodgeSkirts.pak.PS2 not found in PRE
--- Zones/Z_FoothillN/Z_FoothillN.pak.PS2 not found in PRE
--- Zones/Z_FoothillS/Z_FoothillS.pak.PS2 not found in PRE
--- Zones/Z_Fort/Z_Fort.pak.PS2 not found in PRE
--- Zones/Z_Hide/Z_Hide.pak.PS2 not found in PRE
--- Zones/Z_HideSkirts/Z_HideSkirts.pak.PS2 not found in PRE
--- Zones/Z_Hunt/Z_Hunt.pak.PS2 not found in PRE
--- Zones/Z_Injun/Z_Injun.pak.PS2 not found in PRE
--- Zones/Z_Inskirts/Z_Inskirts.pak.PS2 not found in PRE
--- Zones/Z_LVEast/Z_LVEast.pak.PS2 not found in PRE
--- Zones/Z_Laundry/Z_Laundry.pak.PS2 not found in PRE
--- Zones/Z_Opium/Z_Opium.pak.PS2 not found in PRE
--- Zones/Z_LVWest/Z_LVWest.pak.PS2 not found in PRE
--- Zones/Z_Bank/Z_Bank.pak.PS2 not found in PRE
--- Zones/Z_Hoodoo/Z_Hoodoo.pak.PS2 not found in PRE
--- Zones/Z_HoodooTunnel/Z_HoodooTunnel.pak.PS2 not found in PRE
--- Zones/Z_Mine/Z_Mine.pak.PS2 not found in PRE
--- Zones/Z_MineTunnel/Z_MineTunnel.pak.PS2 not found in PRE
--- Zones/Z_LostCity/Z_LostCity.pak.PS2 not found in PRE
--- Zones/Z_MineSkirts/Z_MineSkirts.pak.PS2 not found in PRE
--- Zones/Z_Outskirts/Z_Outskirts.pak.PS2 not found in PRE
--- Zones/Z_PassE/Z_PassE.pak.PS2 not found in PRE
--- Zones/Z_PassW/Z_PassW.pak.PS2 not found in PRE
--- Zones/Z_PassN/Z_PassN.pak.PS2 not found in PRE
--- Zones/Z_PassS/Z_PassS.pak.PS2 not found in PRE
--- Zones/Z_Ranch/Z_Ranch.pak.PS2 not found in PRE
--- Zones/Z_RanchSkirts/Z_RanchSkirts.pak.PS2 not found in PRE
--- Zones/Z_SCTrails/Z_SCTrails.pak.PS2 not found in PRE
--- Zones/Z_SEplains/Z_SEplains.pak.PS2 not found in PRE
--- Zones/Z_Steamboat/Z_Steamboat.pak.PS2 not found in PRE
--- Zones/Z_Steamboat2/Z_Steamboat2.pak.PS2 not found in PRE
--- Zones/Z_TrainTunnelCanyonM/Z_TrainTunnelCanyonM.pak.PS2 not found in PRE
--- Zones/Z_TrainTunnelMine/Z_TrainTunnelMine.pak.PS2 not found in PRE
--- Zones/Z_TrainTunnelSEPlains/Z_TrainTunnelSEPlains.pak.PS2 not found in PRE
--- Zones/Z_Viewer/Z_Viewer.pak.PS2 not found in PRE
--- Zones/Z_Apache_LOD/Z_Apache_LOD.pak.PS2 not found in PRE
--- Zones/Z_Badlands_LOD/Z_Badlands_LOD.pak.PS2 not found in PRE
--- Zones/Z_Bridge_LOD/Z_Bridge_LOD.pak.PS2 not found in PRE
--- Zones/Z_CanyonE_LOD/Z_CanyonE_LOD.pak.PS2 not found in PRE
--- Zones/Z_CanyonM_LOD/Z_CanyonM_LOD.pak.PS2 not found in PRE
--- Zones/Z_CanyonW_LOD/Z_CanyonW_LOD.pak.PS2 not found in PRE
--- Zones/Z_CanyonTrail_LOD/Z_CanyonTrail_LOD.pak.PS2 not found in PRE
--- Zones/Z_Dodge_LOD/Z_Dodge_LOD.pak.PS2 not found in PRE
--- Zones/Z_DodgeSkirts_LOD/Z_DodgeSkirts_LOD.pak.PS2 not found in PRE
--- Zones/Z_FoothillN_LOD/Z_FoothillN_LOD.pak.PS2 not found in PRE
--- Zones/Z_FoothillS_LOD/Z_FoothillS_LOD.pak.PS2 not found in PRE
--- Zones/Z_Fort_LOD/Z_Fort_LOD.pak.PS2 not found in PRE
--- Zones/Z_Hide_LOD/Z_Hide_LOD.pak.PS2 not found in PRE
--- Zones/Z_Hoodoo_LOD/Z_Hoodoo_LOD.pak.PS2 not found in PRE
--- Zones/Z_Hunt_LOD/Z_Hunt_LOD.pak.PS2 not found in PRE
--- Zones/Z_Inskirts_LOD/Z_Inskirts_LOD.pak.PS2 not found in PRE
--- Zones/Z_Laundry_LOD/Z_Laundry_LOD.pak.PS2 not found in PRE
--- Zones/Z_LVEast_LOD/Z_LVEast_LOD.pak.PS2 not found in PRE
--- Zones/Z_LVWest_LOD/Z_LVWest_LOD.pak.PS2 not found in PRE
--- Zones/Z_Mine_LOD/Z_Mine_LOD.pak.PS2 not found in PRE
--- Zones/Z_MineSkirts_LOD/Z_MineSkirts_LOD.pak.PS2 not found in PRE
--- Zones/Z_Outskirts_LOD/Z_Outskirts_LOD.pak.PS2 not found in PRE
--- Zones/Z_PassN_LOD/Z_PassN_LOD.pak.PS2 not found in PRE
--- Zones/Z_PassS_LOD/Z_PassS_LOD.pak.PS2 not found in PRE
--- Zones/Z_Ranch_LOD/Z_Ranch_LOD.pak.PS2 not found in PRE
--- Zones/Z_RanchSkirts_LOD/Z_RanchSkirts_LOD.pak.PS2 not found in PRE
--- Zones/Z_SCTrails_LOD/Z_SCTrails_LOD.pak.PS2 not found in PRE
--- Zones/Z_SEPlains_LOD/Z_SEPlains_LOD.pak.PS2 not found in PRE
--- Missions/m_hu/m_hu.pak.ps2 not found in PRE
--- Missions/m_sb/m_sb_intro.pak.ps2 not found in PRE
--- Missions/m_sb/m_sb.pak.ps2 not found in PRE
--- Missions/m_ht/m_ht_intro.pak.ps2 not found in PRE
--- Missions/m_ht/m_ht.pak.ps2 not found in PRE
--- Missions/m_bf/m_bf_intro.pak.ps2 not found in PRE
--- Missions/m_bf/m_bf.pak.ps2 not found in PRE
--- Missions/m_bd/m_bd_intro.pak.ps2 not found in PRE
--- Missions/m_bd/m_bd.pak.ps2 not found in PRE
--- Missions/m_whore/m_whore_intro.pak.ps2 not found in PRE
--- Missions/m_whore/m_whore.pak.ps2 not found in PRE
--- Missions/m_bo/m_bo_intro.pak.ps2 not found in PRE
--- Missions/m_bo/m_bo.pak.ps2 not found in PRE
--- Missions/m_ej/m_ej_intro.pak.ps2 not found in PRE
--- Missions/m_ej/m_ej.pak.ps2 not found in PRE
--- Missions/m_st/m_st_intro.pak.ps2 not found in PRE
--- Missions/m_st/m_st.pak.ps2 not found in PRE
--- Missions/m_hide/m_hide_intro.pak.ps2 not found in PRE
--- Missions/m_hide/m_hide.pak.ps2 not found in PRE
--- Missions/m_kh/m_kh_intro.pak.ps2 not found in PRE
--- Missions/m_kh/m_kh.pak.ps2 not found in PRE
--- Missions/m_ss/m_ss_intro.pak.ps2 not found in PRE
--- Missions/m_ss/m_ss.pak.ps2 not found in PRE
--- Missions/m_ef/m_ef.pak.ps2 not found in PRE
--- Missions/m_af/m_af.pak.ps2 not found in PRE
--- Missions/m_js/m_js_intro.pak.ps2 not found in PRE
--- Missions/m_js/m_js.pak.ps2 not found in PRE
--- Missions/m_ha/m_ha_intro.pak.ps2 not found in PRE
--- Missions/m_ha/m_ha.pak.ps2 not found in PRE
--- Missions/m_ea/m_ea_intro.pak.ps2 not found in PRE
--- Missions/m_ea/m_ea.pak.ps2 not found in PRE
--- Missions/m_km/m_km_intro.pak.ps2 not found in PRE
--- Missions/m_km/m_km.pak.ps2 not found in PRE
--- Missions/m_jh/m_jh_intro.pak.ps2 not found in PRE
--- Missions/m_s_master/m_s_master.pak.ps2 not found in PRE
--- Missions/m_s_ktp/m_s_ktp.pak.ps2 not found in PRE
--- Missions/m_s_ktp2/m_s_ktp2.pak.ps2 not found in PRE
--- Missions/m_s_hunting_grizzly/m_s_hunting_grizzly.pak.ps2 not found in PRE
--- Missions/m_s_pex_starter/m_s_pex_starter.pak.ps2 not found in PRE
--- Missions/m_s_pex2/m_s_pex2.pak.ps2 not found in PRE
--- Missions/m_s_pex_stumpy/m_s_pex_stumpy.pak.ps2 not found in PRE
--- Missions/m_s_pex1/m_s_pex1.pak.ps2 not found in PRE
--- Missions/m_s_pex_cletus/m_s_pex_cletus.pak.ps2 not found in PRE
--- Missions/m_s_pex_attorney/m_s_pex_attorney.pak.ps2 not found in PRE
--- Missions/m_s_pex_jesse/m_s_pex_jesse.pak.ps2 not found in PRE
--- Missions/m_s_pex_speedy/m_s_pex_speedy.pak.ps2 not found in PRE
--- Missions/m_s_pex_shopkeep/m_s_pex_shopkeep.pak.ps2 not found in PRE
--- Missions/m_s_pex_mayor/m_s_pex_mayor.pak.ps2 not found in PRE
--- Missions/m_s_bounty1/m_s_bounty1.pak.ps2 not found in PRE
--- Missions/m_s_bounty2/m_s_bounty2.pak.ps2 not found in PRE
--- Missions/m_s_bounty3/m_s_bounty3.pak.ps2 not found in PRE
--- Missions/m_s_bounty4/m_s_bounty4.pak.ps2 not found in PRE
--- Missions/m_s_bounty5/m_s_bounty5.pak.ps2 not found in PRE
--- Missions/m_s_bounty6/m_s_bounty6.pak.ps2 not found in PRE
--- Missions/m_s_bounty7/m_s_bounty7.pak.ps2 not found in PRE
--- Missions/m_s_bounty8/m_s_bounty8.pak.ps2 not found in PRE
--- Missions/m_s_bounty9/m_s_bounty9.pak.ps2 not found in PRE
--- Missions/m_s_bounty10/m_s_bounty10.pak.ps2 not found in PRE
--- Missions/m_s_bounty11/m_s_bounty11.pak.ps2 not found in PRE
--- Missions/m_s_bounty12/m_s_bounty12.pak.ps2 not found in PRE
--- Missions/m_s_re/m_s_re.pak.ps2 not found in PRE
--- Missions/m_s_re2/m_s_re2.pak.ps2 not found in PRE
--- Missions/m_s_hc/m_s_hc.pak.ps2 not found in PRE
--- Missions/m_s_the/m_s_the.pak.ps2 not found in PRE
--- Missions/m_s_the/m_s_the.pak.ps2 not found in PRE
--- Missions/m_s_store1/m_s_store1.pak.ps2 not found in PRE
--- Missions/m_s_store2/m_s_store2.pak.ps2 not found in PRE
--- Missions/m_s_store3/m_s_store3.pak.ps2 not found in PRE
--- Missions/m_hack/m_hack.pak.ps2 not found in PRE
--- Missions/m/m_intro.pak.ps2 not found in PRE
--- Missions/m_ct/m_ct.pak.ps2 not found in PRE
--- Missions/m_test/m_test.pak.ps2 not found in PRE
--- Missions/m_cd/m_cd_intro.pak.ps2 not found in PRE
--- Missions/m_cd/m_cd.pak.ps2 not found in PRE
--- Missions/m_viewer/m_viewer.pak.ps2 not found in PRE
--- Missions/m_mainmenu/m_mainmenu.pak.ps2 not found in PRE
--- zones/
```
I'll try to make it crash with default VU settings.

**Comment by gregory38** [comment]
Does 1.2 have a similar behavior?

**Comment by gregory38** [comment]
I removed the gsdx tag because remaining issue seems to be VU related.

**Comment by rz5** [comment]
On default settings, using the SW renderer, letting the game run until the main menu it will crash. I have Visual Studio installed, so Windows will prompt me to debug it. The call stack has the following:

´´´´
>	GSdx32-AVX.dll!1004d308()	Unknown
 	[Frames below may be incorrect and/or missing, no symbols loaded for GSdx32-AVX.dll]	
 	GSdx32-AVX.dll!1004bd0a()	Unknown
 	GSdx32-AVX.dll!1006b630()	Unknown
 	GSdx32-AVX.dll!1006b568()	Unknown
 	GSdx32-AVX.dll!1007b378()	Unknown
 	GSdx32-AVX.dll!10071739()	Unknown
 	GSdx32-AVX.dll!1006b48b()	Unknown
 	GSdx32-AVX.dll!1007b0e1()	Unknown
 	GSdx32-AVX.dll!10016c11()	Unknown
 	pcsx2.exe!00d6e849()	Unknown
 	pcsx2.exe!0101dc45()	Unknown
 	pcsx2.exe!00e105e8()	Unknown
 	[External Code]	
 	pcsx2.exe!00e105e8()	Unknown
 	pcsx2.exe!00e11b02()	Unknown
 	[External Code]	

´´´´
I'll try 1.2 stable now.

**Comment by gregory38** [comment]
Without debugging symbol it is useless. We don't understand more than you the above trace ;)

**Comment by rz5** [comment]
1.2 also crashes in about the same area of the game.

**Comment by refractionpcsx2** [comment]
What about 1.0? Also what is the result if you run the game on the newest Git build with SuperVU?

**Comment by rz5** [comment]
Newest Git build, with SuperVU and clamping mode on Positive makes it hang as well, emulog is the same as what I posted above. Should be noted that these are 3 separate bugs present on the latest git build, running this game:
1) The missing ground textures bug can be fixed with default settings, VU clamping mode on Nearest;
2) The emulator freezes while loading assets if VU clamping mode is on Positive;
3) The emulator crashes on the main menu with default settings (based on the call stack, that's GSdx at fault).

What should I test with 1.0?

**Comment by refractionpcsx2** [comment]
if it works :P

**Comment by rz5** [comment]
On 1.0:
Missing ground textures can't be fixed by playing with VU round mode anymore;
Still becomes unresponsive if you start it with VU round mode set to Positive;
No longer crashes on main menu with default settings, it eventually starts playing a trailer.

**Comment by refractionpcsx2** [comment]
well thats different. Playing with the round mode will break a lot of games, so because one setting breaks it, that is not part of the problem, just so you are aware, we're only concerned if things are broken in chop/zero and if any other setting happens to improve things

**Comment by willkuer** [comment]
Well pcsx2 gui isnt supposed to freeze if you play with rounding modes, or?

**Comment by refractionpcsx2** [comment]
I think he means the game freezes up rather than the whole emulator, although that's possible too as it might be spamming millions of errors

**Comment by rz5** [comment]
If you boot up GUN while VU round mode is on positive, the game freezes. If you try to exit or shutdown, it doesn't work; try to exit or shutdown again and the whole emulator goes down. Here's last lines of the emulog when that happens, I enabled all log sources plus the dev/verbose stuff:

```
microVU1: Cached Prog = [009] [PC=0040] [List=02] (Cache=0.022%) [0.0mb]
microVU1: Cached Prog = [010] [PC=03f0] [List=01] (Cache=0.022%) [0.0mb]
microVU1: Cached Prog = [011] [PC=01c0] [List=01] (Cache=0.022%) [0.0mb]
microVU1: Cached Prog = [012] [PC=01e0] [List=01] (Cache=0.022%) [0.0mb]
microVU1: D-bit set! PC = ab8
microVU1: Branch Optimization
microVU1: D-bit set! PC = ab8
microVU1: Branch Optimization
microVU1: D-bit set! PC = ab8
microVU1: Branch Optimization
microVU1: D-bit set! PC = b10
```
At this point I try to shutdown.
```
(pxEvtQueue:CoreThreadMethod) Posting event! (pending=0, idle=0)
(pxEvtQueue:CoreThreadMethod) Executing... [Noncancelable]
```
Game is frozen but GUI is still reponsive, I try to exit.
```
(pxEvtQueue:VoidMethod) Posting event! (pending=0, idle=0)
(pxEvtQueue:VoidMethod) Posting event! (pending=1, idle=0)
```
Everything is now frozen.

**Comment by rz5** [comment]
With default settings, as soon as you get to the main menu and the little animation plays, the console starts getting spammed with:
```
Gif Unit - GS packet size exceeded VU memory size!
Gif Unit - GS packet size exceeded VU memory size!
Gif Unit - GS packet size exceeded VU memory size!
Gif Unit - GS packet size exceeded VU memory size!
Gif Unit - GS packet size exceeded VU memory size!
```

Setting VU round mode to Nearest while that's happening makes the spam stop.

**Comment by refractionpcsx2** [comment]
okay, but what I said still applies, round modes other than chop/zero are likely to make problems worse so its no indication of the problem. If negative helps, that's great, that's a bonus.

**Comment by rz5** [comment]
I built a debug build. I'm letting GUN load up to the main menu and I'm getting a couple of failed assertions that keep getting spammed:

GSSState.cpp:508 - Expression: !std::isnan(m_v.ST.S)

GSSState.cpp:509 - Expression: !std::isnan(m_v.ST.T)

**Comment by gregory38** [comment]
@refractionpcsx2 For information, rz5 tryied to run a debug build. Various assertion in GSdx were hit. Honestly it feels like VU send garbage to the GS.

**Comment by refractionpcsx2** [comment]
It's quite possible. Okay will be worth a look, we will reclassify it as a VU bug for now

**Comment by refractionpcsx2** [comment]
What I forgot to ask 6 months ago was do you get a bunch of assertions with the rounding mode set to "Nearest" as that seems to fix the graphics. 

Also I can't quite work out from the comments, does Nearest make the game crash or just positive? If it's the latter, I might just put a GameDB entry in for this.

Pinging @rz5

**Comment by rz5** [comment]
I'm reading my comments again and for this game, setting VU rounding to 'Nearest' fixes the missing textures/polys and prevents crashes, at least in the very first area of the game.

Setting VU rounding to either 'Positive' or 'Chop/Zero' breaks graphics AND will eventually make the game crash.

**Comment by refractionpcsx2** [comment]
Okay in that case, if you can provide a CRC (if the game is not in our compat list) then I'll add it to the GameDB to force the game to use Nearest rounding :)

**Comment by ssakash** [comment]
> Okay in that case, if you can provide a CRC (if the game is not in our compat list) then I'll add it to the GameDB to force the game to use Nearest rounding :)

Why do you need the game's CRC ?

**Comment by refractionpcsx2** [comment]
> Why do you need the game's CRC ?

because the patches link by the CRC of the game, not the ELF name as games can share ELF name, but sharing CRC is very unlikely.

**Comment by ssakash** [comment]
> because the patches link by the CRC of the game, not the ELF name as games can share ELF name, but sharing CRC is very unlikely.

Unless I'm seriously confused, the GameDB only applies the rounding/clamping options based on the Serial/ELF name/ Region , not the hexadecimal CRC value. I think you got it mixed up with CRC hacks on GSDX ?

Though the GameDB can still have patches specific to certain CRC's. but only patches, not core options like clamping/rounding.

**Comment by refractionpcsx2** [comment]
> Unless I'm seriously confused, the GameDB only applies the rounding/clamping options based on the Serial/ELF name/ Region , not the hexadecimal CRC value. I think you got it mixed up with CRC hacks on GSDX ?
> 
> Though the GameDB can still have patches specific to certain CRC's. but only patches, not core options like clamping/rounding.

You're right, I am slightly confused, I don't need the CRC for that, however the GameDB does have patches specific to CRC's, but they are for code patching, not changing options, which require nothing but the section in the DB which should already be there.

**Comment by refractionpcsx2** [comment]
Now live in the GameDB :)
