### ISSUE TITLE
[BUG] Fatal Frame 3 flickering floor textures

### ISSUE THREAD

**Issue by kenshen112** [PCSX2/pcsx2#4493]
**Describe the bug**
In the main hall and several other rooms of the mansion, there are several areas where the textures of the floor will flicker in and out of existence in HW mode, not SW

**To Reproduce**
Play the game in HW mode and watch it go

**Expected behavior**
Textures should stay stable and not flash

**GS Settings**
Default

**Emulation Settings**
Default

**GS Window Screenshots**
[Gifs of the issue](https://imgur.com/a/6j3minw)

**System Info (please complete the following information):**
 -   PCSX2 Revision: v1.7.0-dev-1288-gb5a917fb0
 -   OS: Windows 10 or Arch either it happens
 -   CPU: Ryzen 3700x
 -   GPU: GTX 2070

**Logs and Dumps**
https://www.dropbox.com/s/io0gvz7nm5cembm/gsdx_20210615204051.gs.xz?dl=0

**Comment by kenshen112** [comment]
Updated dump. Should work now

**Comment by kozarovv** [comment]
Dump still not work for me, but i noticed that winrar thinks that xz archive is broken (still unpacks it). Maybe try to use zip or something.

**Comment by kenshen112** [comment]
[I tested this one runs. I can only make multi-frame dumps apparently](https://www.dropbox.com/s/shcxtzdpzqrva7m/gsdx_20210616085600.gs?dl=0)

**Comment by lightningterror** [comment]
Duplicate https://github.com/PCSX2/pcsx2/issues/3692
