### ISSUE TITLE
[BUG]: 2002 FIFA World Cup All GPU render shadow bug

### ISSUE THREAD

**Issue by tee4341** [PCSX2/pcsx2#5505]
### Describe the Bug

2002 FIFA World Cup (USA) All GPU render shadow bug
![screenshot 6](https://user-images.githubusercontent.com/48321898/153087688-bd4ad406-82ac-491a-9e56-992714cbd62b.jpg)
![screenshot 9](https://user-images.githubusercontent.com/48321898/153087693-c18d9eab-9d55-47b9-9081-eacb5ad4bd58.jpg)
![screenshot 1](https://user-images.githubusercontent.com/48321898/153087804-fdc81fb9-f293-41f1-ad68-f2bf09d2a900.jpg)
![screenshot 2](https://user-images.githubusercontent.com/48321898/153087806-3ce00692-5eba-4827-bbd0-8682391c7ea5.jpg)
![screenshot 5](https://user-images.githubusercontent.com/48321898/153087808-5d6dc9cb-2180-4775-a61f-e3e8459b20ee.jpg)

### Reproduction Steps

Stop this game shadow work fine
![screenshot 3](https://user-images.githubusercontent.com/48321898/153087945-a33c7af1-667f-4e5f-bece-57876ae69310.jpg)

### Expected Behavior

Software render worke fine
![screenshot 8](https://user-images.githubusercontent.com/48321898/153088034-db237397-c0c0-4813-8029-abf827676547.jpg)
![screenshot 7](https://user-images.githubusercontent.com/48321898/153088039-c5fe87bd-be4c-46e5-b032-24efbcf30d75.jpg)

### PCSX2 Revision

1.7.2271

### Operating System

Windows 11

### CPU

i7

### GPU

gtx950m

**Comment by lightningterror** [comment]
A gsdump would be nice.

**Comment by coornio** [comment]
Also upgrade to the latest dev build. 2271 is a fair amount of changes behind 2351 so might as well make sure this isn't already obsolete.

**Comment by lightningterror** [comment]
@tee4341 Any update, also try testing with higher blending levels.

**Comment by tee4341** [comment]
> 
All shadows render work fine...

![2002 FIFA World Cup4](https://user-images.githubusercontent.com/48321898/165682487-e574b0c7-27c1-43d1-ba83-e468630f2013.jpg)
opengl + external shader .fx

![2002 FIFA World Cup3](https://user-images.githubusercontent.com/48321898/165682696-ca8a486f-05e3-422a-b192-ab828b94eef4.jpg)
Direct3d11+ external shader .fx

![2002 FIFA World Cup2](https://user-images.githubusercontent.com/48321898/165682868-d1073e5d-a234-42ed-a625-4d13c83e65c9.jpg)
Vulkan

![2002 FIFA World Cup5](https://user-images.githubusercontent.com/48321898/165682950-e82c9119-0af3-4dd1-9955-f2898e4d97cc.jpg)
Direct3d12+ external shader .fx (external shader not run) "and change render ingameplay only it can run"

![2002 FIFA World Cup6](https://user-images.githubusercontent.com/48321898/165683663-694c4a29-34af-491a-83c0-fd0a6df0f51c.jpg)
after change mode or exit to another page it error

![2002 FIFA World Cup](https://user-images.githubusercontent.com/48321898/165683815-8fef90b4-1986-4548-9b0c-d79027086a45.jpg)
Cannot be used Direct3d12 from the start of the game. will not load into play

**Comment by tee4341** [comment]
> @tee4341 Any update, also try testing with higher blending levels.

> 
All shadows render work fine...

![2002 FIFA World Cup4](https://user-images.githubusercontent.com/48321898/165682487-e574b0c7-27c1-43d1-ba83-e468630f2013.jpg)
opengl + external shader .fx

![2002 FIFA World Cup3](https://user-images.githubusercontent.com/48321898/165682696-ca8a486f-05e3-422a-b192-ab828b94eef4.jpg)
Direct3d11+ external shader .fx

![2002 FIFA World Cup2](https://user-images.githubusercontent.com/48321898/165682868-d1073e5d-a234-42ed-a625-4d13c83e65c9.jpg)
Vulkan

![2002 FIFA World Cup5](https://user-images.githubusercontent.com/48321898/165682950-e82c9119-0af3-4dd1-9955-f2898e4d97cc.jpg)
Direct3d12+ external shader .fx (external shader not run) "and change render ingameplay only it can run"

![2002 FIFA World Cup6](https://user-images.githubusercontent.com/48321898/165683663-694c4a29-34af-491a-83c0-fd0a6df0f51c.jpg)
after change mode or exit to another page it error

![2002 FIFA World Cup](https://user-images.githubusercontent.com/48321898/165683815-8fef90b4-1986-4548-9b0c-d79027086a45.jpg)
Cannot be used Direct3d12 from the start of the game. will not load into play

**Comment by lightningterror** [comment]
If they work fine then I will close it, the dx12 issue is separate.

**Comment by prafullpcsx2** [comment]
Reopening this as this bug was never fixed. Actual problem is during night matches, the four sided shadows are too dark in HW mode. Changing Blending to highest makes it even more dark. Gsdump attached.
[2002 FIFA World Cup_SLUS-20404_20230225223307.gs.zip](https://github.com/PCSX2/pcsx2/files/10831816/2002.FIFA.World.Cup_SLUS-20404_20230225223307.gs.zip)

**Comment by Mrlinkwii** [comment]
still an issue as of 1.7.5090 
![image](https://github.com/PCSX2/pcsx2/assets/17685135/4e3afca0-3bb7-4305-baea-fde21c7ff659)

**Comment by MaLDox77** [comment]
Still an issue in 1.7.5192

Pausing the game and in replays, shadows render perfectly, blended and with players shape. But during gameplay they are an unfiltered low res black cross.

**Comment by JordanTheToaster** [comment]
Shadows are fixed by #7655

**Comment by MaLDox77** [comment]
> Shadows are fixed by [#7655](https://github.com/PCSX2/pcsx2/pull/7655)

Using PCSX2 2.3.419 and the problem is not fixed. Is needed to change a related option?

**Comment by JordanTheToaster** [comment]
> Using PCSX2 2.3.419 and the problem is not fixed. Is needed to change a related option?

They will only work in software mode currently.
