### ISSUE TITLE
[BUG]: Xenosaga Episode III: Black Surfaces in Software Rendering Mode

### ISSUE THREAD

**Issue by MetrosexualGarbodor** [PCSX2/pcsx2#5644]
### Describe the Bug

There are black surfaces in some areas of the game when using software rendering. They also move when the character moves.
![imagen](https://user-images.githubusercontent.com/79612681/158086933-6d1b069d-8963-4df7-8930-62e8fb40714e.png)

### Reproduction Steps

Start a new game in software mode, skip the cutscenes and walk forward. Should be visible after going through the first door. 

### PCSX2 Revision

v1.7.2444

### Operating System

Windows 10 (64bit)

### CPU

i7-10700k

### GPU

RTX 3070

### Logs & Dumps

[gs_20220314000610_Xenosaga - Episode III - Also Sprach Zarathustra _Disc1of2_ _NTSC-U__SLUS-21389.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/8240947/gs_20220314000610_Xenosaga.-.Episode.III.-.Also.Sprach.Zarathustra._Disc1of2_._NTSC-U__SLUS-21389.gs.xz.zip)
[gs_20220314000709_Xenosaga - Episode III - Also Sprach Zarathustra _Disc1of2_ _NTSC-U__SLUS-21389.gs.xz.zip](https://github.com/PCSX2/pcsx2/files/8240948/gs_20220314000709_Xenosaga.-.Episode.III.-.Also.Sprach.Zarathustra._Disc1of2_._NTSC-U__SLUS-21389.gs.xz.zip)

**Comment by MetrosexualGarbodor** [comment]
Somewhere along the way, probably in one of the most recent software renderer changes, this was fixed. 
![imagen](https://user-images.githubusercontent.com/79612681/167508772-eca64efc-0fb6-4fcd-ab0f-4aef2eba3070.png)

**Comment by refractionpcsx2** [comment]
wow this got fixed very recently, I swear I checked this like, 2 days ago and it was still broken.
Awesome to see :)
