### ISSUE TITLE
FIFA Street 2 not rendering correctly.

### ISSUE THREAD

**Issue by Shackkill** [PCSX2/pcsx2#569]
Issue title: Graphical bug / Rendering not working well

-PCSX2 version: 1.2.1

-PCSX2 options: Defaults, plugin settings: http://gyazo.com/5d536816216460396c475f1e73248846

-Plugins used: GSd10 : http://gyazo.com/5d536816216460396c475f1e73248846

-Plugin settings: http://gyazo.com/5d536816216460396c475f1e73248846

-Description: Graphics not rendered correctly, like the terrain, the flags in the menu and the players and their clothing.

-How to replicate: Play Fifa Street 2

-Last known version to work: Never worked

-PC specifications: CPU: Intel Core i7 4770 @ 4.3Ghz GPU: Gigabyte Geforce GTX660 2 GB OS: Windows 8 64-bit

**Comment by karasuhebi** [comment]
Relevant:
http://www.reddit.com/r/PCSX2/comments/37yhiy/fifa_street_2_graphics_clothesflags_are_bugged/

**Comment by bositman** [comment]
You didn't follow the guidelines so this report is more or less useless.
https://github.com/PCSX2/pcsx2/wiki/How-to-create-useful-and-valid-issues

**Comment by bositman** [comment]
Eh just noticed you made a wiki page of it...? I meant reading that and editing this issue with those guidelines.
Anyway, did it for you

**Comment by gregory38** [comment]
Try the version from here http://forums.pcsx2.net/Thread-GSdx-2-0
With the following setup
```
accurate_fbmask = 1
```
And use normal filtering: i.e.
```
filter = 2
```

Normally it must be fixed.

**Comment by Shackkill** [comment]
Where do I have to put the downloaded file? And where do I change the settings of fbmask and filter

Date: Tue, 30 Jun 2015 02:34:09 -0700

**Comment by gregory38** [comment]
In the plugins directory. You need to edit GSdx.ini file.

**Comment by Shackkill** [comment]
I can't find a GSdx.ini file...

Date: Tue, 30 Jun 2015 10:00:06 -0700

**Comment by gregory38** [comment]
the ini file is in the ini directory. The new plugin must be copied into the plugin dir.

**Comment by Shackkill** [comment]
Where can I find all this?

Date: Tue, 30 Jun 2015 10:11:30 -0700

**Comment by gregory38** [comment]
In your PCSX2 installation. If it is too complicated for you, you will have to wait a newest release.

**Comment by Shackkill** [comment]
This is how my PCSX2 folder looks like: http://gyazo.com/31545b4e030a992d3bcd761e402bf99e. I can't find a ini folder/directory.

Date: Tue, 30 Jun 2015 10:16:33 -0700

**Comment by gregory38** [comment]
Sorry I can't help you on that.

**Comment by Shackkill** [comment]
Is it this: http://gyazo.com/eff30262c4046e2f91ee4e5c8654d976 ?

Date: Tue, 30 Jun 2015 10:20:36 -0700

**Comment by gregory38** [comment]
Yes.

**Comment by Shackkill** [comment]
There is no accurate_fbmask ....

Date: Tue, 30 Jun 2015 10:26:34 -0700

**Comment by gregory38** [comment]
of course you need to add it

**Comment by Shackkill** [comment]
Still doesn't work :/

Date: Tue, 30 Jun 2015 10:34:48 -0700

**Comment by gregory38** [comment]
Ok. It seems it need more work. Report for another users
```
players shorts still getting some red color corruption and shadows are too dark
``

**Comment by prafullpcsx2** [comment]
Can be considered fixed now, I guess.

**Comment by Shackkill** [comment]
Well it is still not fixed.
On Jul 5, 2015 21:50, prafullpcsx2 <notifications@github.com> wrote:Can be considered fixed now, I guess.

**Comment by karasuhebi** [comment]
Is it fixed or not?

**Comment by Shackkill** [comment]
No it isn't :/
On Aug 4, 2015 15:17, "Jaime J. Denizard" <notifications@github.com> wrote:Is it fixed or not?

**Comment by willkuer** [comment]
This is not a support forum. Open your support request in the support forum. Git is mostly for developer discussion.

**Comment by karasuhebi** [comment]
I'm pretty sure this is a valid bug report based on the back-and-forth between Shackkill and @gregory38.

**Comment by ssakash** [comment]
@Shackkill 
accurate FB mask is removed from the latest development builds so that variable won't do anything in the INI file. try different levels of blending unit accuracy and report back. @prafullpcsx2 did say that the issue was solved.

**Comment by gregory38** [comment]
It must work in openGL with normal filtering and a high enough level of accuracy blending ( I think basic might be enough). Configuration can be done in the GUI now.

**Comment by prafullpcsx2** [comment]
I tested the game again and I can confirm that it's fixed. Remember that the fix won't work if you have texturing filtering set to full or you have enabled HW hacks.

**Comment by Shackkill** [comment]
How can I change the levels of unit accuracy blending?

Date: Fri, 14 Aug 2015 06:52:38 -0700

**Comment by ssakash** [comment]
How can I change the levels of unit accuracy blending? 

Blending unit accuracy in the GSdx plugin settings.

**Comment by karasuhebi** [comment]
@Shackkill:
![2015-08-29 13_55_13-settings](https://cloud.githubusercontent.com/assets/6857825/9563559/945419fa-4e55-11e5-89ca-01753122f9cc.png)

**Comment by Shackkill** [comment]
My screen doesn not show blending accuracy: https://gyazo.com/b6a652290a2dd0be9169ffbc97450fd3

Date: Sat, 29 Aug 2015 10:55:39 -0700

**Comment by karasuhebi** [comment]
You're supposed to use the latest development version. Download it here:
http://buildbot.orphis.net/pcsx2/index.php

**Comment by atomic83GitHub** [comment]
This issue can be close as the game use the Giffifo which was added to it month ago.

**Comment by lightningterror** [comment]
Game should be rendered correctly on D3D now as well with fbmask blending.

**Comment by AhayriSG** [comment]
SLUS-21369 with [1.7.0-20220102140416](https://github.com/PCSX2/pcsx2/pull/5252)
OpenGL (full blending), D3D11 (high blending), Vulkan (full blending), Software, Turning off MTVU
![Capture](https://user-images.githubusercontent.com/59465544/148076015-c5e9a505-3566-4cef-96d9-83dc5c2965c1.JPG)

**Comment by refractionpcsx2** [comment]
Should be fine if you have automatic gamefixes enabled and you're not messing with speedhacks or any manual fixes.

**Comment by AhayriSG** [comment]
> Should be fine if you have automatic gamefixes enabled and you're not messing with speedhacks or any manual fixes.
> 
> You might need to adjust the EE cycle rate down, I forget..
> 
> Either way, game sucks, I hate it. Same with FIFA 2005

yeah, EE Cycle Rate needs +1 guys.
