### ISSUE TITLE
[BUG]: Crash when loading WRC4 with Qt

### ISSUE THREAD

**Issue by stuken** [PCSX2/pcsx2#6164]
### Describe the Bug

Attemping to boot WRC4 results in the emulator crashing when using the new Qt interface. The same redump verified iso boots correctly under the previous wxWidgets interface.

### Reproduction Steps

Simply launch WRC4 via the Qt interface.

### Expected Behavior

Game boots as it did under wxWidgets interface.

### PCSX2 Revision

v1.7.2788

### Operating System

Windows 10 (64bit)

**Comment by stenzek** [comment]
Crash dump file?

**Comment by stuken** [comment]
[pcsx2-qtx64-avx2.exe.6808.zip](https://github.com/PCSX2/pcsx2/files/8761545/pcsx2-qtx64-avx2.exe.6808.zip)

**Comment by stenzek** [comment]
Game is TLB missing. Already fixed by https://github.com/PCSX2/pcsx2/pull/6162

**Comment by stuken** [comment]
Afraid it's still not totally fixed. The hard crash has gone but it is now going into an endless incrementing loop of

```
(EE pc:004006B8) TLB Miss, addr=0x22000000 [load]
(EE pc:004006B8) TLB Miss, addr=0x22000000 [store]
(EE pc:004006B8) TLB Miss, addr=0x22000001 [load]
(EE pc:004006B8) TLB Miss, addr=0x22000001 [store]
(EE pc:004006B8) TLB Miss, addr=0x22000002 [load]
```

**Comment by refractionpcsx2** [comment]
Have you disabled Game Fixes under Advanced System? or Compatibility Patches (same place)? As the game requires a patch to not crash, and it is in the GameDB, at least for the PAL version.

**Comment by stuken** [comment]
This is out of the box settings so patching is enabled. Patching is showing up in the logs:

```
[GameDB] Searching for 'sces-52389' in GameDB
[GameDB] Found 'sces-52389' in GameDB
No game settings found (tried 'C:\Users\Stuart\Downloads\pcsx2-v1.7.2789-windows-64bit-AVX2-Qt\gamesettings\AFD06CBA.ini')
Applying settings...
GS Lookup CRC:AFD06CBA
[GameDB] Searching for 'sces-52389' in GameDB
[GameDB] Found 'sces-52389' in GameDB
(GameDB) Enabled Gamefix: XGKick
Updating CPU configuration...
iR3000A Recompiler reset.
(SetEmuThreadAffinities) Not implemented
[GameDB] Searching for 'sces-52389' in GameDB
[GameDB] Found 'sces-52389' in GameDB
[GameDB] Searching for patch with CRC 'AFD06CBA'
[GameDB] Found and falling back to default patch
Author: kozarovv
patch 0,EE,0040000C,double,3c0500603cc70054
patch 0,EE,00400014,double,24a5001024840010
patch 0,EE,0040001C,double,7ca6000078860000
patch 0,EE,00400024,double,000000001487fffb
patch 0,EE,0040002c,double,000000000817fff5
patch 0,EE,005fffd4,double,3c1c70003c040060
patch 0,EE,005fffdc,double,3c0700003c067000
patch 0,EE,005fffe4,double,279c000024840800
patch 0,EE,005fffec,double,24e7100024c60080
patch 0,EE,005ffff4,double,00c7e8200818000c
(GameDB) Patches Loaded: 10
EE/iR5900-32 Recompiler Reset
GS Lookup CRC:AFD06CBA
(EE pc:004006B8) TLB Miss, addr=0x22000000 [load]
(EE pc:004006B8) TLB Miss, addr=0x22000000 [store]
(EE pc:004006B8) TLB Miss, addr=0x22000001 [load]
(EE pc:004006B8) TLB Miss, addr=0x22000001 [store]
```

**Comment by refractionpcsx2** [comment]
hmm, yeah I can confirm it works in Wx but not Qt, which is strange because the interface shouldn't interfere with the emulation, unless there's a bug in loading "double" patches in Qt (hard to tell unless we use the debugger PR, but then it needs it on ELF decompression, so you gotta be quick lol

**Comment by stuken** [comment]
Does appear to be falling over trying to patch. Debugged locally and it's failing at 
>	pcsx2-qtx64-dbg.exe!vtlb_memWrite64(unsigned int mem, const unsigned __int64 * value) Line 272	C++

Address and patch values are correct as per the yaml input though.

**Comment by refractionpcsx2** [comment]
yes, I've already talked to Sten, it's due to the different timing in applying patches between WX and Qt, he's working on it.,
