### ISSUE TITLE
[BUG]: Emulation slowdown when using DsHidMini's SCP XInput Bridge (Proxy DLL)

### ISSUE THREAD

**Issue by macardiel** [PCSX2/pcsx2#6443]
### Describe the Bug

When running Metal Gear Solid 2: Substance while using a wired Dualshock 3 controller via DsHidMini's SCP XInput Bridge, a proxy XInput DLL, the emulation will slow down gradually. 
![image](https://user-images.githubusercontent.com/25373353/174389863-d015f191-0ba7-4205-bace-fa7dbdb713e7.png)
Sometimes as slow as 50% emulation speed. 
Emulation will return to normal once the controller is disconnected.
![image](https://user-images.githubusercontent.com/25373353/174389889-81622d28-8957-4d9d-8f48-2ad196a287fd.png)
All features of the DsHidMini work perfectly, including pressure-sensitivity on buttons when using SXS Mode, the only issue is the gradual degradation in emulation speed.
For more info on DsHidMini and the proxy DLL please see these references:

- https://vigem.org/projects/DsHidMini/SCP-XInput-Bridge/
- https://vigem.org/projects/DsHidMini/HID-Device-Modes-Explained/
- https://github.com/PCSX2/pcsx2/issues/6233

### Reproduction Steps

- Place the proxy DLL **Xinput1_3.dll** from DsHidMini's ~\x64 directory inside PCSX2's root directory
- run DsHidMini Control and ensure the Dualshock 3 gamepad's **HID Device Mode** is set to **SXS (Steam, RPCS3)**
- Run PCSX2 and configure the Xinput gamepad's buttons (Autoconfig works but it inverts the analog sticks Y axes)
- Run Metal Gear Solid 2: Substance (SLUS-20554)
- As the game progresses, the emulation speed will gradually degrade as shown in the pictures
- When disconnecting gamepad, emulation will return to normal

### Expected Behavior

As the game progresses, the emulation speed will gradually degrade as shown in the pictures

1. After ~2 minutes
![image](https://user-images.githubusercontent.com/25373353/174389863-d015f191-0ba7-4205-bace-fa7dbdb713e7.png)

2. After disconnecting gamepad completely (remove USB)
![image](https://user-images.githubusercontent.com/25373353/174389889-81622d28-8957-4d9d-8f48-2ad196a287fd.png)

### PCSX2 Revision

PCSX2 Nightly - v1.7.2954

### Operating System

Windows 10 (64bit)

**Comment by refractionpcsx2** [comment]
It's a known, reported upstream problem, nothing we can do about it.  Being tracked here https://github.com/ViGEm/DsHidMini/issues/225

**Comment by macardiel** [comment]
Thank you, I'm glad to know this has eyes on.

**Comment by andutrache** [comment]
this is fixed now and new DLL has been posted here: https://github.com/ViGEm/DsHidMini/issues/214

**Comment by Gabriel2Silva** [comment]
Not fixed for me. Using the XInput Bridge makes me lose around 40 to 50% performance, rendering games such as MGS2 and Onimusha 3 unplayable due to being unable to maintain stable 60fps. The emulation speed decrease is not gradual, it is already there as soon as you open the game. I don't know exactly how can I provide more info.

**Comment by refractionpcsx2** [comment]
well either way you need to take it up with them, telling us isn't going to resolve anything.
