### ISSUE TITLE
Metal Gear Solid 3: Subsistence (E) Cutscene Freeze.

### ISSUE THREAD

**Issue by AmbientMalice** [PCSX2/pcsx2#647]
Game is SLES-82042 running on a Core Quad 3Ghz and an Nvidia GTX 750Ti. PCSX2 version 1.3.1-647

During the cutscene between Sokolov and Snake discussing EVA, the emulator freezes when using any of the hardware renderers. Worse, the emulator can jam up the entire PC.

![gsdx_20150711205448](https://cloud.githubusercontent.com/assets/10704701/8633529/4652aef8-2810-11e5-89a6-8bb1ce234693.jpg)

Issue is likely related to https://github.com/PCSX2/pcsx2/issues/642 since the game suffers huge VRAM usage spikes.

The culprit seems to be this visual effect.

![gsdx_20150711210349](https://cloud.githubusercontent.com/assets/10704701/8633536/88e91f04-2810-11e5-9cf7-5005c52c6253.jpg)

Save State:
https://mega.co.nz/#!J0wiWaTT!M-qjuAUVFFJpcJwQjx7FXktptpfGq9_3wn7xe13Hi_Q

**Comment by gregory38** [comment]
Could you test latest version? A memory leak was fixed.

**Comment by AmbientMalice** [comment]
Nope. Still freezes using latest GSDX, sadly. Also, I've noticed the problem also occurs during Snake's vampire slaying minigame dream.

**Comment by gregory38** [comment]
Could you enable paltex and use native resolution. It will reduce the VRAM/RAM requirements.

**Comment by AmbientMalice** [comment]
With 8bit textures and native resolution, the game consumes 1.6GB of VRAM during the vampire minigame dream sequence. This is kinda okay for my GTX 750Ti, but it's gonna cause massive problems for people with 1GB (and less) GPUs.

**Comment by gregory38** [comment]
Well. GPU have more and more RAM so it will become less and less important.

Anyway, I know the game uses a special trick to postprocess the screen. It splits the screen into very small RT (64x32 pixels). GSdx will allocate a full RT (1280x1024 pixels) for each small RTs. You can imagine the number of useless MB allocated. I hope I will be able to correct it in the future but it isn't easy and it will require massive change.

**Comment by gregory38** [comment]
Please test latest GIT. Memory alllocation was improved to avoid various useless allocation.

**Comment by AmbientMalice** [comment]
Seems fixed. Good work.
