### ISSUE TITLE
[BUG]: Monopoly: Top left half of the screen shows the top right half of the screen.

### ISSUE THREAD

**Issue by Meerkov** [PCSX2/pcsx2#7468]
### Describe the Bug

See image. Top left half of the screen shows the top right half of the screen.

During FMVs it looks normal.

### Reproduction Steps

Start the game, and notice the top half of the screen is broken.
![image](https://user-images.githubusercontent.com/8139496/204058109-25fc83c7-ee6b-4129-84fc-0b0fe9266a59.png)

### PCSX2 Revision

1.6.0

### Operating System

Windows 10 (64bit)

### CPU

i9-9900k

### GPU

RTX 3060

**Comment by refractionpcsx2** [comment]
Can you try the latest development build to see if the issue still exists?

you can find them on our download page on pcsx2.net (scroll down once there)

**Comment by refractionpcsx2** [comment]
One of our tested checked it, and it's still an issue, but please upgrade before reporting any new issues, in case we've already fixed it, thanks :)

**Comment by Meerkov** [comment]
Thanks, I upgraded to the Nightly instead of the latest release (which looks like it's from 2020). Still reproduces, thanks for checking

**Comment by refractionpcsx2** [comment]
yep, 1.6 is pretty old now, we've fixed a lot of stuff since :P

**Comment by Meerkov** [comment]
Same bug appears in Trivial Pursuit

**Comment by Rex000** [comment]
Still the same problem in the latest nightly v1.7.4009
![Monopoly_SLUS-21753_20230205002034](https://user-images.githubusercontent.com/28770012/216785964-da7be95d-7848-4720-9ff8-99d25372defd.png)
![Monopoly_SLUS-21753_20230205002038](https://user-images.githubusercontent.com/28770012/216785968-a5c29b6b-3751-4d5d-a5af-5bff5531c799.png)
![Monopoly_SLUS-21753_20230205002116](https://user-images.githubusercontent.com/28770012/216785971-bae39178-3003-4489-bdd7-2f403834e896.png)
![Monopoly_SLUS-21753_20230205002313](https://user-images.githubusercontent.com/28770012/216785972-3136a623-cad8-443d-98b6-1277b196a6a4.png)
![Monopoly_SLUS-21753_20230205002336](https://user-images.githubusercontent.com/28770012/216785975-6b33e355-3be3-4a73-8a0a-bb227f654b30.png)
