### ISSUE TITLE
 Black: strange bugs in software and hardware mode.

### ISSUE THREAD

**Issue by ghost** [PCSX2/pcsx2#84]
Sky, post-processing effects and many textures are missing you can get stuck in walls/objects ,occasionaly be teleported to some other place and also occasionaly view can be locked in a spinning loop.

**Comment by gregory38** [comment]
Could you test the SW renderer on latest git ? A couple of bug were fixed so maybe yours.

**Comment by charliebruce** [comment]
Can confirm that the misplaced polygon issue still exists - tested with the latest version from git, OpenGL software renderer.

![gsdx_20150816150154](https://cloud.githubusercontent.com/assets/2148474/9293600/19dca0ce-4429-11e5-9d1f-fa6e7963d6f6.png)

Dump:

http://cjb248.com/pcsx2dump/black-misplaced-polygons.zip

.

**Comment by gregory38** [comment]
You mean the light effect. Based on the screenshot the issue feels like Jak games.

**Comment by MrCK1** [comment]
A [recent bug report](http://forums.pcsx2.net/Thread-GSDX-Hardware-mode-Bug-Report-Black-PAL-Graphical-Bug-s?pid=504006&highlight=Black#pid504006) didn't mention any of the issues mentioned here. A few post-processing effects still aren't emulated correctly. 

Anyone able to confirm this?

**Comment by AmbientMalice** [comment]
The game emulates very well now. Extremely resource intensive, though. Makes SotC look like a bit of a joke.
DOF effects work properly.
![gsdx_20160430013120](https://cloud.githubusercontent.com/assets/10704701/14921104/c047e422-0e73-11e6-8de9-7b42f1e2bdd5.png)

High Blending:
![gsdx_20160430013315](https://cloud.githubusercontent.com/assets/10704701/14921127/ddee64ec-0e73-11e6-9cfc-54c4a9830e18.png)

Full Blending:
![gsdx_20160430013323](https://cloud.githubusercontent.com/assets/10704701/14921137/eabae100-0e73-11e6-847e-4f7be05dec7a.png)

The game looks wrong without Full Blending, which carries a ridiculous performance hit.

**Comment by gregory38** [comment]
@AmbientMalice 
What is your CPU (model and frequency) and your GPU brand?

**Comment by charliebruce** [comment]
@AmbientMalice What settings were you using for that? 

I just built the latest version from git. The weird light effect is still present for me. Have tried OGL HW/SW. DX9 and DX11 HW also has massive bloom, that grows over the course of a few seconds, eventually turning in to the white HUD-only image posted in that forum thread. 

Enabling OpenGL HW hacks (specifically, having skipdraw=1) causes a similar kind of bloom to that seen with DX9/11.

**Comment by AmbientMalice** [comment]
@gregory38 Intel Q9400 @3.2Ghz. Nvidia GTX 750Ti.

**Comment by charliebruce** [comment]
@AmbientMalice I think it's loaded the latest version of the plugin - the date in the Config->GS menu is today. I just tried booting the game again with those settings and got this:

![black](https://cloud.githubusercontent.com/assets/2148474/14921785/e4cc4c04-0e2b-11e6-8b14-f3a7ef72d58d.PNG)

**Comment by AmbientMalice** [comment]
@charliebruce What is your GPU?

**Comment by charliebruce** [comment]
@AmbientMalice It's a Nvidia 765M laptop GPU (it also has an Intel 4600 graphics card, it's an Optimus machine). From PCSX2 console:

> Current Renderer: OpenGL (Hardware mode)
> 3.x GL context successfully created
> OpenGL information. GPU: GeForce GTX 765M/PCIe/SSE2. Vendor: NVIDIA Corporation. Driver: NVIDIA 359.06

I've edited my previous post to include more info about the plugin I'm using by the way.

**Comment by gregory38** [comment]
Could you someone give a shot on #1843 ? It fixes a small issue with the SW renderer.

**Comment by gregory38** [comment]
@AmbientMalice @charliebruce I need your feedback on master and the above PR. Severals SW renderer fixes have been done.

**Comment by atomic83GitHub** [comment]
Now, the software and the OpenGL render are perfect but there is a serious issue maybe unrelated, sometimes the character can get stuck in the game environnement and/or be teleported randomly in the game map. And there is a place in the game that is nearly unplayable due to this (inside the weapon factory), the camera become buggy as hell and can crash the game with some flashy color on the screen, the interesting fact is this is only happening in this portion of the level, I will try to do a blockdump on this.

**Comment by lightningterror** [comment]
That doesn't seem like a GSdx issue. Try playing with the clamping modes or similar options. That usually solves those kinds of bugs.

**Comment by MrCK1** [comment]
@atomic83GitHub Can you do another check on this when you get a chance, such as using @lightningterror 's suggestions?

**Comment by atomic83GitHub** [comment]
@MrCK1 I tried various clamping/rounding modes as well as some hacks but nothing succeed. Although, the M-bit build seems to fix level 4 craziness but introduce camera bugs and don't solve the "getting stuck/teleported in the game environnement" issue.

**Comment by morgens** [comment]
Was someone able to find a solution for polygons bug? My screen looks like this on PCSX2 1.4.0 Hardware OpenGL. Tried different setting without luck
![pcsx2 screenshot 2018 07 08 - 09 22 43 52](https://user-images.githubusercontent.com/17810566/42417352-84cb68fe-8290-11e8-956e-454e83890ea7.png)

**Comment by AmbientMalice** [comment]
@morgens PCSX 1.4.0 is pretty ancient. Use this instead. https://buildbot.orphis.net/pcsx2/

**Comment by morgens** [comment]
@AmbientMalice Thanks! Tried it, and after some further testing and settung VUs->Clamping Mode this polygon bug is gone. There is still a problem with black sky and the lighting looks a bit odd, like some pixel shaders are missing, will look into it later. If there is a nice solution, please let me know.
![pcsx2 screenshot 2018 07 08 - 09 59 35 81](https://user-images.githubusercontent.com/17810566/42417552-0f5d4942-8296-11e8-8a06-a147bf8a46aa.png)

**Comment by morgens** [comment]
@AmbientMalice OpenGL. On DirectX i have a very bright shaders that make the screen lit by white color or on some levels like in the very first room with colors of light that is coming from windows. So it becomes unplayable.
![pcsx2 screenshot 2018 07 08 - 11 30 05 09](https://user-images.githubusercontent.com/17810566/42418129-a8572184-82a2-11e8-9435-e357856b7571.png)

**Comment by MrCK1** [comment]
Since the CRC hack is removed, the only questionable thing here remaining is the supposed polygon issues. Any updates/confirmations on that?

**Comment by buzzrad1** [comment]
Anyone ever play Black and get stuck in an area and are unable to move, forcing you to either quit the game or kill yourself?

**Comment by atomic83GitHub** [comment]
This is the unfamous COP2/VU0sync problem causing the character to be stuck into walls or just moving erratically.

**Comment by buzzrad1** [comment]
Aww, that's too bad. Thank you for your quick response!

**Comment by refractionpcsx2** [comment]
The teleporting and collision bugs are now fixed in master, closing this as #563 is tracking the black sky issue.
