### ISSUE TITLE
[GSDX] Soul Calibur III [NTSC-U]

### ISSUE THREAD

**Issue by ssakash** [PCSX2/pcsx2#895]
**_PCSX2 versions used:**_ pcsx2-v1.3.1-1256-gbbd74e5 (latest dev build)
**_Emulation settings:**_ "Safest" preset, no hacks.
**_Plugins used:**_ GSdx AVX2 using the OpenGL renderer and software mode.
**_Plugin settings:**_ CRC Hack Level "None"
#### Description:

Using the OpenGL renderer, character shadows seem to be missing. Also missing is the subtle scanline overlay. OpenGL Software mode works as expected.
## Screenshots:

OpenGL renderer. No character shadows and no scanline overlay.
![image:1](http://i.imgur.com/4of7qnI.jpg)

Software mode output, for reference:
![image:2](http://i.imgur.com/CzelVJ4.jpg)

**_GS dump**_ : http://forums.pcsx2.net/attachment.php?aid=57584

**Comment by gregory38** [comment]
Please test Dx, various accurate option

**Comment by prafullpcsx2** [comment]
If I tested correctly these shadows were fixed in software mode when @gabest11  recently fixed Lupin game. https://github.com/PCSX2/pcsx2/commit/42f51591df66c3b82d353dc6bb6aad7e14d1127d

So may be kinda hard to fix it in HW mode anytime soon.

**Comment by ssakash** [comment]
These shadows are present in all non-software renderers according to my tests. Problem still present on Ultra level of Blending unit accuracy.

**Comment by gregory38** [comment]
@prafullpcsx2 actually lupin fix isn't hard to implement (gabest did 99% of the job). The remaining issue is the impact on perf.

**Comment by lightningterror** [comment]
This has been fixed on OpenGL with Depth Emulation. Issue remains on Direct3D since it lacks Depth support.

**Comment by FlatOutPS2** [comment]
* Currently still needs CRC hacks to be disabled to fix it on OpenGL. ;)

**Comment by lightningterror** [comment]
Soon™
