### ISSUE TITLE
Ratchet & Clank - Blurred Background only in top left corner

### ISSUE THREAD

**Issue by Masamune3210** [PCSX2/pcsx2#914]
Version - 1.3.1-1282
Specs - i5 2500k @ 4.0 GHz, 11 GB RAM, GTX 660 3GB
In hardware mode, when the game is paused the entire background is grey except for the top left corner which is blurred correctly. Software mode handles this correctly, displaying the current screen blurred behind the pause screen.

Hardware - ![capture](https://cloud.githubusercontent.com/assets/1053504/10656992/132bbd22-784b-11e5-8c0e-1cd219e7b80e.PNG)

Software - ![capture](https://cloud.githubusercontent.com/assets/1053504/10657000/3740052e-784b-11e5-9899-dbdf289ff1f2.PNG)

Log - https://gist.github.com/deadair3210/3a6e1d8bbc8611583726

**Comment by yorkiesandskittles** [comment]
I'm guessing this is the same as the MGS2 issue?

**Comment by Dreadmoth** [comment]
Slight change in behaviour as of cb19451

Now draws a column of black below the correct top-left corner:
![ratchet1](https://cloud.githubusercontent.com/assets/8492684/14915283/0b131310-0e55-11e6-9d94-3c63ea41a0b9.png)

If the menu is accessed in software mode at any point before switching to hardware mode, that black area is replaced with a partial frame from software mode - stuck in place and does not update unless software mode is used again.
![ratchet2](https://cloud.githubusercontent.com/assets/8492684/14915401/04073622-0e56-11e6-9b35-30d26a8da212.png)

**Comment by Dreadmoth** [comment]
9cacfee improved the issue, now the entire column is rendered correctly:

![ratchet3](https://cloud.githubusercontent.com/assets/8492684/14942168/0cc12b6c-0ff8-11e6-8091-459e5fa421a8.png)

**Comment by gregory38** [comment]
@Dreadmoth could you provide me a gs dump please? (http://forums.pcsx2.net/Thread-How-to-create-a-proper-GS-dump)

**Comment by Dreadmoth** [comment]
Turns out I made a mistake in my earlier comment: I had the UserHacks_DisablePartialInvalidation hack enabled which was causing the black area - with that disabled the column renders correctly with cb19451 (and later commits)

GS dump: http://www.mediafire.com/download/bipvxqc2b5d1plh/Ratchet_and_Clank_menu_bug.zip

**Comment by gregory38** [comment]
I don't understand my log doesn't print anything about texture shuffle effect. So It is another effect. I don't think my commit really improve the situation.

**Comment by Dreadmoth** [comment]
Yeah, I made a mistake and assumed it was the newest changes which affected it. Sorry for wasting your time :/

Some relatively recent commit did improve it over the earlier behaviour, I'll see if I can track it down

**Comment by gregory38** [comment]
Don't bother. Likely better depth handling or random texture cache invalidation.

**Comment by MrCK1** [comment]
Anybody know if #1613 would have an effect on this issue? If nobody gets to it, I'll look later.

**Comment by gregory38** [comment]
No. It is a likely a texture cache issue. Not a scaling issue.

**Comment by tadanokojin** [comment]
Issue is caused by improper invalidation. Game downloads texture from EE and GSdx should invalidate the whole texture but instead only invalidates a single page.

**Comment by MegaAlen** [comment]
@stenzek Can you please look into this bug/issue? <3

**Comment by jascio** [comment]
Did some deep searching and found what initially improved (rendering entire column correctly in #1222) the issue and then introduced again in #1522,

I'm note a programmer but tried to change the IF statement and last function and it improved the render from the column to entire frame, don't know where i can post it (Here/Discord)?

I hoped this would help even other R&C titles but i was wrong it'll improve a little bit but not solve the problem R&C3 /Gladiator not tested R&C2.

I've not tested the entire game , and not even other games if this can break things but i'm sure it will.

<img width="739" alt="image" src="https://user-images.githubusercontent.com/77208830/164980585-7d1e8fc6-6d94-4c45-afb8-631582aaccaa.png">

<img width="738" alt="image" src="https://user-images.githubusercontent.com/77208830/164980561-e4b9b1fc-d96d-4a3c-9adc-8c9304f4e4b3.png">

Hoping that my poor , very base knowledge programming can help u understand this issue

**Comment by seta-san** [comment]
this is still happening on 1.7.4135

**Comment by refractionpcsx2** [comment]
this should be fixed in #8249

**Comment by matheusvb3** [comment]
This only fixes the first Ratchet & Clank, correct? Going Commando and Up Your Arsenal still have this issue.

**Comment by refractionpcsx2** [comment]
Bummer, I'll have to check them. Yes it was the first r&c which is what this issue was for

**Comment by matheusvb3** [comment]
Thanks for the quick response. Is there any way I can help? I can give GS dumps of those games if you need.

**Comment by refractionpcsx2** [comment]
Nah I have the games, just need to investigate it, thanks :)

**Comment by RenegadeScooter** [comment]
It's happening again! (I got this on v1.7.4272)
![Ratchet   Clank_SCUS-97199_20230324202428](https://user-images.githubusercontent.com/69838290/227689518-1ff55027-6d61-44cd-b7ab-dc23ab9b66a2.png)
I _swear_ it was fixed a while ago! Am I doing anything wrong?

**Comment by Dreadmoth** [comment]
> It's happening again! (I got this on v1.7.4272) [Ratchet Clank_SCUS-97199_20230324202428](https://user-images.githubusercontent.com/69838290/227689518-1ff55027-6d61-44cd-b7ab-dc23ab9b66a2.png) I _swear_ it was fixed a while ago! Am I doing anything wrong?

It was fixed. After more recent changes, Ratchet & Clank 1 and 2 seem to need Target Partial Invalidation enabled, like R&C3.

**Comment by RenegadeScooter** [comment]
> Ratchet & Clank 1 and 2 seem to need Target Partial Invalidation enabled

Where is that setting? I can't find it

**Comment by Dreadmoth** [comment]
> Where is that setting? I can't find it

It might be better to wait for it to be added as an automatic fix (or for the change in behaviour to be investigated a bit more), but if you need it right now:

Right-click game in game list  → Properties...  → Graphics section → Rendering tab  → check Manual Hardware Renderer Fixes  → Hardware Fixes tab  → check Target Partial Invalidation

**Comment by refractionpcsx2** [comment]
I thought it was already added :/

**Comment by Dreadmoth** [comment]
> I thought it was already added :/ like, last week.

Looks like it was only added to 3.
I made a PR #8479 , hopefully I didn't miss any versions of the games...

**Comment by refractionpcsx2** [comment]
Thanks! merged :)
