### ISSUE TITLE
[BUG]: Taiko no Tatsujin: Tatakon de Dodon ga Don | bottom screen in opening is glitched

### ISSUE THREAD

**Issue by SeruranBlue** [PCSX2/pcsx2#9912]
### Describe the Bug

Bottom screen in opening is glitched in HW.

HW:
![Taiko no Tatsujin - Tatacon de Dodon ga Don  with Tatacon _SLPS-20221_20230906193900](https://github.com/PCSX2/pcsx2/assets/121824800/9e6520b6-7a27-488d-aeea-cf5c5b843ecd)
SW:
![Taiko no Tatsujin - Tatacon de Dodon ga Don  with Tatacon _SLPS-20221_20230906193902](https://github.com/PCSX2/pcsx2/assets/121824800/875b9a53-254f-4458-834b-1cd5e849ef4d)

### Reproduction Steps

boot the game.

### Expected Behavior

![Taiko no Tatsujin - Tatacon de Dodon ga Don  with Tatacon _SLPS-20221_20230906193902](https://github.com/PCSX2/pcsx2/assets/121824800/2fe306a1-8151-47e1-abf8-9c6c86018be1)

### PCSX2 Revision

v1.7.4984

### Operating System

Windows 10 (64bit)

### Logs & Dumps

[Taiko no Tatsujin - Tatacon de Dodon ga Don [with Tatacon]_SLPS-20221_20230906193714.gs.zst.zip](https://github.com/PCSX2/pcsx2/files/12536436/Taiko.no.Tatsujin.-.Tatacon.de.Dodon.ga.Don.with.Tatacon._SLPS-20221_20230906193714.gs.zst.zip)

**Comment by SeruranBlue** [comment]
same glitch happen in Taiko no Tatsujin: DOKI! Shinkyoku Darake no Haru Matsuri.

**Comment by SeruranBlue** [comment]
I checked several old version:
1.6.0 - OK
1.7.2300 - OK
![2300](https://github.com/PCSX2/pcsx2/assets/121824800/076e5f86-6a7b-4fec-b065-1abc8ae7b1b0)
1.7.2301 - Glitched (rightmost)
![2301](https://github.com/PCSX2/pcsx2/assets/121824800/b2406fe1-3756-4a0d-9783-e50c4f2ba9d4)
1.7.2313 - Extremely glitched
![2313](https://github.com/PCSX2/pcsx2/assets/121824800/c6bd750b-b43b-4ed3-a056-b5b86d4b6384)
1.7.2375 - Super glitched
![2375](https://github.com/PCSX2/pcsx2/assets/121824800/ac753bd6-658b-4f41-a512-18e5e3db1ad3)
1.7.3003 - Glitched (rightmost)
![3003](https://github.com/PCSX2/pcsx2/assets/121824800/8ed92ab0-16ec-430c-9de9-36663e6e8af9)

so maybe regression from #5387 ? (I'm not sure...)

**Comment by refractionpcsx2** [comment]
I know what it's related to, I just need to deal with it.

**Comment by Mrlinkwii** [comment]
seemed fixed as of v1.7.5243 atleast with the gs dump

![image](https://github.com/PCSX2/pcsx2/assets/17685135/3bdf0414-ba3d-48d5-84d2-992b8123cbce)

**Comment by SeruranBlue** [comment]
![image](https://github.com/PCSX2/pcsx2/assets/121824800/5cc59bc3-2954-4150-9bf6-14d490ea6769)
still broken in actual game

**Comment by refractionpcsx2** [comment]
Oh yeah I need to fix this
