### ISSUE TITLE
[BUG]: WRC 3 [SCES-51684] Incorrect text rendering in Vulkan and OpenGL

### ISSUE THREAD

**Issue by Neutroni** [PCSX2/pcsx2#9979]
### Describe the Bug

Text in the game main menu renders wrong missing the top few lines of the font with Vulkan and OpenGL renderers, software renderer is correct.
Same issue affects WRC 4 Ford Fiest Sports Edittion Demo [SCED-52945]
Both BIOS and game(s) are PAL versions.

### Reproduction Steps

Launch the game and check text rendering in main menu with Vulkan or OpenGL renderer. "Time Trial" text should be most obvious comparison by missing top in letter T

### PCSX2 Revision

v1.7.5013

### Operating System

Linux (64bit) - Specify distro below

### If Linux - Specify Distro

Arch

### CPU

R5 3600

### GPU

RX 480

### GS Window Screenshots

Vulkan
![WRC 3_SCES-51684_20230917121906](https://github.com/PCSX2/pcsx2/assets/49252067/2e322141-1bd7-4734-8627-18d685d7687a)
OpenGL
![WRC 3_SCES-51684_20230917122013](https://github.com/PCSX2/pcsx2/assets/49252067/c0d27104-1afe-49d9-86d7-82c7dedfb9cd)
Software
![WRC 3_SCES-51684_20230917122000](https://github.com/PCSX2/pcsx2/assets/49252067/1584e3e3-e912-414a-b7bb-1d7b246da129)
I cant at this point in time get comparison from console due to failing laser, but below is from WRC 4 demo with has same issue
Vulkan
![WRC 4 - The Official Game of the FIA World Rally Championship  Ford Fiesta Sports Edition Demo _SCED-52945_20230917122144](https://github.com/PCSX2/pcsx2/assets/49252067/afbea90c-37be-4e4b-aac7-cfaa5c2cc737)
PS2
![PXL_20230917_090622617](https://github.com/PCSX2/pcsx2/assets/49252067/69ed047f-0785-40fc-b718-4b758d2870c7)

**Comment by Parallax71** [comment]
> ### Describe the Bug
> 
> Text in the game main menu renders wrong missing the top few lines of the font with Vulkan and OpenGL renderers, software renderer is correct. Same issue affects WRC 4 Ford Fiest Sports Edittion Demo [SCED-52945] Both BIOS and game(s) are PAL versions.
> ### Reproduction Steps
> 
> Launch the game and check text rendering in main menu with Vulkan or OpenGL renderer. "Time Trial" text should be most obvious comparison by missing top in letter T
> ### Expected Behavior
> 
> _No response_
> ### PCSX2 Revision
> 
> v1.7.5013
> ### Operating System
> 
> Linux (64bit) - Specify distro below
> ### If Linux - Specify Distro
> 
> Arch
> ### CPU
> 
> R5 3600
> ### GPU
> 
> RX 480
> ### GS Settings
> 
> _No response_
> ### Emulation Settings
> 
> _No response_
> ### GS Window Screenshots
> 
> Vulkan ![WRC 3_SCES-51684_20230917121906](https://user-images.githubusercontent.com/49252067/268493348-2e322141-1bd7-4734-8627-18d685d7687a.png) OpenGL ![WRC 3_SCES-51684_20230917122013](https://user-images.githubusercontent.com/49252067/268493360-c0d27104-1afe-49d9-86d7-82c7dedfb9cd.png) Software ![WRC 3_SCES-51684_20230917122000](https://user-images.githubusercontent.com/49252067/268493373-1584e3e3-e912-414a-b7bb-1d7b246da129.png) I cant at this point in time get comparison from console due to failing laser, but below is from WRC 4 demo with has same issue Vulkan ![WRC 4 - The Official Game of the FIA World Rally Championship Ford Fiesta Sports Edition Demo _SCED-52945_20230917122144](https://user-images.githubusercontent.com/49252067/268493599-afbea90c-37be-4e4b-aac7-cfaa5c2cc737.png) PS2 ![PXL_20230917_090622617](https://user-images.githubusercontent.com/49252067/268493658-69ed047f-0785-40fc-b718-4b758d2870c7.jpg)
> ### Logs & Dumps
> 
> _No response_

With HW renders I see it well, yes, at x2 (720p resolution)
W10, intel i7 6700, GTX 1070, 15Gb RAM...

![WRC 3_SCES-51684_20230918192847](https://github.com/PCSX2/pcsx2/assets/142044650/429c1a67-7823-49c9-89a0-94abe582417c)

**Comment by refractionpcsx2** [comment]
Can you provide a GS Dump

**Comment by Neutroni** [comment]
> Can you provide a GS Dump

Updated original report with a zip file containing 2 single frame frame GS dumps (One Vulkan and another OpenGL), still new to to this so presume that is what is needed.

**Comment by Parallax71** [comment]
> Can you provide a GS Dump

You ask me or Neutroni?

**Comment by refractionpcsx2** [comment]
I didn't really care who it was as long as somebody gave GS dumps showing the problem :P Looks like Neutroni did so, so thanks for that.

**Comment by JordanTheToaster** [comment]
Fixed by virtue of having round sprite full.

![image](https://github.com/PCSX2/pcsx2/assets/80843560/a987df13-0d8e-4a2d-a3bb-031070950735)

**Comment by refractionpcsx2** [comment]
and in native?

**Comment by Mrlinkwii** [comment]
<img width="1214" height="992" alt="Image" src="https://github.com/user-attachments/assets/51ffe698-c995-4573-838a-23b68c7d76de" /> still broken as of v2.5.153 at native

**Comment by TJnotJT** [comment]
Might be known already, but this seems to be because the game give V coordinates that are exactly on texel boundaries so rounding errors in the GPU floating point math cause the wrong texel to be sampled with nearest filtering. On my system the V coords used by the GPU are off  by < .01. At least in this case it might be fixable accurately at native res since the dv/dy gradient is exactly 1, so we could shift the Vs to be on texel centers (and same for U).
